### ISSUE TITLE
Open toot URL as a toot

### ISSUE THREAD

**Issue by carlosala** [mastodon/mastodon-android#10]
When you click in a toot URL (maybe posted in another toot) it opens an in-app browser or the default browser, depending on configuration.

I think would be interesting to have a config to open that toot in the app, in the detailed view of a toot.
Other apps (like Tusky) do so👌🏻

**Comment by grishka** [comment]
You mean when it links to your instance?

**Comment by carlosala** [comment]
Yes, that's it
