### ISSUE TITLE
Can't use multiple accounts 

### ISSUE THREAD

**Issue by githubgirly** [mastodon/mastodon-android#106]
I have two accounts for a pretty good reason, but it's not allowed or possible

**Comment by grishka** [comment]
You can long tap the avatar in the tab bar to open the account switcher. In the upcoming version we're adding an icon that hints at this.

![Screenshot_20220502-211539.png](https://user-images.githubusercontent.com/1478258/166302397-1ca3268d-5556-4573-9919-6b69c3ee2a9d.png)

**Comment by githubgirly** [comment]
Thank you so much! It was very much hidden to my eye

**Comment by grishka** [comment]
Yes, this is why we're adding this icon

**Comment by grishka** [comment]
I'm closing this because for all intents and purposes, this issue is now resolved.
