### ISSUE TITLE
Notifications don't work

### ISSUE THREAD

**Issue by Discostu36** [mastodon/mastodon-android#12]
Notifications don't seem to work. I haven't received a single one since I installed the app.

Android 11
Fairphone 4

**Comment by grishka** [comment]
Do you have Google services?

**Comment by Discostu36** [comment]
> Do you have Google services?

Yes, I do.

**Comment by grishka** [comment]
Could you please get logcat from when the app starts after being unloaded or force stopped? Or a bug report (the one from developer settings), that also includes logcat.

**Comment by Discostu36** [comment]
Is there an e-mail address I can send the bug report to? I don't want to share it in public, not knowing if it could contain private information.

**Comment by grishka** [comment]
Yes, send it to mail@grishka.me
Was this a clean installation or did you update from beta?

**Comment by Discostu36** [comment]
Clean installation. First from FDroid, then I reinstalled from GitHub APK to make sure it doesn't have to do with the FDroid package.

**Comment by Discostu36** [comment]
> Yes, send it to mail@grishka.me

Message was rejected because the bugreport file is above 10 MB

**Comment by grishka** [comment]
It's the year 2022 and 10 MB is still considered a big file by some services. Sigh.

Do you have Telegram? https://t.me/grishka

**Comment by grishka** [comment]
I don't see anything related to notifications at all 🤔
It behaves as if it did successfully register.

**Comment by Discostu36** [comment]
I do receive notifications now. I don't know why it didn't or why it does now. But i guess this can be closed.
