### ISSUE TITLE
Settings toggle refers to boosts as "reblogs" (English)

### ISSUE THREAD

**Issue by githubgirly** [mastodon/mastodon-android#120]
Only in other languages have I seen "boosts" renamed to "reblogs" or the such, an example is Italian with "Rebloggare." This is mostly used in Tumblr, and I'd be okay with it if this feature weren't called boosts in every other corner of the app. Favourites are still called favourites instead of likes and keeps that consistency unlike with boosts. It's under "Notifications" and "Notify me when..."

Sorry if this is nitpicking, I'm just trying to post all the inconsistencies I find in the app to make this better because I love the app a lot

**Comment by grishka** [comment]
It is also "reblogs" in the iOS app. Just yesterday I removed all remaining mentions of "boost".

> Sorry if this is nitpicking

It is.

**Comment by githubgirly** [comment]
Is it possible to make a setting to call them boosts still? Some people might prefer what was used in the past
