### ISSUE TITLE
Closed servers can still be found via Get started and related issues

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon-android#121]
1. When you click _Get started_ and search for a server that has closed registrations (e.g. todon.nl (note: not todon.eu), the server shows up.
2. Not the text from _joinmastodon.org/communities_, but the full _short server description_ text is shown (in the case of todon.nl very long). 
3. There is a select box in front of that text, so you can select this server, click Next and you see the server rules like you normally do.
4. Click Next again and you see the sign-up form. Submitting this form will fortunately give a 403 error.

This is of course very confusing for people and gives a bad impression, so hopefully you can put this on the priority list. I think closed servers should only show up in the search results when users click the _Log in_ button. Note that also there the complete _short server description_ text shows up, but only for servers who are closed for registrations, so that is probably related with the rest of this issue.

Edit: I found out that text from open servers, are pulled from joinmastodon.org, so I changed the wording.

**Comment by grishka** [comment]
Entering the full server domain in the search field bypasses all checks, this is by design.

**Comment by joenepraat** [comment]
> Entering the full server domain in the search field bypasses all checks, this is by design.

Why is that by design? Isn't it very confusing for new users trying to sign up on a server that is closed for registrations, and than getting an error? Those servers shouldn't there at all when searching via 'Getting started' or at least getting a message 'This server doesn't accept registrations'.

And there is also still point 2.

**Comment by charliemikels** [comment]
It makes sense that you'd still be able to access the server page anyways if you manually type the full name, but I would like a notice that says "Hey, you should know this server is not accepting registrations at this time." That way if I tell a user that I'm on toot.cafe, and if they try to find my server in the app, they won't accidentally get too far into the process before being told "you still can't make an account here."

**Comment by grishka** [comment]
Yes, this alert is already implemented as a fix for #377 because indeed letting someone enter their data only to be met with an API error is not a good idea.

**Comment by charliemikels** [comment]
I agree, but that warning should also appear much earlier. A user should be able to reach the create an account page, but they should know their registration might not be accepted. Just a little text in red at the top of the search result or the Ground Rules page would help a lot.

**Comment by grishka** [comment]
The alert appears when you try to proceed from the server list screen. Can't be much earlier.

**Comment by charliemikels** [comment]
Hmm. I didn't get one when I went through. Could you check toot.cafe on your end? The app gave me no warnings about it, but the website says it's closed.

![Screenshot_20221120-115432.png](https://user-images.githubusercontent.com/20339866/202914992-17f46df1-30c1-47ab-a601-2f3095d37aa9.png)
![Screenshot_20221120-115436.png](https://user-images.githubusercontent.com/20339866/202915000-13134703-6b17-4f99-a785-ea1302f8f998.png)
![Screenshot_20221120-115439.png](https://user-images.githubusercontent.com/20339866/202915004-0f2ea5d0-e408-47c9-8c1b-19f57e85f4a6.png)

**Comment by grishka** [comment]
> Hmm. I didn't get one when I went through

I just added it today. It's obviously not in any production versions and not even in any beta yet.

**Comment by charliemikels** [comment]
Oh I didn't realize the change was so recent. My bad. I look forward to seeing it in the stable build.
