### ISSUE TITLE
Domain verification not displayed

### ISSUE THREAD

**Issue by cassidyjames** [mastodon/mastodon-android#125]
Domain verification shows on the web as [described by @Gargron](https://mastodon.social/@Gargron/108245858984927046) 

![Screenshot_20220504-155528.png](https://user-images.githubusercontent.com/611168/166832338-2d915c90-74da-4417-bfb1-bc8557fcdbd2.png)

but it doesn't appear in the app.

![Screenshot_20220504-155459.png](https://user-images.githubusercontent.com/611168/166832324-781c2b3e-1aa3-4e54-912e-b88b52b733ed.png)

**Comment by edent** [comment]
See also https://github.com/mastodon/mastodon-ios/issues/312
