### ISSUE TITLE
New Follower/Following List lets you attempt to follow yourself

### ISSUE THREAD

**Issue by GlenMerlin** [mastodon/mastodon-android#127]
In the latest update just pushed you can view follower/following for individual accounts

however this will display yourself as a potential option and throw a "record not found" error when you attempt to follow yourself

it would probably be better if the option was grayed out or the button simply didn't show if it is on your account

![Screenshot_20220504-223719.png](https://user-images.githubusercontent.com/43477600/166864279-e3b01b57-b1bc-46ba-b8b3-db283179747e.png)

**Comment by realpixelcode** [comment]
Yeah, I can confirm this.

**Comment by grishka** [comment]
Oh. I meant to hide that button for your own account, but forgot 🙈
