### ISSUE TITLE
Add tooltips to bottom navigation bar

### ISSUE THREAD

**Issue by Poopooracoocoo** [mastodon/mastodon-android#132]
Either that, or add labels.

**Comment by grishka** [comment]
Why? They already have content descriptions for screen readers.

**Comment by Poopooracoocoo** [comment]
I just didn't know what the tab with the search icon was. Tapping and holding didn't tell me the name and so I just guessed that it was a search tab when it could've been explore or discover. I'm really used to tapping and holding to see tooltips but no worries, this is really minor.
