### ISSUE TITLE
Image not fully visible when adding alt text

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#139]
Only a cropped version of the image is displayed when adding an alt text - which makes it hard to actually describe the image.
Could be more like on Twitter, where the image is actually scrollable, and the text area is fixed to the bottom.

![Screenshot_20220506-172013319](https://user-images.githubusercontent.com/6217438/167163135-f41a842f-9df8-4ca8-b1e3-1762a09aa06f.jpg)

**Comment by githubgirly** [comment]
+1, I had this issue too many times!

**Comment by grishka** [comment]
This was fixed in M3 redesign by allowing the image to be opened in a full-screen media viewer.
