### ISSUE TITLE
Can't make an account on todon.eu

### ISSUE THREAD

**Issue by joenepraat** [mastodon/mastodon-android#14]
When you fill in everything and press Next, nothing happens. When you press a few times Next, you get the message 'Too many request'. Todon.eu requires approval, so maybe it has something to do with that?

![Screenshot_20220414-193302_Mastodon](https://user-images.githubusercontent.com/41594439/163443163-cab30ec1-377f-4a07-9b11-0a639a298f79.png)

**Comment by joenepraat** [comment]
Thanks @grishka !

**Comment by joenepraat** [comment]
@grishka I like to re-open this issue, because it still doesn't work for todon.eu. I tested it with another approval required server and there it works. It has probably to with the small local code changes I did in app/views/about/show.html.haml, so we could add an localized and context specific text. So maybe you can tell me how the code recognizes an approval required server? Because than I can make some necessary changes to make it work.

**Comment by grishka** [comment]
> So maybe you can tell me how the code recognizes an approval required server?

By looking at the `approval_required` field in the instance object (`/api/v1/instance`). No HTML parsing is involved.

**Comment by joenepraat** [comment]
Thanks, I will check this out tomorrow.

**Comment by joenepraat** [comment]
Yes, it works indeed. It was because of a delay between changing the setting and the api. I found another bug, but I will add that later today in another issue.
