### ISSUE TITLE
joe biden will be posting in 6 seconds

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#149]
![Screenshot_20220508-230018294](https://user-images.githubusercontent.com/6217438/167315697-b3fa0ac3-989a-4c47-bce9-d2e3295b2b16.jpg)
joe biden shouldn't be tooting in the future

**Comment by acoolstraw** [comment]
:verified:

**Comment by grishka** [comment]
What should I do in this case? Show it as "0s" regardless?

> :verified:

Probably was not returned in the `emojis` array in the account object.

**Comment by sk22** [comment]
> What should I do in this case? Show it as "0s" regardless?

oh… i wasn't considering that this could actually happen because my phone's time's not in sync with the instance's time… hm

**Comment by hazysu** [comment]
I think making it display as 0s for negative values would suffice. Some apps do "Right Now" or something equivalent for when a timer like this is from less than a minute or so, but I think being a bit more specific does no harm even if it's possible it's slightly off due to time synchronization

**Comment by sk22** [comment]
I think, "Just now" would fit nicely. Would also feel more natural than having "0s" stay, potentially even after refreshing

**Comment by Gargron** [comment]
Mastodon's web app says "now"

**Comment by realpixelcode** [comment]
This often happens with my own toots.

![](https://user-images.githubusercontent.com/52963327/167358354-977785f1-aaec-406c-8eb8-937b26cd7096.png)

> joe biden shouldn't be tooting in the future

 Though, I'd really appreciate him joining the fediverse 😅

**Comment by acoolstraw** [comment]
he is on the fediverse, in two forms:
Joe Biden (real, inactive [monument]): `@joebiden@social.linux.pizza`
Joe Biden (active): `@joebiden@fuckgov.org`

**Comment by acoolstraw** [comment]
safe to say that Joe Biden will no longer by posting in 6 seconds

**Comment by grishka** [comment]
He will be posting "now"
