### ISSUE TITLE
LibreAV Malware Detected

### ISSUE THREAD

**Issue by HiperFall** [mastodon/mastodon-android#15]
Scanning apps on a device with LibreAV antivirus software shows an issue with Mastodon App.
![Screenshot_20220414-210252](https://user-images.githubusercontent.com/11684093/163459060-87b8ded8-6df3-44ae-9793-2038acc49059.png)

**Comment by Gargron** [comment]
Any other details or reasoning?

**Comment by HiperFall** [comment]
> Any other details or reasoning?

No, that's all it says. Other apps on my device are okay. That's strange though.

**Comment by morta5** [comment]
> Any other details or reasoning?

This app works with machine learning btw

**Comment by PoorPocketsMcNewHold** [comment]
https://github.com/projectmatris/antimalwareapp
Too vague, and too young method to be considered a mature method of malware detection. As showcased on their README.md

> ⚠️⚠️ PLEASE BE AWARE THAT LIBREAV IS STILL IN ITS EARLY STAGES OF DEVELOPMENT AND MAY CONTAIN A LOT OF FALSE POSITIVES IN PREDICTION. THIS PROJECT IS DEVELOPED FOR EDUCATIONAL PURPOSES ONLY AND WE MAKE NO GUARANTEE THAT THE OUTPUT PRODUCED BY LIBREAV IS ABSOLUTELY CORRECT. SO PLEASE DO NOT JUDGE OTHER APPLICATIONS USING THE OUTPUT OF LIBREAV ALONE.⚠️⚠️

OP failed to do further researches.

**Comment by HiperFall** [comment]
> https://github.com/projectmatris/antimalwareapp Too vague, and too young method to be considered a mature method of malware detection. As showcased on their README.md
> 
> > ⚠️⚠️ PLEASE BE AWARE THAT LIBREAV IS STILL IN ITS EARLY STAGES OF DEVELOPMENT AND MAY CONTAIN A LOT OF FALSE POSITIVES IN PREDICTION. THIS PROJECT IS DEVELOPED FOR EDUCATIONAL PURPOSES ONLY AND WE MAKE NO GUARANTEE THAT THE OUTPUT PRODUCED BY LIBREAV IS ABSOLUTELY CORRECT. SO PLEASE DO NOT JUDGE OTHER APPLICATIONS USING THE OUTPUT OF LIBREAV ALONE.⚠️⚠️
> 
> OP failed to do further researches.

Sorry, don't hate me, pls. 😔
