### ISSUE TITLE
Not all voice note timecodes stay in one line

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#151]
In voice notes, sometimes the timecode overflows, causing it to look like this:

![Screenshot_20220509-082044682](https://user-images.githubusercontent.com/6217438/167351838-b2af327a-7362-49b8-8556-6f4b18c76880.jpg)
![Screenshot_20220509-082048149](https://user-images.githubusercontent.com/6217438/167351862-d8ba495a-3dd0-4840-90c3-ad6c10c180aa.jpg)

The initial width seems to also affect this - an audio with 0:16 seconds has more of these (including every number below 0:10) than one with 0:08.

**Comment by grishka** [comment]
This is what you get for using custom fonts.

**Comment by sk22** [comment]
oh i'm so sorry for using the wrong font for your app

**Comment by sk22** [comment]
seriously tho: if you don't want to deal with custom fonts, you should override the system-wide font and use one specific font instead. but afaik, people sometimes like to use custom fonts to help with dyslexia, so i don't think overriding custom fonts would be a good option either, but what do i know. which fonts are the wrong and which are the right ones anyway? is there a list of supported fonts?

**Comment by githubgirly** [comment]
I'm dyslexic and use a custom font, so please do not override it 🤔

**Comment by sk22** [comment]
thanks for fixing!
