### ISSUE TITLE
[Feature request] "Load missing posts" should attempt to keep scroll position

### ISSUE THREAD

**Issue by ajhall** [mastodon/mastodon-android#154]
I often open the app and read from bottom to top to catch up with the latest posts. When I come across a "Load missing posts" banner, I tap it and it shifts the entire timeline down. This is what I would want if I was reading top-to-bottom, but when reading bottom-to-top it makes me lose my position and I have to hunt for where I left off.

![Screenshot_20220509-182529~2](https://user-images.githubusercontent.com/1380292/167620895-926191a8-8ff2-4148-9d9a-1019617458a4.png)

It would be nice if the scroll position shifted based on the position of the "load missing posts" banner. For example, maybe if the banner was in the top half of the screen when tapped it would keep the posts at the bottom visible after adding new ones, but if the banner was in the bottom half of the screen it would keep the posts at the top visible.

This relates to https://github.com/mastodon/mastodon-android/issues/147, but is a slightly different situation.

**Comment by kojid0** [comment]
I wonder why we have this "load missing posts" button anyway. I want all post to be shown in the first place (add a setting?). Loosing the position after clicking the button makes this request even more important

**Comment by movalex** [comment]
This feature request is year oldnow. Is anything done to fix that? If this wrong behavior (loads posts down) is considered to be unimportant by the users, how do they even use the app then? For me personally it is complete showstopper.

**Comment by garrett** [comment]
> it is complete showstopper

I'm in full agreement. This single bug right here is why I don't use the official app or one of its forks (Megalodon and Moshidon).

I'm usually using Tusky instead (which almost always does the right thing). Fedilab also works. No other clients but these two, shockingly.

> This feature request is year old now.

I think a lot of us have been very patient and jumping between apps, hoping this will finally be fixed.


> users, how do they even use the app then?

:shrug: I wonder the same thing.

When I load the app, I want to be at the same place in my stream and continue loading more. I never want to lose my place. 

As it is right now, trying to use the app is a bad experience for anyone who cares about reading their timeline (versus a random amount of recent posts from people and hashtags they follow). Unfortunately, this makes Mastodon look bad overall, as it's the default app and most people's first experience with Mastodon (and the fediverse) these days.

**Comment by Offerel** [comment]
I can't believe that this isn't fixed yet. It drive's me nuts, to loose the position in the timeline because of this.

**Comment by garrett** [comment]
@Offerel: Remembering your location when loading new posts works in Moshidon, which is a fork of the official app with additional features. https://github.com/LucasGGamerM/moshidon (It's available in Google Play and F-Droid.)

**Comment by Offerel** [comment]
It's this a special option. I have installed this app now, but could not find such a setting. Or is this enabled as default without a setting?

**Comment by ajhall** [comment]
Thanks for implementing this in v2.8.0, it works great!
