### ISSUE TITLE
“The spicy zone” label is hard to read in dark theme

### ISSUE THREAD

**Issue by dar5hak** [mastodon/mastodon-android#16]
The red text doesn't contrast well with the dark gray background.

![Screenshot_2022-04-15-02-54-45-28_98181b3e65f153deb38599aee3aee7e4.jpg](https://user-images.githubusercontent.com/8205055/163479759-3c6e6610-9de4-421b-b625-cbb3d87addc7.jpg)

**Comment by grishka** [comment]
Yes, the designer asked me to replace that color like a week ago but I forgot ><
