### ISSUE TITLE
Images not correctly sized/centered in notifications

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#164]
![Screenshot_20220515-140333240](https://user-images.githubusercontent.com/6217438/168471932-72851015-5e22-4a5f-95db-f8179baf52de.jpg)

**Comment by grishka** [comment]
Which version are you using? This was fixed ages ago.

**Comment by sk22** [comment]
the latest, master branch, commit [558adc6](https://github.com/mastodon/mastodon-android/commit/558adc6936637adc7fd8efeb69acb6cd932e4e58) - just tried it with the latest version on the play store as well: 1.1.1 (37)
i found the issue you were talking about (#43) and i figure it might be screen-specific? not sure if anyhow related, but i have my navigation bar disabled (using gesture control), so maybe something is calculated wrong because of that? i'll try to look into this as well

**Comment by grishka** [comment]
Yeah if you have a custom ROM and/or customized SystemUI, that might be the cause.

**Comment by sk22** [comment]
(So I'm slowly trying to understand how your code works so I can hopefully fix it myself or at least provide more info)

Interestingly, when setting the "outRect" left and right to 0, the image appears exactly centered:

![image](https://user-images.githubusercontent.com/6217438/168484963-225eeb22-ba5e-40cb-9812-b188e288743f.png)

```
if(insetLeft)
  outRect.left=0; //pad;
if(insetRight)
  outRect.right=0; //pad;
```

**Comment by sk22** [comment]
Looking at the screenshots in #43, I'm wondering: should images be 100% width in the timeline as well? (Because they aren't for me)

**Comment by grishka** [comment]
There's supposed to be padding for non-image display items.
![Снимок экрана 2022-05-15 в 20 10 25](https://user-images.githubusercontent.com/1478258/168485264-07c19c09-eb10-4a50-adda-8a580ffa40ef.png)
There are no mockups that show images, so I used the iOS app as a reference:
![IMG_0828](https://user-images.githubusercontent.com/1478258/168485403-1dd68353-4a9b-4c1e-80db-2ccdad0f6774.PNG)

**Comment by sk22** [comment]
hm. and non-notifications? is this displayed correctly? because if not i'm assuming there's something wrong with the way the image's width is calculated (given it is calculated, haven't looked into it yet)
![image](https://user-images.githubusercontent.com/6217438/168485563-16262e8f-71da-41ee-b345-29e5c1a8eaa4.png)

**Comment by grishka** [comment]
> should images be 100% width in the timeline as well?

They should but there's a limit of 400dp on the width.

**Comment by sk22** [comment]
hmm

**Comment by sk22** [comment]
can it be that the limit is always measured on the basis of the screen width instead of the container's width? would explain why it overflows in notifications (i think)

**Comment by grishka** [comment]
No, it's the width of the RecyclerView iirc.

Anyway, what did you do to your SystemUI exactly? You don't ever post non-cropped screenshots of the entire screen, and this doesn't make matters easier.

**Comment by sk22** [comment]
sorry about that, i don't really want to unnecessarily expose anyone's (including my own) identity on mastodon on github.

**Comment by sk22** [comment]
okay, so here's the two scenarios 
![image](https://user-images.githubusercontent.com/6217438/168485976-688533f8-29bd-4f75-b847-77dcc68be3ef.png)
![image](https://user-images.githubusercontent.com/6217438/168486084-21029ca2-d972-4463-8bf2-8ed3c0b4a3df.png)

and after "disabling" the max_width (by increasing it):

![image](https://user-images.githubusercontent.com/6217438/168486233-ce86a9b6-18fa-4f0c-b332-0440e32e8155.png)
![image](https://user-images.githubusercontent.com/6217438/168486200-4e5ee402-b7a2-44e4-9a52-e077249720ab.png)

i didn't really consciously do anything to my system ui, but i am using a custom rom (which i really should replace - it hasn't seen an update in ages) and i did set the display size to "small" (in the display settings - i think it's a vanilla android option?), but even with "default", i have 411 dp (which i can also manually adjust - i think that's just fine-tuning provided by the custom rom) and hence also this issue

**Comment by grishka** [comment]
![image](https://user-images.githubusercontent.com/1478258/168486683-b66d4b6a-dd46-402f-90a9-69fc87d36407.png)

Okay I found it. The image isn't centered if I rotate the screen so the width would exceed the max width.

**Comment by sk22** [comment]
i think it's this line which sets the ImageAttachmentFrameLayout's width to MAX_WIDTH, which shouldn't be the case for notifications, right?

https://github.com/mastodon/mastodon-android/blob/4fe646d71cb65aaee7ae9ede82701c99f0e65818/mastodon/src/main/java/org/joinmastodon/android/ui/views/ImageAttachmentFrameLayout.java#L39

**Comment by grishka** [comment]
Hm. `horizontalInset` is supposed to be the sum of those insets.

**Comment by sk22** [comment]
(i think you posted the wrong screenshot)

**Comment by sk22** [comment]
adding horizontalInset to the fallback-to-min-width case at least gets the image centered:

```java
// subtract horizontalInset in both cases
int w=Math.min(((View)getParent()).getMeasuredWidth(), V.dp(MAX_WIDTH))-horizontalInset;
```

![image](https://user-images.githubusercontent.com/6217438/168486915-40560dc3-441a-4a25-9dbc-d21c7258c7c7.png)

**Comment by grishka** [comment]
> (i think you posted the wrong screenshot, or at least i'm not exactly sure what you mean by it)

I selected the padding on the left, then moved the selection to the right. Yes, I use Photoshop for measuring things in images. It's surprisingly handy for that purpose ;)

**Comment by sk22** [comment]
> > (i think you posted the wrong screenshot, or at least i'm not exactly sure what you mean by it)
> 
> I selected the padding on the left, then moved the selection to the right. Yes, I use Photoshop for measuring things in images. It's surprisingly handy for that purpose ;)

ohh, i thought you accidentally had another window on top, but it was just the image from your post, oops. yeah, as you said,

> You don't ever post non-cropped screenshots of the entire screen, and this doesn't make matters easier.

**Comment by sk22** [comment]
and yes, same in this one https://user-images.githubusercontent.com/6217438/168485976-688533f8-29bd-4f75-b847-77dcc68be3ef.png:

![image](https://user-images.githubusercontent.com/6217438/168487204-25d9e816-e368-4580-9777-4dcf549fef05.png)

**Comment by sk22** [comment]
> and yes, same in this one https://user-images.githubusercontent.com/6217438/168485976-688533f8-29bd-4f75-b847-77dcc68be3ef.png:

wait, nevermind again, i think this was just because i took a screenshot from the scrcpy window. tried again by taking a real screenshot and it's only 1px off this time (which counts as centered, imo), sorry for the misinformation

**Comment by grishka** [comment]
Yeah that fixes it for me too. Thanks and excuse me for yet again being terrible with math.

**Comment by sk22** [comment]
> Yeah that fixes it for me too. Thanks and excuse me for yet again being terrible with math.

Yeah no, I totally get that. Thanks for fixing it!
