### ISSUE TITLE
Reconsider image max width

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#168]
I think, the 400 dp max width for images is too small (although I'm not sure it's 100% suited for determining whether images should be displayed full-width or not anyway, see #167 - maybe there could be some aspect ratio threshold instead?)

According to https://gs.statcounter.com/screen-resolution-stats/mobile/worldwide, at least 23 % (plus parts of whatever "Other" consists of) of mobile users have devices with a width of at least 400 dp,

> | Screen Resolution | Market Share Perc. (Apr 2021 - Apr 2022)
> | -- | --
> | Σ < 400 | 51.71
> | Σ > 400 | 23.44
> | Other | 24.83
> | 1st: 360x640 | 8.45
> | 2nd: 414x896 | 7.43
> ...

and according to the stats on https://worship.agency/mobile-screen-sizes-for-2021, widths around 410 dp are the most popular.

Since the app is supposed to display images full-width as a UI design feature, I think it'd be good to support that for more devices.
Now unfortunately, I'll have to suggest 425 dp to be the max width instead of 400, as it's the width value Chrome DevTools calls "Mobile L" width (and my device has 457 dp with the display size set to small, oh well).

**Comment by sk22** [comment]
> (although I'm not sure it's 100% suited for determining whether images should be displayed full-width or not anyway, see https://github.com/mastodon/mastodon-android/issues/167 - maybe there could be some aspect ratio threshold instead?)

Still hoping for a solution that gets my device - the Xiaomi Mi 6X - supported with the display size set to "small" as well, but I'm assuming that this would require rethinking the max width as a whole, or maybe depend on #167. Maybe the max width can still be increased as a first step, leaving the issue open for the future?

**Comment by Gargron** [comment]
You have created 4 GitHub issues about roughly the same feature today. Please consider consolidating your thoughts into one issue.

**Comment by sk22** [comment]
i partly agree; #167 kind of makes this issue redundant - closing this issue. the other ones, while similar, aren't really the same imo. anyway, sorry about the loads of issues regarding this!
