### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by cer4k4** [mastodon/mastodon-android#178]
Hi and how are you 🙂
Please check the emoji of mastadon because we don't have arch linux emoji or anything on mastadon.green server

**Comment by grishka** [comment]
What do you mean

**Comment by sk22** [comment]
> Hi and how are you slightly_smiling_face Please check the emoji of mastadon because we don't have arch linux emoji or anything on mastadon.green server

You'll have to contact mastodon.green's admin (who appears to be https://mastodon.green/@JohanEmpa) about adding custom emojis.

**Comment by cer4k4** [comment]
Hi , please check the picture and see the name of my friend and you can see
the arch linux logo between the character's
And when I asked from his how you can do this? do you found solution with
ASCII code or anything application ? he said no and
it's related to your server of mastadon if that server have emoji you can
display it on your name or post and he said it's not related to emojis of
your phone

**Comment by grishka** [comment]
You aren't making much sense.

**Comment by sk22** [comment]
I assume you meant to attach a screenshot in your reply, but I don't see any on GitHub.
Anyway, you probably see the Arch Linux custom emoji on a user profile who is on another server (not mastodon.green).
Custom emojis are server-specific. You can see everyone else's custom emojis, but you can only use the ones provided by the server you're registered on. (Looking at your server admin's profile, [:flan_cheer:](https://files.mastodon.green/custom_emojis/images/000/005/856/original/3cf8f2bdb0f321f7.png) seems to be an example.)
You can see your home server's custom emoji using the emoji button in the Mastodon app (not related to your phone's Unicode emoji) - these are the only ones you can use, unless your server admin adds more.

**Comment by cer4k4** [comment]
That's weird. 🙏🏻❤️

**Comment by sk22** [comment]
it is :/

**Comment by realpixelcode** [comment]
In order to see all custom emojis available on your Mastodon server, simply create a new toot and tap the smiley button.

If you don't see an emoji you'd like to use, it's not available on your server, meaning you'll have to ask the server's admin to add it.

![](https://user-images.githubusercontent.com/52963327/169657228-e1c057b3-4308-4984-8fd1-1d8163a8ae95.png)

**Comment by cer4k4** [comment]
Got it, thanks!

**Comment by cer4k4** [comment]
Ok nice to meet you and thanks for answering my question :)

**Comment by cer4k4** [comment]
Thank you!
