### ISSUE TITLE
Don't crop profile banners

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#181]
When uploading a profile banner in the web UI, Mastodon explicitly states that its resolution will be 1500×500px. That's exactly the size of my own profile banner. Yet, it is not fully visible in the Mastodon app – which is quite irritating and annoying.

![](https://user-images.githubusercontent.com/52963327/169657500-1c1a4bc2-7fa6-46c0-986e-6091583ae0d6.png)

**Comment by Gargron** [comment]
That's the recommended size, not a guarantee that it will always be displayed as 1500x500px in all circumstances
