### ISSUE TITLE
Inconsistent terms used throughout Mastodon

### ISSUE THREAD

**Issue by logicalwillow** [mastodon/mastodon-android#186]
The button to publish a new post
Web - "Toot!"
Android - "Publish"

Boosts
Web - "Boost"
Android - "Reblog"

Should these be more consistent?

**Comment by realpixelcode** [comment]
The terminology in the Mastodon mobile apps is intended. https://mastodon.social/@Gargron/108352419844292116

**Comment by Mattis142** [comment]
this doesnt explain the inconsistency between Boosts and Reblogs. In spanish it appears to even still be called a Retoot for some more inconsistency. To me Reblogging is a Tumblr term more than a Mastodon term and I would appreciate it if the app calls Boosts Boosts just like the web UI and the documentation does
