### ISSUE TITLE
Can't log in through mstdn.io instance

### ISSUE THREAD

**Issue by bphd** [mastodon/mastodon-android#187]

**Comment by bphd** [comment]
I really don't have much to add. I'm not an expert user, so I just use the app through Play Store without any debug mode, so no logs and there's not much description since this problem occurs literally at first opening just after clicking "Log In" and like, that's all

**Comment by grishka** [comment]
> I find mstdn.social but not mstdn.io, so I'm stuck

Oh it's this again... You have to type `mstdn.io` into the search field.

@Gargron I'm more and more inclined to think that the instance catalog *when logging in* solves nothing yet greatly confuses people just like in this case.

**Comment by bphd** [comment]
> > I find mstdn.social but not mstdn.io, so I'm stuck
> 
> Oh it's this again... You have to type `mstdn.io` into the search field.
> 
> @Gargron I'm more and more inclined to think that the instance catalog _when logging in_ solves nothing yet greatly confuses people just like in this case.

Oh okay, It would be more intuitive to complete the catalog, to make the "Next" button green when a valid instance is typed, or to change the whole process to incentivize the user to click "Enter" when typing into the search field. Like idk, create a custom search result like "Try 'search term' in browser...". It has to be worked on

**Comment by grishka** [comment]
My opinion is that the catalog is great for when you don't know which instance you want to join, so you could pick one. But it does more harm than good when logging in. You already know which instance your account is on, so why not just ask for that directly, without creating the impression that the app whitelists instances it supports?

**Comment by grishka** [comment]
That's what I'm saying
