### ISSUE TITLE
Unclear build instructions

### ISSUE THREAD

**Issue by dsrev** [mastodon/mastodon-android#19]
While I was trying to build the app myself, I learned that:

1. ~~Google no longer provides Build Tools `33.0.0-rc1`, but there is `33.0.0-rc2` as of today~~
2. Not covered https://github.com/grishka/appkit, which is required by the application. ~~I don't understand how to assemble *this* one~~

That's all I've noticed so far.

**Comment by grishka** [comment]
Appkit is on maven central. I didn't upload version 1.2.1 yet because I'm not yet sure if I'll need to fix anything else in it, and publishing something to maven central is kind of an irreversible process (you have to release it as a new version every time). You can clone the repo and put it into your local maven repository (`publishReleasePublicationToMavenLocal` gradle task) and then it'll work.

> Google no longer provides Build Tools 33.0.0-rc1, but there is 33.0.0-rc2 as of today

TIL

**Comment by grishka** [comment]
So actually, the `buildToolsVersion` line is no longer required and it'll just use whatever you have installed if it's not present, which is a good thing. And also TIL that the supported java features depend not on the build tools but on the gradle plugin. After updating _that_ to 7.1.3 I can now build the project with java 17 language level 🤔

**Comment by dsrev** [comment]
Good to know!

> ... You can clone the repo and put it into your local maven repository (`publishReleasePublicationToMavenLocal` gradle task) and then it'll work.

I'll check it out when I'm home, rn I'm a little busy

**Comment by dsrev** [comment]
The build succeeded! ...but I can't install the application I just built. :/

I did not see any problems or errors during the build (except for the lack of local.properties).

**Comment by grishka** [comment]
> ...but I can't install the application I just built. :/

What's the error? `adb install` returns it and it's also visible in logcat

**Comment by dsrev** [comment]
```
Performing Streamed Install
adb: failed to install .\mastodon-release-unsigned.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdXXXXXXXXXX.tmp/base.apk: Failed to collect certificates from /data/app/vmdXXXXXXXXXX.tmp/base.apk: Attempt to get length of null array]
```

Did I forget to specify something?

**Comment by grishka** [comment]
I don't know how you built it, but you didn't sign it

**Comment by dsrev** [comment]
Oh... right. Everything is okay now.

I'll leave this issue open, since the main problem remains unchanged

**Comment by grishka** [comment]
> since the main problem remains unchanged

Which problem?

**Comment by dsrev** [comment]
> Which problem?

"Not covered [grishka/appkit](https://github.com/grishka/appkit)", as I mentioned earlier. Not sure if it installs on its own with the latest changes tbh

**Comment by grishka** [comment]
What the heck does "not covered" even mean? You aren't making any sense.

**Comment by dsrev** [comment]
*... пожалуй, объясню на своём родном языке.*

Я хотел донести, что сборка твоего Appkit не была описана в README, пока ты мне не объяснил какую команду лучше использовать для этого. До появления оф.клиента Mastodon я никогда самостоятельно не собирал приложения для своего смартфона, из-за чего я не могу знать, Gradle устанавливает пакеты с Maven Central или нет 🤔

**Comment by grishka** [comment]
Устанавливает. Maven вообще считается стандартом для зависимостей в джаве, и все другие системы сборки его поддерживают. Вот версия 1.2.1: https://search.maven.org/artifact/me.grishka.appkit/appkit/1.2.1/aar

Если хочешь что-нибудь поменять в самом appkit, можно использовать `publishReleasePublicationToMavenLocal`, локальный репозиторий по идее должен иметь приоритет. 
![image](https://user-images.githubusercontent.com/1478258/164153843-10cd78d6-9400-4898-9c5f-d19f83499a16.png)

Я всё-таки закрою ишью, потому что кажется, что инцидент исчерпан.
