### ISSUE TITLE
Switching languages doesn't immediately translate all strings

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#190]
1. Set system language to language A.
2. Open Mastodon. Everything is translated into A.
3. Without closing Mastodon, switch the system language to B.
4. Go back to Mastodon. Everything is translated into B – except for those greyish labels in the notifications tab.

German to English:

![](https://user-images.githubusercontent.com/52963327/170480000-122456ff-c322-411a-9311-72d8b9bf2e49.png)

English to German: 

![](https://user-images.githubusercontent.com/52963327/170480219-597de096-6dbf-4494-8a3b-f03808f04382.png)

(Those labels are translated correctly when re-opening Mastodon after switching the language.)

**Comment by grishka** [comment]
Yeah right because ordinary users change their system language 10 times a day...
