### ISSUE TITLE
Feature: Set language of post

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#199]
Just like in the Web UI, it should be possible to explicitly set the language for a post that one creates.

**Comment by SeidChr** [comment]
Why is this not in the app??

**Comment by mariotaku** [comment]
Can you assign this to me if it needs help? I think can implement this one. @grishka

**Comment by grishka** [comment]
No, we don't need help right now. As this feature changes the UI, it needs to be designed by our UI/UX team.

**Comment by mariotaku** [comment]
I see. This is a very useful feature. And I'll be looking forward to this one!

**Comment by SeidChr** [comment]
Uninstalled the app now. Using PWA. No notifications, but i can set the language :D

**Comment by realpixelcode** [comment]
This feature has been implemented meanwhile. Just tap the 🌐 icon in the draft window.
