### ISSUE TITLE
Quotes appear as HTML-encoded in notifications

### ISSUE THREAD

**Issue by dar5hak** [mastodon/mastodon-android#20]
If a notification of a toot contains quotes, they appear as HTML-encoded.

![IMG_20220415_123421.jpg](https://user-images.githubusercontent.com/8205055/163535846-8f5cad15-be60-4fcf-b363-496740c2310c.jpg)

The same toot looks fine inside the app.

![IMG_20220415_123225.jpg](https://user-images.githubusercontent.com/8205055/163535398-541565c3-bce9-4af8-9bd5-e89f5ab20914.jpg)

**Comment by grishka** [comment]
It was fixed on the server side but I'm not sure whether it was released yet.

**Comment by grishka** [comment]
mastodon/mastodon#18071
