### ISSUE TITLE
Edit profile: “Done” button not aligned

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#201]
The “done” button should be aligned with the input field for the display name.

![](https://user-images.githubusercontent.com/52963327/174434684-5afe23ad-e947-4afa-88a9-e34ed69e59ce.png)

**Comment by grishka** [comment]
It shouldn't.

![image](https://user-images.githubusercontent.com/1478258/174470907-9679a577-da50-4db7-ab1e-f64f355ae5ca.png)

**Comment by Gargron** [comment]
To clarify what grishka said, the design has been given to us as-is by the designer, it is not an implementation mistake or oversight.
