### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by Pukimaa** [mastodon/mastodon-android#203]
I got the fairly new Android 12. One thing I just miss is Material You in Mastodon. I think it would be super cool as it gives more consistency throughout the phone. And if you really want the classic Mastodon Design maybe just add a third option so it becomes:
- Light
- Dark
- Material You/Custom

I think everyone would love to see that!

**Comment by pc00per** [comment]
+1.
The current design is already polished. The only thing missing is the color palettes of material you design...

**Comment by Mr-Bajs** [comment]
Nothing wrong with the darker theme that is now. But Material You would be much appriciated, it gives a much cleaner feel having your apps in the same theme, such as Material You allows.

**Comment by bbaster** [comment]
Material You was just officially confirmed:

https://github.com/mastodon/mastodon-android/issues/565#issuecomment-1593562348

**Comment by grishka** [comment]
What do you mean confirmed? I was building it in `m3_redesign` branch for months in plain sight.

**Comment by Pukimaa** [comment]
It's implemented by now
