### ISSUE TITLE
Login on Custom Mastodon Instance

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mastodon/mastodon-android#207]
We have users with instances of Mastodon in SNET (Street Network) that do not have domains accessible from the internet.

Is there a possibility to add the option of a custom instance?

**Comment by grishka** [comment]
What do you mean by "custom instance"?

**Comment by AnonymousWebHacker** [comment]
> What do you mean by "custom instance"?

When you open the app, there is a search box where you search for the instance to which you belong or want to register.

Said list of instances are public and are in the list of federated instances in the network.

When I refer to custom, I mean being able to enter an instance that is not on the list, for example.

https://mastodon.azeroth  <-  It is an instance that is not public on the internet, it is only within a SNET

**Comment by grishka** [comment]
Ah so it's **yet again** the case of the existence of that list confusing people. We really need to do something about it. It's a huge enormous UX catastrophe.

You can enter an arbitrary domain into that field and either hit enter or wait for it to appear in the list. It should at least try `GET /api/v1/instance` if your DNS resolves *.azeroth domains. Except I'm not sure what's the HTTPS certificate situation is going to be — I'm doubtful any public CAs would issue a certificate for an .azeroth domain. Is it self-signed? The app probably won't trust it then.

**Comment by AnonymousWebHacker** [comment]
It is a valid domain, the sites are signed by original CAs, (not self-signed).  I thought to close the problem, but I put the domain and it did not allow me to accept

![WhatsApp Image 2022-06-28 at 10 5hfgh2 35 PM](https://user-images.githubusercontent.com/43164089/176341231-bda27b68-ac86-4ba5-837c-d39923e7def7.jpeg)
![WhatsApp Image 2022-06-28 at 10 5hfg2 43 PM](https://user-images.githubusercontent.com/43164089/176341235-0d8fd72c-1f0e-4e44-85fd-1d9ca41d97f4.jpeg)
![WhatsApp Image 2022-06-28 at 10 5f2 43 PM](https://user-images.githubusercontent.com/43164089/176341240-45ebd834-7ffe-4744-a69a-88e7e9288ff6.jpeg)
![WhatsApp Image 2022-06-28 at 10 52 43 PM](https://user-images.githubusercontent.com/43164089/176341247-f549b69f-724e-46ca-8792-37070564c761.jpeg)

![Captura de pantalla de 2022-06-28 22-46-49](https://user-images.githubusercontent.com/43164089/176340334-b754e699-b7b1-4d81-bd13-da127dfb56c7.png)

**Comment by AbrilJara** [comment]
Hi, i also recently created an instance in limited federation mode and when i hit the go button on the keyboard in my phone (because de next button in the app screen it's dissbaled) it show the following error:

```
Error

[MY DOMAIN] doesn't seems to be an instance of Mastodon.

This method requires an authenticated user.
```

**Comment by AnonymousWebHacker** [comment]
> Hi, i also recently created an instance in limited federation mode and when i hit the go button on the keyboard in my phone (because de next button in the app screen it's dissbaled) it show the following error:
> 
> ```
> Error
> 
> [MY DOMAIN] doesn't seems to be an instance of Mastodon.
> 
> This method requires an authenticated user.
> ```

Can you enter well, via browser from cell phone or PC? The problem is only with the official Mastodon app?

**Comment by AbrilJara** [comment]
Correct, i can access the app without problems from my browsers but when I tried from de app y show's me that error.

I tried deleting the variable for limited federation and reloading the instance and i was able to access form the app. Although, it still didn't appear on the list of instances in the app.

I wan't to calrify aso, my app wasn't limited in federation but also on IPs, so you can only access from certain addresses to the app.

**Comment by AnonymousWebHacker** [comment]
Main problem, it was solved with an update of the app.

Steps, write the address of my non-federated instance, wait for the API to communicate with instance detection, and access it
