### ISSUE TITLE
Missing Delete and Redraft feature

### ISSUE THREAD

**Issue by imto1** [mastodon/mastodon-android#21]
I can't see Delete and Redraft feature on Mastodon android. It's very useful feature for editing previously posted toots. It will be good to add this feature to your android app.

**Comment by grishka** [comment]
Huh?
![screenshot](https://user-images.githubusercontent.com/1478258/163547236-fbcf5bea-9c46-48d8-beb4-1ba02814b92b.png)

**Comment by imto1** [comment]
![IMG_20220415_131303_582.jpg](https://user-images.githubusercontent.com/43239919/163548378-84c23416-1a6c-469a-989c-6053a477b344.jpg)

**Comment by carlosala** [comment]
Since v3.5 of Mastodon there's an option to properly edit toots, but it's currently disabled in the webapp and native apps until next version, to give time to instances to update. Probably this option is not going to make any sense after this change (in my opinion, obviously)

**Comment by sk22** [comment]
possible implementation: https://github.com/mastodon/mastodon-android/compare/master...sk22:feature/delete-redraft - not ideal, i guess, but it works!
(now available in my fork's latest release: https://github.com/sk22/mastodon-android-fork/releases)

**Comment by Gargron** [comment]
Yes, since we already added edits to the API, it makes no sense to work on delete & redraft in the apps.
