### ISSUE TITLE
Missing bookmarks

### ISSUE THREAD

**Issue by imto1** [mastodon/mastodon-android#22]
Cannot bookmark posts and also unable to see bookmarks. Please add this feature to Mastodon android.
Thanks.

**Comment by imto1** [comment]
![IMG_20220415_131259_636.jpg](https://user-images.githubusercontent.com/43239919/163548477-23d9b2fb-0583-4fe6-aeb2-d644a60b0e11.jpg)
![IMG_20220415_131256_189.jpg](https://user-images.githubusercontent.com/43239919/163548507-b5ea2efd-d2a2-4013-80ae-852429081249.jpg)

**Comment by sk22** [comment]
implemented this in my fork's [feature/bookmark](https://github.com/sk22/mastodon-android-fork/tree/feature/bookmarks) branch: https://github.com/mastodon/mastodon-android/compare/master...sk22:feature/bookmarks

**Comment by da-bu** [comment]
Hey, any updates on this one? I'm new to Mastodon and really like the app. This is the one feature I'm missing the most. 🙏

**Comment by grishka** [comment]
Github issues are mostly for bug reports. Features that require new UI, as well as any other UI changes, are decided upon centrally and implemented in both iOS and Android apps more or less at the same time. This is also the reason why I don't merge pull requests that change the UI or add to it.

**Comment by da-bu** [comment]
Thank you for the clarification! What's the best place / way to make UI suggestions?

**Comment by SamStephens** [comment]
@grishka 

> Github issues are mostly for bug reports. Features that require new UI, as well as any other UI changes, are decided upon centrally and implemented in both iOS and Android apps more or less at the same time. This is also the reason why I don't merge pull requests that change the UI or add to it.

So what you're saying is that third party contributors to this repository should consider themselves confined to bug fixes, as UI changes are managed centrally?

As per https://github.com/mastodon/mastodon-android/issues/271 can you please add a contributions policy? I'd really like to be able to contribute to this application, but I'm not going to put the effort in without knowing you'll accept my changes.

**Comment by 3ter** [comment]
> Github issues are mostly for bug reports. Features that require new UI, as well as any other UI changes, are decided upon centrally and implemented in both iOS and Android apps more or less at the same time. This is also the reason why I don't merge pull requests that change the UI or add to it.

I don't understand the concept here. The android version is on `v1.1.3` vs iOS being on `v1.4.5` (3 feature versions higher, assuming semver). On iOS the respective issue came up only recently while this one has been around for half a year.
https://github.com/mastodon/mastodon-ios/issues/479

**Comment by SamStephens** [comment]
@grishka someone volunteered their labour for you, and you rejected it because of contribution policies you have never clarified.

It is six months later, and the application is still lacking this very foundational feature. Even though if you actually collaborated with the community, I'm guessing the pull request could easily have been adapted to be what you want.

I've been using the official Android application even though every post I ever sees says that other applications are better, because I want to contribute and improve it. I'm just about to give up that idea because the lack of communication here does not give me confidence that it's a good use of my time.

My take is if you're not going to engage with the community, if this is the communication model you think is appropriate, you'd be doing the Mastodon ecosystem a favour if you shut this application down in favour of focusing on the web application, and let third parties continue to build better phone applications.

**Comment by 3ter** [comment]
> > Github issues are mostly for bug reports. Features that require new UI, as well as any other UI changes, are decided upon centrally and implemented in both iOS and Android apps more or less at the same time. This is also the reason why I don't merge pull requests that change the UI or add to it.
> 
> I don't understand the concept here. The android version is on `v1.1.3` vs iOS being on `v1.4.5` (3 feature versions higher, assuming semver). On iOS the respective issue came up only recently while this one has been around for half a year. [mastodon/mastodon-ios#479](https://github.com/mastodon/mastodon-ios/issues/479)

And the feature has apparently been added to the iOS version in the meantime:
https://github.com/mastodon/mastodon-ios/issues/479#issuecomment-1321009862

**Comment by grishka** [comment]
> someone volunteered their labour for you, and you rejected it because of contribution policies you have never clarified.

But they did it without first asking whether the results of that labor would be useful for me.

> It is six months later, and the application is still lacking this very foundational feature.

This app is for new users. There are more advanced apps for more advanced users.

> Even though if you actually collaborated with the community, I'm guessing the pull request could easily have been adapted to be what you want.

Except the bookmarks feature is not currently planned and I don't know if or when it will be. Or if it will be, it might end up looking and/or working another way entirely.

> My take is if you're not going to engage with the community

I'll say it again: this is not a community project. It is a **centrally managed** open-source project. Its direction and feature set is not decided by the community. The community is still welcome to make suggestions, report bugs and create pull requests that fix them.

> you'd be doing the Mastodon ecosystem a favour if you shut this application down in favour of focusing on the web application, and let third parties continue to build better phone applications.

"Better" is subjective. This app is for new users. The minimal feature set is purposeful.

**Comment by grishka** [comment]
And yes you're right that there needs to be a contribution policy.

**Comment by 3ter** [comment]
> > someone volunteered their labour for you, and you rejected it because of contribution policies you have never clarified.
> 
> But they did it without first asking whether the results of that labor would be useful for me.
> 
> > It is six months later, and the application is still lacking this very foundational feature.
> 
> This app is for new users. There are more advanced apps for more advanced users.
> 
> > Even though if you actually collaborated with the community, I'm guessing the pull request could easily have been adapted to be what you want.
> 
> Except the bookmarks feature is not currently planned and I don't know if or when it will be. Or if it will be, it might end up looking and/or working another way entirely.
> 
> > My take is if you're not going to engage with the community
> 
> I'll say it again: this is not a community project. It is a **centrally managed** open-source project. Its direction and feature set is not decided by the community. The community is still welcome to make suggestions, report bugs and create pull requests that fix them.
> 
> > you'd be doing the Mastodon ecosystem a favour if you shut this application down in favour of focusing on the web application, and let third parties continue to build better phone applications.
> 
> "Better" is subjective. This app is for new users. The minimal feature set is purposeful.

Thank you for the clarification!

That means "back to Tusky" for me personally, but for others the minimal starting point into Mastodon might just be the right thing 👍.

**Comment by SamStephens** [comment]
@grishka 

> This app is for new users. There are more advanced apps for more advanced users.

Where is this position made clear? In comments of Github issues is not really useful. I just had a look at the Play Store listing. The listing says nothing about that.

This is the Mastodon official Android application. It's reasonable to expect it to provide the full Mastodon experience. If it's purposefully not going to, make that clear in the Play Store listing. Make it clear in the README.md of this repository. Make it clear in the official blog post that readme links to.

Maybe even name the application to reflect that. Mastodon Basic or something. As it stands, people are going to install this application expecting the full experience, and then be really confused as people in their timelines tell them to do things like make their replies Unlisted that the application does not and apparently will not support.

> Except the bookmarks feature is not currently planned and I don't know if or when it will be. Or if it will be, it might end up looking and/or working another way entirely.

But you've already told us that "Features that require new UI, as well as any other UI changes, are decided upon centrally and implemented in both iOS and Android apps more or less at the same time.", and as per https://github.com/mastodon/mastodon-ios/issues/479#issuecomment-1321009862 this feature has been implemented in iOS.

Communication is the key here. If it had been made clear the mobile applications are deliberately a subset of the full set of functionality, I would have known it wasn't the application for me.

**Comment by grishka** [comment]
I asked Eugen and I will implement bookmarks the same way they work on iOS.

**Comment by SamStephens** [comment]
Thanks @grishka . As far as the rest of my comments go, it'd be appreciated if you did follow up on making it clearer this application only supports a subset of full Mastodon functionality, and if a contribution policy was put together.
