### ISSUE TITLE
Set max-height for posts

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#220]
Long NSFW text posts are kinda confusing to the user since they are basically huge walls of solid colour. They should be truncated and given a “Read more” button.

https://user-images.githubusercontent.com/52963327/179295766-6b98c527-c2a1-457f-9143-bb0c120f0835.mp4

**Comment by sk22** [comment]
duplicate of #166, and yeah, saw the same post and had the same problem :/

**Comment by realpixelcode** [comment]
> duplicate of #166, and yeah, saw the same post and had the same problem :/

Oh right, doesn't see that
