### ISSUE TITLE
Feature: Cancel media download

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#231]
When downloading a video, for example, you might notice too late that it's really long and therefore really big in file size – maybe too big to be downloaded via cellular data, for example. Thus, there should be an option to cancel the download, ideally as a button in the notification.

**Comment by grishka** [comment]
This is not controllable by the app because it uses the system download manager.

**Comment by grishka** [comment]
Have you tried expanding the notification?..

![Screenshot_20220730-173932.png](https://user-images.githubusercontent.com/1478258/181919364-0f970f06-b83c-4d41-94ef-d7e44a96226f.png)

**Comment by realpixelcode** [comment]
Ah, thanks for the hint!
