### ISSUE TITLE
Poll: negative amount of seconds left

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#238]
I just opened Mastodon and came across a post with a poll that were created 8 hours ago. The poll's timer said `-9800 seconds left`. Though, when trying to vote it said “poll is already over”.

I don't know why this was, I didn't do anything unusual; I just opened the app and scrolled down.

![](https://user-images.githubusercontent.com/52963327/184108365-e724d218-b45e-425b-9727-a80660f30481.png)

![](https://user-images.githubusercontent.com/52963327/184108391-b6d4e58b-3ab5-4c0c-a138-a6350ebb6f06.png)

**Comment by grishka** [comment]
This is me being dumb
