### ISSUE TITLE
error: invalid source release: 17

### ISSUE THREAD

**Issue by unhumanalien** [mastodon/mastodon-android#241]
I have downloaded Mastodon-Android v1.1.3, opened it in Android Studio. However, when I tried to build the project a error appeared:

   Cause: error: invalid source release: 17

![image](https://user-images.githubusercontent.com/111471056/185270864-3bf0cb4e-774b-4da8-b60b-c465ed94e2f6.png)

Using: JDK 18.0.1.1
Android Studio 2121.2.1 Patch 2

PS: script ./gradlew assembleRelease works perfectly.

**Comment by grishka** [comment]
Do you also have JDK 17 selected here?

![image](https://user-images.githubusercontent.com/1478258/185273467-1318b7ef-6402-4593-bc6b-b8ead9ec1d96.png)

**Comment by unhumanalien** [comment]
Now it worked!
Thank a lot!
