### ISSUE TITLE
character count does not include content warning character lengh

### ISSUE THREAD

**Issue by negatendo** [mastodon/mastodon-android#249]
Mastodon [counts the text in a content warning towards the overall 500 character limit](https://github.com/mastodon/mastodon/issues/9792).

The character count in the lower-right corner of the android app when publishing a new post does not account for this, resulting in a possible validation error (Text character limit of 500 exceed) if you try and post a 500 character post with a content warning, despite the displayed character count in the lower-right saying you're ok (see attached screenshot).

The character count in the lower-right could include the character count for the content warning text to fix this.

![Screenshot_20220828-111000~2](https://user-images.githubusercontent.com/35718/187086352-fc448652-52de-49d7-b3a3-339df66ebc5d.png)

**Comment by grishka** [comment]
TIL CW is included in that limit
