### ISSUE TITLE
This app has not posted any notifications

### ISSUE THREAD

**Issue by TheJoYo** [mastodon/mastodon-android#262]
Version 1.1.3
Android 13

No notifications are ever posted from the app to android.
I tested this with `mastodon.social`.

![fae2a06b7efcd67c](https://user-images.githubusercontent.com/57574308/197896760-6680098c-9ff9-423a-8ee3-6b19c568341a.png)

**Comment by grishka** [comment]
Do you have Google services?

**Comment by TheJoYo** [comment]
yes, i installed from the Play Store.

**Comment by grishka** [comment]
Do you have notifications enabled in the app settings? Those are synced with the server.

**Comment by TheJoYo** [comment]
yes, I tested this with multiple accounts on different instances which all have notifications enabled.

**Comment by TheJoYo** [comment]
![signal-2022-10-25-190111](https://user-images.githubusercontent.com/57574308/197897941-3ec4b262-cbfa-45c2-8a35-a934f15c1f8f.png)

**Comment by grishka** [comment]
Hmmm. Are there any other apps in which notifications similarly don't work? What is your device? Are you using a stock or a custom ROM?

**Comment by TheJoYo** [comment]
No, Tusky is notifying as expected.
This is on stock Android on a Pixel 6a.

**Comment by grishka** [comment]
That's even stranger then. But then also I just tested and I'm not receiving any notifications either. Only thing I can think of is an issue with the WebPush -> FCM server. cc @Gargron

**Comment by grishka** [comment]
Okay, one more thing I missed. Android 13 introduced a runtime permission for notifications. There is **supposed** to be a compatibility mode for apps targeting older Android versions, which Mastodon is, but you know how Google does quality control on their products lately... Adding `android.permission.POST_NOTIFICATIONS` to the manifest fixed it nevertheless and made the permission dialog appear on a subsequent app launch. I had "all Mastodon notifications" off and greyed out before I did that.
