### ISSUE TITLE
Translate button

### ISSUE THREAD

**Issue by Mattis142** [mastodon/mastodon-android#267]
Please implement the translate button from the website into the app as well

**Comment by schmitzel76** [comment]
As I have a following coming from different countries, this is surely needed. I don't want to spam then in a language they don't know with content that might not be relevamt to th. Now I have to post from the website to do that.

**Comment by vahetildian** [comment]
Hello, which website are you talking about? The server i'm using doesn't have such a translate button

**Comment by oriolpiera** [comment]
It has to be a translate button below every toot not in your language, that show a translation just there without go outside the app.

**Comment by vahetildian** [comment]
I don't have that option in my browser, maybe it depends on the server? Please show what the author is referring to looks like. It could help with coherence of design

**Comment by MKCOOL142** [comment]
> I don't have that option in my browser, maybe it depends on the server? Please show what the author is referring to looks like. It could help with coherence of design

I am talking about mastodon.social as I thought this app was mostly aimed at mastodon.social users but now thinking about that it doesn't exactly make sense to assume that, regardless that's the instance I am talking about

**Comment by stephen304** [comment]
Fwiw, this is what it looks like on mastodon.social web. Would love to see this functionality in the app

![Screenshot_20221118_220901](https://user-images.githubusercontent.com/981915/202831398-390acb56-9f0a-4a0b-9c16-42898a1d5526.png)
![Screenshot_20221118_220907](https://user-images.githubusercontent.com/981915/202831397-db4ef389-e93e-4285-b47d-1a1aeb77ed23.png)

**Comment by nicobatty** [comment]
Yes, this is pretty important especially for European users since we tend to toot in multiple languages (english and native usually).

The problem is that the texts are getting the "translate" button but that is a minor problem compared to the language filtering feature that can be enabled at the account level which would result in the toot not showing at all for some people (I had to edit some of my messages to because of that).

I'm basically forced to use either the web app or a different client to send my toots which is kind of a bummer.

**Comment by MKCOOL142** [comment]
> Yes, this is pretty important especially for European users since we tend to toot in multiple languages (english and native usually).
> 
> The problem is that the texts are getting the "translate" button but that is a minor problem compared to the language filtering feature that can be enabled at the account level which would result in the toot not showing at all for some people (I had to edit some of my messages to because of that).
> 
> I'm basically forced to use either the web app or a different client to send my toots which is kind of a bummer.

I'm a bit confused on what you mean? Like are you talking about the language selector to select what language your post is in?

**Comment by nicobatty** [comment]
@MKCOOL142 I actually though this was about language selector support but it is about translating the content with DeepL... My bad... :sweat_smile:

**Comment by MKCOOL142** [comment]
> @MKCOOL142 I actually though this was about language selector support but it is about translating the content with DeepL... My bad... 😅

Idk if you know Abt Megalodon? It's based on the mastodon app and actually has the language selector and deepL translation feature and more additional features, you should give it a try honestly

**Comment by nicobatty** [comment]
> > @MKCOOL142 I actually though this was about language selector support but it is about translating the content with DeepL... My bad... sweat_smile
> 
> Idk if you know Abt Megalodon? It's based on the mastodon app and actually has the language selector and deepL translation feature and more additional features, you should give it a try honestly

I actually found out about it a few minutes after my message. It is a great fork, it does have all the things I actually wanted!

**Comment by MKCOOL142** [comment]
> > > @MKCOOL142 I actually though this was about language selector support but it is about translating the content with DeepL... My bad... sweat_smile
> > 
> > 
> > Idk if you know Abt Megalodon? It's based on the mastodon app and actually has the language selector and deepL translation feature and more additional features, you should give it a try honestly
> 
> I actually found out about it a few minutes after my message. It is a great fork, it does have all the things I actually wanted!

You can also try moshidon, it's based on Megalodon with some minor tweaks
