### ISSUE TITLE
Following notifications include HTML entity codes

### ISSUE THREAD

**Issue by SamStephens** [mastodon/mastodon-android#272]
When I receive notifications of new users following me, I see HTML entities that are not present in the source profile, as per this example screenshot.

![image](https://user-images.githubusercontent.com/1034921/198956770-90b5b3a1-a729-47ca-afc0-f9d61c007a3f.png)

Source text includes `Sid James' mind in Jenny Agutter's body`, the notification shows this as `Sid James&#39; mind in Jenny Agutter&#39;s body`, with the apostrophes rendered as HTML entities.

Mastodon 1.1.3, Google Pixel 6, Android 13, Build number TP1A.221005.002

**Comment by davidmhewitt** [comment]
As mentioned in https://github.com/mastodon/mastodon-android/issues/235#issuecomment-1300851287, it seems that the notification title and body text are set/sent by the Mastodon server. So any bugs regarding these would need to be raised against mastodon itself.

**Comment by SamStephens** [comment]
Resolving in favour of https://github.com/mastodon/mastodon/issues/19718
