### ISSUE TITLE
Mastodon Android 1.1.3 crashes when attempting to view followers

### ISSUE THREAD

**Issue by vaelfonia** [mastodon/mastodon-android#274]
The title is essentially what I'm experiencing. Mastodon Android will crash and send me back to the home screen every time I attempt to view my list of followers. I have cleared the cache, I have logged out & back in, and reinstalled the app, to no avail.

**How to reproduce**
1. Open Mastodon Android.
2. Go to profile.
3. Attempt to view follower list

Expected behaviour: Able to view list of followers
Actual behaviour: App crashes to home screen / launcher

This does not occur with the list of people I am following, just the list of people who are following me.

**App Version:** Mastodon Android 1.1.3 (Play Store)
**Android Version:** 13.0 (October 2022 patch), build number TP1A.221005.003
**Device:** Google Pixel 6a

**Comment by davidmhewitt** [comment]
I can't reproduce this with my follower list.

Are you willing to share your mastodon handle so I can see if I can reproduce the crash browsing your followers list to see if it's something caused by a specific follower of yours?

Otherwise, are you able to provide debug logs?

**Comment by vaelfonia** [comment]
Sure thing, it's @vaelfonia@mastodon.social.
It occurs even when everything else works normally enough, under peak load it won't even crash, it would just give me a timeout.

As for logs, I'm unsure as to how to do so, but if you would like them I'll try my best to figure it out.

**Comment by vaelfonia** [comment]
I got this stack trace from the send feedback prompt after one of the crashes. It seems to be something to do with an emoji?

[stacktrace.txt](https://github.com/mastodon/mastodon-android/files/9910576/stacktrace.txt)

If any more logs are needed, please let me know.

**Comment by davidmhewitt** [comment]
That's great, thank you!

I've found the issue and will submit a fix today, hopefully to be included in the next version of the app.

For reference, in case I don't get around to fixing it:

The issue is with accounts that use the same custom emoji in their name and bio. Here's an excerpt of the accounts JSON for one such account:

```
"last_status_at": "2022-11-01",
"emojis": [
{
"shortcode": "Chaos",
"url": "https://files.mastodon.social/cache/custom_emojis/images/000/415/455/original/7439b002f3e8500b.png",
"static_url": "https://files.mastodon.social/cache/custom_emojis/images/000/415/455/static/7439b002f3e8500b.png",
"visible_in_picker": true
},
...
{
"shortcode": "Chaos",
"url": "https://files.mastodon.social/cache/custom_emojis/images/000/415/455/original/7439b002f3e8500b.png",
"static_url": "https://files.mastodon.social/cache/custom_emojis/images/000/415/455/static/7439b002f3e8500b.png",
"visible_in_picker": true
},
```

The inclusion of this emoji in the JSON twice results in the following code throwing an exception on the duplicate `shortcode`:

https://github.com/mastodon/mastodon-android/blob/0ee494bcfc9854e718456321cdc14277e9cb88e0/mastodon/src/main/java/org/joinmastodon/android/ui/text/HtmlParser.java#L132

**Comment by vaelfonia** [comment]
Huh, weird. Glad I could help!

Thanks for the explanation ^-^
Have a nice day!
