### ISSUE TITLE
Feature: Option for natural reading order of timeline

### ISSUE THREAD

**Issue by politas** [mastodon/mastodon-android#281]
Facebook, Twitter, they all got us accustomed to this bizarre practice of reading timelines backwards, so newer posts are above older ones.

Could we please have an option to have the newer entries in the timeline at the bottom, so we can read without constantly scrolling in opposite directions?

**Comment by avidseeker** [comment]
Related to https://github.com/mastodon/mastodon-android/issues/70

**Comment by Sam-Oak** [comment]
Pachli, another Mastodon client, [added this feature](https://github.com/pachli/pachli-android/pull/867).
