### ISSUE TITLE
Duplicate @Subscribe for onStatusCreated event handlers in HomeTimelineFragment?

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#283]
Not a bug per se, but I'm opening this issue because I'm very confused and I'm not sure if or why the code is correct.

`HomeTimelineFragment`, which inherits from `StatusListFragment`, has a method that subscribes to the `StatusCreatedEvent`.

```java
class HomeTimelineFragment extends StatusListFragment {
	@Subscribe // ← should this be here? onStatusCreated is called by StatusListFragment anyway
	public void onStatusCreated(StatusCreatedEvent ev){
		prependItems(Collections.singletonList(ev.status), true);
	}
}
```

But so does the `StatusListFragment` itself. It subscribes to said event and then calls the object's (in this case, an instance of `HomeTimelineFragment`) `onStatusCreated` method.

```java
abstract class StatusListFragment {
	protected void onStatusCreated(StatusCreatedEvent ev){}

	@Subscribe
	public void onStatusCreated(StatusCreatedEvent ev){
		StatusListFragment.this.onStatusCreated(ev); // ← this calls HomeTimelineFragment's onStatusCreated
	}
}
```

<details>
<summary>This seems to not cause any problems: <code>StatusListFragment</code>'s <code>StatusCreatedEvent</code> handler calls <code>HomeTimelineFragment</code>'s <code>onStatusCreated</code> method. The called <code>prependItems</code> method was only invoked once, as the breakpoint inside only fired once. (click to reveal screenshot)</summary>

![image](https://user-images.githubusercontent.com/6217438/199617442-a5613c33-3a78-4efa-a0b9-abfd88ab0088.png)
</details>

<details>
<summary>However, in my fork, the method is called twice – once for each subscription; actually, as I would expect seeing the two <code>@Subscribe</code> annotations (click to reveal screenshots)</summary>

First, it's called from the `StatusListFragment`'s subscription:
![image](https://user-images.githubusercontent.com/6217438/199617595-59921d40-6308-47d6-9fb4-e25a67968b2c.png)

Then, directly through `HomeTimelineFragment`'s subscription:
![image](https://user-images.githubusercontent.com/6217438/199617626-aedca116-7a93-47cc-a009-0798e9411bec.png)
</details>

Removing the `@Subscribe` annotation in `HomeTimelineFragment`'s event handler fixes the issue in my fork (due to the event firing twice, newly published posts were prepended twice as well), but I don't understand why the issue doesn't occur upstream. Is the second subscription there on purpose?

**Comment by grishka** [comment]
It needed to be there because Otto (the event bus) does not traverse the class hierarchy. But this looks like I forgot to remove it because I moved these event listeners to `EventListener` inner class for this exact reason 🤔
