### ISSUE TITLE
New language requests on Crowdin

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon-android#295]
Please look at the discussions on Crowdin

https://crowdin.com/project/mastodon-for-android/discussions

There are multiple requests waiting there - I made mine 6 months ago.

**Comment by grishka** [comment]
Added:

- Scottish Gaelic
- Indonesian
- Dutch
- Sinhala

I didn't add Kurdish because Android doesn't support setting it as a system language (on devices I have), so translating the app into it would be pointless.
