### ISSUE TITLE
Java error when tapping “Load more...”

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#298]
Today, I came across a “Load more...” button in my timeline but got a Java error when tapping it:

![](https://user-images.githubusercontent.com/52963327/200122970-7aa5cd9d-7d1c-41d4-b84f-43edc28af9a0.png)

**Comment by grishka** [comment]
Who has this many followers?..

**Comment by lewismcgeary** [comment]
I did some digging after seeing a similar error elsewhere in the app, in my case it seemed to be https://mcd.dk/@rune which claims 7.99B followers, 7.99B following and a join date at the end of the Epoch...

**Comment by Pectojin** [comment]
> a join date at the end of the Epoch...
Hmm, it was supposed to be after the end. I'll have to fix that.

**Comment by Pectojin** [comment]
You can replicate the setup with these queries:
```
UPDATE account_stats SET following_count = 7985735748 WHERE id = 2;
UPDATE account_stats SET followers_count = 7985735748 WHERE id = 2;
```

(after finding the correct stats id from `select * from account_stats where account_id = 1;`)

**Comment by grishka** [comment]
This one's even better lol
![screenshot](https://user-images.githubusercontent.com/1478258/200150834-edbd6190-fcd1-41d9-8291-9b2b14204f91.png)

**Comment by Pectojin** [comment]
haha, no clue how that happened. I set it to 1 million a little while ago, but I never set it negatively.

**Comment by grishka** [comment]
It's clear it's an overflow

ugh
![image](https://user-images.githubusercontent.com/1478258/200150895-ceebb502-6169-483d-a704-4b2851243495.png)

**Comment by grishka** [comment]
(what's next, I'll have to make it a BigInteger?)

**Comment by sk22** [comment]
I briefly thought about just using it as a string, but the same issue would apply to the number of likes and reposts… rune said this:

> I actually don't know if they use the number for anything. A string would probably be safe, although weird when people start (ab)using it as a string.
> The best option might just be some guard clauses that drop the value and show some default.
