### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by Doomsdayrs** [mastodon/mastodon-android#3]
The android ecosystem is moving towards using Kotlin.

Using Java will inhibit the future maintainability of the application.

Consider converting to Kotlin overtime.

**Comment by grishka** [comment]
> Consider converting to Kotlin overtime.

To solve what?

**Comment by Doomsdayrs** [comment]
Java is not the language for Android anymore. Its easier to develop new features in Kotlin.

Kotlin has less overhead and is more maintainable.

**Comment by grishka** [comment]
> Java is not the language for Android anymore.

Because Google says so? The same Google who can never make up its mind and settle for something that gets the job done? The same Google that comes out with ever more, ever more nonsensical abstractions on top of Android that solve all those problems no one has ever had?

> Its easier to develop new features in Kotlin.

For me it's easier to develop new features in a language that I've been using for more than a decade, that doesn't try to outsmart me, that I don't have to fight, and that isn't a moving target.

> Kotlin has less overhead and is more maintainable.

This is subjective. Are you trying to tell me that there are developers who know Kotlin but don't know Java? Shame on them then.

**Comment by Doomsdayrs** [comment]
> Because Google says so? The same Google who can never make up its mind and settle for something that gets the job done? The same Google that comes out with ever more, ever more nonsensical abstractions on top of Android that solve all those problems no one has ever had?

While you might have some previous dislike for Googles actions in certain departments. And that you have something you are comfortable with. I don't see how that relates to the very large and growing Kotlin developer scene.

> For me it's easier to develop new features in a language that I've been using for more than a decade, that doesn't try to outsmart me, that I don't have to fight, and that isn't a moving target.

I can understand that Java is something you are comfortable with, but is it the best choice going forward when Google is trying to move onto Kotlin, and new developers in the now and future will be using Kotlin more and more.

> This is subjective. Are you trying to tell me that there are developers who know Kotlin but don't know Java? Shame on them then.

Nearly all computer programmers are taught Java, but that does not mean they all *like* coding in Java. Neither does it mean they have proficiency in coding in Java, nor does it mean they even have the capability to properly digest Java codebases.

Please do consider that Kotlin is easier to write, it requires less to type and is simpler on the eyes. While Java has its history, Kotlin has versatility that you don't have in Java.

**Comment by Gargron** [comment]
I’m sorry but I don’t see the point in allowing this discussion to continue. Our programming language choice is ours to make and there’s nothing wrong with using Java for Android apps at the moment.
