### ISSUE TITLE
Mixed error and search state

### ISSUE THREAD

**Issue by opatry** [mastodon/mastodon-android#300]
I had an error while searching, having a retry button state. Then starting another search left error state visible while displaying search results.

![Screenshot_20221105-203837.png](https://user-images.githubusercontent.com/362710/200137979-bf311384-ef0a-45b2-9cb5-131eb5fb7e77.png)

![Screenshot_20221105-203433.png](https://user-images.githubusercontent.com/362710/200137933-fc982523-0b20-46df-a9bb-449d1560f6ac.png)

**Comment by grishka** [comment]
I thought this was impossible 🤔

**Comment by opatry** [comment]
Maybe linked to poor connectivity.

**Comment by grishka** [comment]
> Maybe linked to poor connectivity.

No, I meant that the two states displaying together was impossible. Of course errors themselves are always possible in any networking operations.
