### ISSUE TITLE
[BUG] Signing in on instance with `LOCAL_DOMAIN != WEB_DOMAIN` doesn't work

### ISSUE THREAD

**Issue by zemlanin** [mastodon/mastodon-android#312]
When searching for Mastodon server with different `LOCAL_DOMAIN` and `WEB_DOMAIN` values, it:

1. shows `LOCAL_DOMAIN` in search results (unlike iOS, see screenshots. maybe it's iOS bug)
2. does `/api` and `/oauth` requests to `LOCAL_DOMAIN` instead of `WEB_DOMAIN`, resulting in 404/405s

So, for example, users of instance with `LOCAL_DOMAIN=example.com` and `WEB_DOMAIN=mastodon.example.com` won't be able to sign in

Android:
<img width="500" alt="Android Screenshot" src="https://user-images.githubusercontent.com/711514/200313461-d8f4a164-2826-4ba6-9836-9dedca8e7f6c.png">

iOS:
<img width="500" alt="iOS Screenshot" src="https://user-images.githubusercontent.com/711514/200313654-cd1895d0-6454-42e1-8ddc-27b4f7da9065.PNG">

**Comment by grishka** [comment]
Hmm. How does it even find it at all like in your screenshots when https://devua.club/api/v1/instance returns 404? It only works for me if I enter `mastodon.devua.club`.

**Comment by zemlanin** [comment]
`https://devua.club/.well-known/webfinger` and/or `https://devua.club/.well-known/host-meta`?

**Comment by grishka** [comment]
Yes but this app doesn't use these.

**Comment by grishka** [comment]
No, but I suppose I do have to support this redirect thing for the sake of consistency since the iOS app does
![image](https://user-images.githubusercontent.com/1478258/200329930-8522d355-97bc-4609-8e60-3846fa0d9fa3.png)

**Comment by zemlanin** [comment]
(iOS PR https://github.com/mastodon/mastodon-ios/pull/211)
