### ISSUE TITLE
Bug: wrong behavior inserting text on replies

### ISSUE THREAD

**Issue by X-static** [mastodon/mastodon-android#313]
Hi,

I have this weird bug when inserting text on a reply or a new post from a profile page. I think I can assume it's when one or more handles are on the text input already.

Issue:
When I type the first word and double press the spacebar to automatically insert punctuation (common keyboard function), the next word I type replace the previous one.

I've recorded my screen to better illustrate the issue: [here](https://drive.google.com/file/d/1bTXFVcuyQcgpczYM0mgALiDF58fiQ6fK).

I also noticed other minor keyboard automatic function that are not recognized inside the app textbox and work fine on other apps.

Thank you.

App version: 1.1.3
Android 12. Poco F3
Keyboard: Gboard

**Comment by grishka** [comment]
Okay, if you wish. But be warned that fixes to these kinds of bugs are sometimes not as straightforward as it might seem.

**Comment by soumdatta81** [comment]
I will be careful. Thanks for assigning.

**Comment by soumdatta81** [comment]
Struggling a bit. Any idea how to do this?

**Comment by grishka** [comment]
Hm. Maybe somehow related to MediaAcceptingInputConnection 🤔

**Comment by grishka** [comment]
@soumdatta81 do you still want to fix this, or do I do it?

**Comment by soumdatta81** [comment]
Removing the function makes it work but apart from that, I think everything looks normal. Am I missing something else?

**Comment by grishka** [comment]
But that function is necessary for the image/gif insertion from the keyboard to work, so you can't remove it.

Anyway, I think I'll try to debug it myself. This might require digging into AOSP sources too 🙈
Thank you for your help!
