### ISSUE TITLE
Can't log into  (new) server instance

### ISSUE THREAD

**Issue by akhepcat** [mastodon/mastodon-android#318]
Just stood up a mastodon server, and have zero problems reaching it from a web browser;  got friends registering just fine.

Trying to connect using the latest available android build from the Play store just pops up the most unuseful error:

`Error
  mastodon.akhepcat.com doesn't appear to be a Mastodon instance

500`

And, yet, it's working fine over IPv4 and IPv6 for multiple browser users.

**Comment by grishka** [comment]
But https://mastodon.akhepcat.com/api/v1/instance does, in fact, return a server error

**Comment by akhepcat** [comment]
hrm.   something is trying to connect to port 5003, but of course, i don't know what that is - i guess it's time to find out what this instance didn't start up when it got installed...

**Comment by akhepcat** [comment]
mastodon-streaming is failing.  Okay, i'll close this since it's obviously not a mobile-app issue.  thanks for the heads up with the api test

**Comment by nfriedly** [comment]
I ran into the same issue today, but the resolution was different in my case: `/api/v1/instance` didn't show any errors, but I did notice a websocket URL. My Mastodon server is set up behind Nginx Proxy Manager, and I hadn't turned on websockets support. After I flipped that setting, the app was able to connect to the server.

Hopefully that helps someone.

**Comment by grishka** [comment]
Except the app doesn't use websockets, so it must be a coincidence.

**Comment by nfriedly** [comment]
Huh. I think that's the only thing I changed. 🤷‍♂️
