### ISSUE TITLE
"This list is empty" is not localised

### ISSUE THREAD

**Issue by julroy67** [mastodon/mastodon-android#319]
Currently on each screen with a list using appkit's emptyViewLayout the "This list is empty" will be showing in English.
The string is not available to translate because it is getting pulled from appkit's [strings.xml](https://github.com/grishka/appkit/blob/master/appkit/src/main/res/values/strings.xml) file.

Should the translations be added to appkit's repo or is there a way to add translations for this string in this repo?

**Comment by grishka** [comment]
I'll add it to Mastodon's strings.xml, all those strings are meant to be customizable, I just forgot to do that 🙈

**Comment by grishka** [comment]
I'll add it to Mastodon's strings.xml, all those strings are meant to be customizable, I just forgot to do that 🙈

**Comment by julroy67** [comment]
Nice, thank you!
