### ISSUE TITLE
Setting to ignore Content Warnings

### ISSUE THREAD

**Issue by devinmatte** [mastodon/mastodon-android#323]
Content Warnings are good, especially good that they're on by default when present for a post.

However, some users, especially myself, might be okay with not having to tap to see a post with a content warning and would prefer a setting they could toggle on that shows the post by default regardless of the CW

Potentially even a more advanced setting where "ignore content warnings on posts/warnings that don't contain the following strings"

This could be the same as the desktop setting:
<img width="386" alt="Screen Shot 2022-11-08 at 3 30 21 PM" src="https://user-images.githubusercontent.com/9310513/200669232-da900098-badc-40e8-9dbb-46db8bebe953.png">
Just available in the app

**Comment by thomaslule** [comment]
+1

There is a "Show content warnings" setting that we can untick, but it is not very usable. Instead of automatically expanding the CWs, it totally hides them. Sometimes there is useful info in the CW text. And sometimes we would like the CWs to be expanded by default but still be able to fold them.

Having the same "Always expand" setting as in the default web UI would be much better.

**Comment by grishka** [comment]
This already exists as of 2.x (Material 3 redesign)
![Screenshot_20230913-182735](https://github.com/mastodon/mastodon-android/assets/1478258/d7a8f5a3-2cb7-4553-8efa-29e3306092f1)

**Comment by thomaslule** [comment]
@grishka about the comment I left just above, should we open another issue or could you re-open this one? Not showing CWs is not the same as always expanding them.

**Comment by grishka** [comment]
This setting does always expand them, it doesn't hide them completely.

**Comment by thomaslule** [comment]
I may have been unclear, let me illustrate the problem:

This is when the "show CW" setting is activated, I can see the CW and expand it.

![Sans titre](https://github.com/mastodon/mastodon-android/assets/8104612/983d2b40-16bd-4843-adb2-187eaa89c06e)
![Sans titre](https://github.com/mastodon/mastodon-android/assets/8104612/60f79412-1358-434c-adf2-5a29eb78c6b8)

And this is when I untick the setting:

![Sans titre](https://github.com/mastodon/mastodon-android/assets/8104612/7657b418-dc86-452e-9708-62223826df8c)

The text of the CW is lost, in this case I cannot know that the person is talking about covid.

**Comment by thomaslule** [comment]
From what I understand, this issue is the same as https://github.com/mastodon/mastodon-android/issues/87
