### ISSUE TITLE
literal

### ISSUE THREAD

**Issue by ucdc05** [mastodon/mastodon-android#324]
error: unclosed string literal
			db.execSQL("""
			             ^

**Comment by grishka** [comment]
Are you sure you're using JDK 17 or newer?

**Comment by ucdc05** [comment]
newer

**Comment by grishka** [comment]
Can you write more than one word at a time?

**Comment by ucdc05** [comment]
i can. and also how can i be part of this

**Comment by ucdc05** [comment]
Fixed.  Thank you

**Comment by grishka** [comment]
This is a user error since JDK 17 is a requirement for building the app and it is specified as such in the readme.
