### ISSUE TITLE
Support 2FA security keys

### ISSUE THREAD

**Issue by brad2014** [mastodon/mastodon-android#326]
I added a 2FA security key to my profile.  I now cannot log in on the app.

I get the message "The browser does not support security keys".

Enhancement request:  Support security keys (FIDO, Solokeys, Yubikey, Webauthn, etc)

**Comment by grishka** [comment]
Login uses your default browser. The app has no control over what happens after it launches the oauth flow.

**Comment by brad2014** [comment]
You're right!~  Thanks.
I was using the DuckDuckGo browser, and when I changed the Android default browser to Chrome, it worked.
