### ISSUE TITLE
Function request: Push notifications

### ISSUE THREAD

**Issue by Minecodes** [mastodon/mastodon-android#329]
When  the accounts get a notification, it should send a push notification (like in the browser version). This would be handy as you don't want to get every notification as a browser or email notification, but also want a way to get them through the app.

**Comment by grishka** [comment]
There already are push notifications. As they work via Google's FCM, they require Google services or a replacement like microG.

**Comment by Minecodes** [comment]
I have that, but I didn't send me any over the app.

**Comment by Minecodes** [comment]
> There already are push notifications. As they work via Google's FCM, they require Google services or a replacement like microG.

I have that, but I didn't send me any over the app.

**Comment by Minecodes** [comment]
Thanks for informing 😉
