### ISSUE TITLE
[Bug] "Search" section empty

### ISSUE THREAD

**Issue by alan-ford** [mastodon/mastodon-android#33]
Device: Amazon Fire 7 with Android 7.1.2

The "Search" section empties after visiting one of the proposed accounts and I have to restart the app.

**Comment by grishka** [comment]
Could you please describe the steps to reproduce this?

**Comment by alan-ford** [comment]
@grishka 

1. Open "Search" tab;
2. Go to any account;
3. Return to the Search tab.

**Comment by grishka** [comment]
Can't reproduce this, but I did find a crash, so that's something lol

**Comment by grishka** [comment]
I believe this was due to Android being too smart and focusing the search field automatically (#95), I fixed that today.
