### ISSUE TITLE
TLD's longer than 3 letters don't allow sign-in

### ISSUE THREAD

**Issue by thunderblood101** [mastodon/mastodon-android#34]
My instance is weirder.earth, which doesn't work at the moment because when entering my domain, the app cuts the last 2 characters off of "earth". Screenshots included, version 1.0.
![Screenshot_20220418-214534](https://user-images.githubusercontent.com/26202905/163904249-3daf4f39-3982-4a74-b58c-d0c3ea7dfc80.png)
![Screenshot_20220418-214542](https://user-images.githubusercontent.com/26202905/163904268-9444437e-bdbb-4d12-9805-7a43e39fa09c.png)

**Comment by grishka** [comment]
It's not that, it's me being stupid again and not updating the search query from the field immediately when you press enter
