### ISSUE TITLE
infosec.exchange doesn't exist on list to choose 

### ISSUE THREAD

**Issue by olekstomek** [mastodon/mastodon-android#345]
I'm trying to login to my created account https://infosec.exchange/ but I don't see this server on list in mobile app (Android). 

Is it somehow a [separate instance](https://github.com/glitch-soc/mastodon)? I don't see infosec.exchange in the [server list](https://joinmastodon.org/pl/servers).
At first I thougth that **I**nf**O**se**C**.exchange is ioc.exchange but no. 
By the way, then on ioc I entered my email to reset my password and I got information that the email exists and a password reset link was sent (but the email never arrived). Is it ok that there is information that the email will be sent even though I was not on the server instance where my account is?

**Comment by sk22** [comment]
just type in "infosec.exchange" and press enter!

**Comment by olekstomek** [comment]
Okey, it really works! 😆
This server will be searched only after entering the full name, after typing eg `infosec.exchang` (without the last letter) it is still not listed.  However, it is not so obvious after all.
