### ISSUE TITLE
Package invalid

### ISSUE THREAD

**Issue by HJKK2** [mastodon/mastodon-android#352]
I think the title explains the issue.
[mastodon-release-unsigned.zip](https://github.com/mastodon/mastodon-android/files/9996603/mastodon-release-unsigned.zip)

**Comment by grishka** [comment]
Uh no, the title doesn't explain anything? Nothing about this issue makes sense actually.

**Comment by grishka** [comment]
It does say "unsigned" in the name — you need to sign an apk before you install it. If you use the launch button in Android Studio, then it would be signed for you automatically with a debug certificate, the one in `~/.android/debug.keystore`.
