### ISSUE TITLE
Camel case for hastags

### ISSUE THREAD

**Issue by atdotslashdot** [mastodon/mastodon-android#355]
It would be great if the autocomplete suggestions for hashtags had the CamelCase version of the tag. I understand this is the better option for screen readers but I expect most people will use what comes up as the suggestion.

**Comment by sk22** [comment]
thing is, it will actually give you CamelCased hashtags as suggestions if the server knows them as such. that is, if your instance's moderators set it to be this way (they can approve/reject hashtags to be shown in the trends and change casing). so i don't think the app can do much here

![Screenshot_2022-11-13-14-55-28-644-edit_org joinmastodon android sk](https://user-images.githubusercontent.com/6217438/201525506-017506fc-bbc4-4e5d-8815-bcc77d5dcbb0.jpg)

**Comment by atdotslashdot** [comment]
Thanks, is there a recommendation in the docs or are useful link I can
forward to an instance moderator?

**Comment by sk22** [comment]
> Thanks, is there a recommendation in the docs or are useful link I can forward to an instance moderator?

not that i knew of, but your instance's moderators can go to `your.instance.social/admin/trends/tags` and moderate hashtags from there - but only the ones that are currently trending. i don't think there's a way of editing other hashtags, unfortunately

**Comment by atdotslashdot** [comment]
Thanks
