### ISSUE TITLE
UI: No filled variant of repost button

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#363]
![IMG_20221116_083428](https://user-images.githubusercontent.com/6217438/202116246-00a28043-4633-4380-a1ca-77651008076b.jpg)
![IMG_20221116_083358](https://user-images.githubusercontent.com/6217438/202116251-f3123972-2171-4bcf-882d-7cbada689f47.jpg)

The selected variant isn't "filled" (the filled variant would be slightly more bold), while the selected fav button is displayed in its filled variant - not sure if this is intentional?

**Comment by sk22** [comment]
proposed change:

![Screenshot_2022-11-20-17-11-13-194-edit_org joinmastodon android](https://user-images.githubusercontent.com/6217438/202912968-6a73bc80-77ac-4cb7-8e31-5993d1602342.jpg)
![Screenshot_2022-11-20-17-11-27-633-edit_org joinmastodon android](https://user-images.githubusercontent.com/6217438/202912972-f1a5b1db-3c8c-464d-b4d8-108d18486306.jpg)

**Comment by grishka** [comment]
Ok it is actually the filled icon in in the mockups, so I'll fix this
<img width="383" alt="image" src="https://user-images.githubusercontent.com/1478258/202913152-8ea5374c-8ddd-4251-953b-0d3dab899b35.png">

**Comment by sk22** [comment]
can open a PR if you want?

**Comment by grishka** [comment]
I can do it myself
