### ISSUE TITLE
Crash when viewing someone's profile

### ISSUE THREAD

**Issue by CorruptComputer** [mastodon/mastodon-android#365]
Not every profile causes the crash, however this one produces it every time: `@hazelnot@sunbeam.city`

I can't figure out what is causing it, there doesn't seem to be anything odd about that profile compared to others. 

Sorry I can't copy/paste from the android crash log, but here is a screenshot of the stack trace if it helps.

![Screenshot_2022-11-16-09-42-19-38_ef2e086c15df938868bbfbb5823b0ab0.jpg](https://user-images.githubusercontent.com/5573038/202226361-e350789b-8340-4c40-bce7-ecbd51976259.jpg)

**Comment by tonytamsf** [comment]
FYI: on Android 13 with the `master` version of the app, I'm able to view the profile.

**Comment by CorruptComputer** [comment]
Checked today and the crash did not occur on first load of the profile. I had to scroll down a bit before it crashed. I think it may actually be a specific post loading which is causing it.

Ill do some testing tonight and see if I can figure out some more info about it.

**Comment by grishka** [comment]
It's already fixed in #275
