### ISSUE TITLE
Add "Unlisted" option for toots.

### ISSUE THREAD

**Issue by Xabellee** [mastodon/mastodon-android#37]
Web Mastodon supports that feature, but in this app I cannot use it. In this app I can only use _public_, _Followers only_, _Only people I mention_.

**Comment by moertel** [comment]
Some other threads (e.g. on the iOS app) talk about this being a deliberate design decision. Before anyone goes in to invest time in a PR, can the maintainers please clarify whether this is true?

**Comment by Cassolotl** [comment]
This is now essential in light of *https://github.com/mastodon/mastodon/pull/26344*, which will make all public posts from "discoverable" accounts searchable.
