### ISSUE TITLE
Signing up on closed server still prompts user data

### ISSUE THREAD

**Issue by b90g** [mastodon/mastodon-android#377]
When selecting a Server that isnt open for signing up, the user gets still promted to enter his desired account name etc and on submitting gets a `forbidden` message.

ideally there wouldnt be a data prompt, or at least a better errormessage that the server isnt open for registration

**Comment by grishka** [comment]
Ok, so the iOS app does do this check.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/1478258/202894905-4c4db1ea-1258-49fc-8682-74481e37fc86.png">
