### ISSUE TITLE
Option to open mastodon links in app (Is that doable)?

### ISSUE THREAD

**Issue by Andre601** [mastodon/mastodon-android#380]
From what I understand can apps register domains to be handled by them, so that when you open a certain domain it gets handled by the app (i.e. GitHub.com URLs would open the GitHub App if installed).

With Mastodon, there is obviously the issue that there isn't just one single URL you can open to see post, but several ones...
Tho, is there any possibility to add this functionality to the Android app (Open links to posts, profiles, etc in the App rather than browser) itself? Based on my limited knowledge would I assume no, but you never know.

If that is possible would it most certainly be a useful thing to have, as you don't have to login to your account or switch it in browser...

**Comment by BluePixel4k** [comment]
Similar to #110

**Comment by mattwelke** [comment]
It sounds like https://github.com/mastodon/mastodon-android/issues/110 described the UX issue and this issue describes a probably technical reason for the issue to occur.

This does make sense to me. I vaguely remember from doing Android development a few years ago that it had ways for you to make your app open certain kinds of links. With Mastodon, it makes sense that the links are HTTP[S], and you'd have to by the domain, not the protocol. And it can be any domain. But how about, as a quick win, the app automatically adds the domain of the server you log the app into as a domain recognized as Mastodon, and those links would be opened in the app? Maybe it could even go further than that. It could add the domain of the server you log the app into, and also the domains of the servers that server federates with.

I think those are some pretty safe assumptions for the app to make (based on my admittedly limited Mastodon/ActivityPub knowledge so far).

**Comment by kolAflash** [comment]
@Andre601
Was this meant about how links open IN THE MASTODON APP, or FROM ANOTHER APP?

&nbsp;

If it's from another app:

This is kind of an issue for all self / on premise hosted software. Mastodon, Nextcloud, PeerTube, ...  
Nevertheless some apps solved it at least partially by registering for any domain `*`. Sometimes narrowed down by certains strings behind the slash `/`. On some OS versions the user needs to enable this manually in the OS, but at least it's possible.

At the Fediverse app does this for Mastodon.  
https://framagit.org/tom79/fedilab

The NextCloud app does this for NextCloud instances.  
(altough there are minor problems)  
https://github.com/nextcloud/android/issues/1069

For PeerTube there's a proposal of a URL redirection service. Altough I'm not sure if I like that idea.  
https://github.com/Chocobozzz/PeerTube/issues/1540

**Comment by Andre601** [comment]
Please move discussion to #110.
The issue is closed for a reason.
