### ISSUE TITLE
Request: lists for hashtags

### ISSUE THREAD

**Issue by TheFern2** [mastodon/mastodon-android#382]
I don't know if this would need to be implemented in the server, but I would like to have lists of hashtags. I will like to work on this if it sounds like a good idea.

**Comment by realpixelcode** [comment]
Possibly similar to #31

**Comment by TheFern2** [comment]
@realpixelcode Yes, closing. Btw how do you set up hashtag timelines? I don't see that anywhere on tusky android.

**Comment by realpixelcode** [comment]
> @realpixelcode Yes, closing. Btw how do you set up hashtag timelines? I don't see that anywhere on tusky android.

Go to

Profile settings ➡️ Tabs ➡️ Plus button ➡️ Hashtags
