### ISSUE TITLE
Make URLs clickable in the Ground Rules signup page

### ISSUE THREAD

**Issue by charliemikels** [mastodon/mastodon-android#389]
My instance has a link to our full code of conduct in one of our ground rules. However it is not clickable, nor selectable in the app, so actually getting to the CoC page is a little tedious. Links starting with https:// should be clickable like in a regular Mastodon post.

**Comment by grishka** [comment]
Can I have a link to your instance so I could test against it?

**Comment by charliemikels** [comment]
toot.cafe

Here's a screenshot of that it looks like for me right now:
![Screenshot_20221121-020820.png](https://user-images.githubusercontent.com/20339866/202986701-1b823161-75b2-4cf9-b43f-bbe962cc0588.png)

Note: my instance is currently closed for registration, but you should still be able to see it.

**Comment by Gargron** [comment]
FWIW that's not how the "server rules" feature was intended to be used.
