### ISSUE TITLE
Talkback and screen reader related labels

### ISSUE THREAD

**Issue by davidbtc2009** [mastodon/mastodon-android#39]
- Android 11
- Mastodon v1.0

The app so far works well however the following items need to be labeled correctly for those of us using screen readers

In settings screen
- the back arrow reads as "unlabeled" instead of "back"
- under the visual appearance headings there are radio buttons for automatic, light, and dark. But talkback does not say which is selected. What it should say for example is automatic selected, light, dark if auto is selected or automatic, light, dark selected if dark mode is selected. Or automatic, light selected, dark if light mode is selected

In the compose window
- the back button reads as "unlabeled" instead of "back"

In the search screen
- the magnifying glass icon at top left reads as "unlabeled". If this button actually causes a search it needs to be labeled " search" if its just a visual thing that has no function it either needs to be put into the edit box element or make talkback skip that element completely
- when you type in the search box the "X" icon to clear the search reads as "unlabeled" instead of "clear search" for example.

In the My profile tab and other users profiles
- the header image is a button that reads as "unlabeled" but does nothing when clicked. If this is not a button its element type may need changing and the label should be "header image" or similar
- the profile picture acts just like the header image just mentioned. If it is not a button its element type should be changed and the label should read something like "profile image"

**Comment by grishka** [comment]
The back buttons are part of the system-provided toolbar component and they do have "navigate up button" as description for me 🤔

The other points are valid and I'll fix these, thanks.

**Comment by davidbtc2009** [comment]
@grishka Weird. My mastodon app is v1.0 (27) and talkback is v12.1 and those buttons do not read as "navigate up" for me.

**Comment by grishka** [comment]
Apparently it depends on the android version, anyway, I fixed it
