### ISSUE TITLE
Update documentation to make it clear the apps are a simplified experience

### ISSUE THREAD

**Issue by SamStephens** [mastodon/mastodon-android#396]
Quoting from discussion on https://github.com/mastodon/mastodon-android/issues/22#issuecomment-1321075092

> This app is for new users. There are more advanced apps for more advanced users.
> [...]
> This app is for new users. The minimal feature set is purposeful.

Please make this clear in the Play Store listing. Please make it clear in the README.md of this repository. Please consider renaming this application to something like Mastodon Basic/Mastodon Express/Mastodon Light to make it clear this is deliberately not the full experience. At the moment, I regularly see posts in my feed warning people away from the official applications, because people go to these applications expecting the full experience, and are disappointed when the applications do not provide that.

Also, it might be worth creating documentation of which features you are deliberately leaving out of scope for the app. Looking at the issues, I'm already seeing a bunch of requests for features I suspect you've deliberately omitted from the application. It will probably save you a lot of time to just be able to point people to an existing Out Of Scope document and close the issue.

**Comment by SamStephens** [comment]
Also, is the iOS application considered to be a simplified experience? It sounds like it from the statement

> Features that require new UI, as well as any other UI changes, are decided upon centrally and implemented in both iOS and Android apps more or less at the same time. - https://github.com/mastodon/mastodon-android/issues/22#issuecomment-1304762602

Because if so, a version of this issue should probably be opened there too.

**Comment by grishka** [comment]
This was addressed by #400

**Comment by SamStephens** [comment]
@grishka please consider updating the Store Listing too. It's great you've made this clear to contributors, but the general public is the most important audience here.

The second review I see on https://play.google.com/store/apps/details?id=org.joinmastodon.android&gl=US&pli=1 is a one star review saying:

> Not great. There are no dm's. I cannot find half of the stuff the desk top features on the app. It's not very intuitive to navigate. The update supposedly allowed to follow hashtags, alas. I didn't get it I guess, because even after updating twice, I still don't have the feature... Will update if anything changes. So far, not a fan. The browser version is not letting me log in now. Fantastic.

You'd get less reviews like this one if you made the lack of feature parity clear to the general public.
