### ISSUE TITLE
Doesn't show that a post has been edited

### ISSUE THREAD

**Issue by da5nsy** [mastodon/mastodon-android#397]
Example post: https://fosstodon.org/@da5nsy/109379903975971775

App:
![Screenshot_20221121-175821](https://user-images.githubusercontent.com/3739866/203175110-e097031d-0648-47a3-bd3d-9fbbca418acb.png)

Firefox for Android:
![Screenshot_20221121-175835](https://user-images.githubusercontent.com/3739866/203175112-38f8de75-f7a7-4389-a0f6-2fe6f3d638dc.png)

**Comment by grishka** [comment]
The production version doesn't know anything about editing, but the upcoming release will, and all the relevant functionality is already implemented.
