### ISSUE TITLE
Polls have negative time left when loaded before it ended

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#417]
![Screenshot_2022-11-24-14-26-11-257-edit_org joinmastodon android sk](https://user-images.githubusercontent.com/6217438/203795625-14b55d63-2e39-4ab2-92ae-b1141ea0e11b.jpg)

Not sure what is loaded when and when things are being rendered, but I've seen this as a result a couple of times.

**Comment by realpixelcode** [comment]
Similar to #238
