### ISSUE TITLE
Spoiler/CW of long posts can be off-screen

### ISSUE THREAD

**Issue by waldyrious** [mastodon/mastodon-android#419]
The position of the content warning text is vertically centered in the post, which for long posts may place it "below the fold" when seeing the top of the post, and "above the fold" when the bottom of the post is visible.

Screenshots:

| top of post | end of post |
| ----------- | ----------- |
| <img src="https://user-images.githubusercontent.com/478237/203857606-4d8d6e0e-8c43-4eca-9d82-60b610b6c44b.png" width="400"/> | <img src="https://user-images.githubusercontent.com/478237/203857614-6484f6e6-94df-48f8-8ac5-f0f901b39cb8.png" width="400"/> |

Ideally the text should have a "sticky" positioning, so that it can still be in the vertical center of the post when that doesn't place it off-screen, but would otherwise remain visible (stuck to the top or the bottom of the visible area).

**Comment by sk22** [comment]
possible duplicate of #166

**Comment by waldyrious** [comment]
Indeed @sk22, thanks for pointing it out. I'll close this as a duplicate.
