### ISSUE TITLE
Make view from timeline back

### ISSUE THREAD

**Issue by chen244** [mastodon/mastodon-android#42]
I like this , because it makes me feel I am not alone on then earth. Every time I view the post from different from the timeline, I can feel they are all alive, not only me. Every time, every second, I can meet new friend, maybe he is in Japan, having dinner, or In French.

Now the feature of viewing from timeline is not in mastondon-android. I like the hot trending, then I can know what people are talking now. But I feel lonely when use your app. I find out that it is because I cannot always read a new post, cannot always know who may be will be my friend, what he is doing ,worring. So I need this feature.

**Comment by chen244** [comment]
I don't mind mastondon being a second twitter, but although it is twitter, twitter also have the Option to view from the timeline.

**Comment by Gargron** [comment]
When you follow people you will get their new posts in your home feed.

**Comment by chen244** [comment]
> When you follow people you will get their new posts in your home feed.

But without timeline ,how can I follow interesting people? And what about the chance for the post of a nobody be seen by another ?

**Comment by realpixelcode** [comment]
> twitter also have the Option to view from the timeline.

What exactly do you mean by “view from timeline”?

**Comment by chen244** [comment]
> > twitter also have the Option to view from the timeline.
> 
> What exactly do you mean by “view from timeline”?

Sorry , I may got a mistake. The timeline of twitter is only for who your follow..I don't use twitter frequently. My friend has show the feature of twitter, then I mistake twitter has this feature

**Comment by Gargron** [comment]
> But without timeline ,how can I follow interesting people?

Check the explore tab!

**Comment by grishka** [comment]
Is this issue about something meaningful, or is it safe to close?

**Comment by chen244** [comment]
> Is this issue about something meaningful, or is it safe to close?

Yes,I will close
