### ISSUE TITLE
Add support for Android's adaptive themed icons

### ISSUE THREAD

**Issue by PhaserArray** [mastodon/mastodon-android#429]
Please add support for [Android's adaptive themed icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#design-adaptive-icons).

I understand the original asset has some SVG filters that can't convert to a simple vector shape, but I think a slightly simplified icon is preferred to one that doesn't work at all with Android's theming system.

Related to #296

**Comment by grishka** [comment]
Already done 2 months ago
https://github.com/mastodon/mastodon-android/commit/18633291e62870a7b69ba149bf5deb80977f0e9f
