### ISSUE TITLE
Images in notifications overflow

### ISSUE THREAD

**Issue by Brawaru** [mastodon/mastodon-android#43]
![Screenshot of image in notifications exceeding the quotation block boundaries](https://user-images.githubusercontent.com/10401817/164034515-6ed159f8-bbf9-456a-9dcd-cb7d55fd7535.png)

It seems that the images in notifications aren't confined to the boundaries of ‘quotation’ box, they are padded correctly (?) but can overflow (see at the bottom of screenshot).

**Comment by Brawaru** [comment]
Have you tried with [that exact image](https://user-images.githubusercontent.com/10401817/164040358-0e128f85-8906-4e7d-913f-1f472861683d.jpg)? Also, I wonder if it matters that it's a reply.

**Comment by grishka** [comment]
¯\\\_(ツ)_/¯
![Screenshot_20220419-183534](https://user-images.githubusercontent.com/1478258/164041649-489aaab2-79ff-4d37-a433-2ff4d268f172.png)
(pixel 4a, stock android 11)

**Comment by Brawaru** [comment]
> Also, I wonder if it matters that it's a reply.
?

**Comment by grishka** [comment]
Nope, just tested that

**Comment by Brawaru** [comment]
Makes me wonder. What happens if it is a reply and has new lines in the post (like I have two mentions separated by new line)?

**Comment by realpixelcode** [comment]
Though, I think images shouldn't be displayed in the notifications because they take up so much space that shouldn't be wasted just for the information that someone has favourited or boosted your toot. If you still want to see the entire toot, you can just open it separately by clicking on it.

Maybe, also the text of toots in the notifications could be collapsed 🤔

**Comment by grishka** [comment]
> Makes me wonder. What happens if it is a reply and has new lines in the post (like I have two mentions separated by new line)?

These things shouldn't influence each other. Posts (and notifications) are rendered as a series of "[display items](https://github.com/mastodon/mastodon-android/tree/master/mastodon/src/main/java/org/joinmastodon/android/ui/displayitems)", as I call them. A block of text is a display item, each image is a display item, and the "in reply to", you'll never guess, is also a display item. This is how the scrolling is so smooth. The list uses a GridLayoutManager, but all items _except images and videos_ occupy all spans. So no, separate items shouldn't be able to affect each other.

The insets for notifications are done with this code I'm really not proud of:
https://github.com/mastodon/mastodon-android/blob/2e1f08a096fd55f0316e2012c274d7e9da8d058f/mastodon/src/main/java/org/joinmastodon/android/fragments/NotificationsListFragment.java#L211-L245

**Comment by grishka** [comment]
The problem was actually related to screen rotation and the changing size of the list caused by that.

**Comment by sk22** [comment]
Do you still have this issue as well, @Brawaru? Because I unfortunately do…
