### ISSUE TITLE
Some polls do not show any votes

### ISSUE THREAD

**Issue by brawaru** [mastodon/mastodon-android#44]
Posts from Pleroma instances (?) by some reason do not show any votes, even though they do in web version.

![Screenshot of the poll with seemingly zero votes](https://user-images.githubusercontent.com/10401817/164042135-00b96dd4-d00e-41b2-8fe9-cfd9ecbe7294.png)

Poll on screenshot — https://soc.phreedom.club/objects/450d5b27-cd3a-4c92-83bf-8541e2fd044e.

![Screenshot of the same poll from the web version with 73 votes](https://user-images.githubusercontent.com/10401817/164041906-4365f40f-cbd8-466c-85b5-c0f55d43de43.png)

**Comment by RaissaDavinha** [comment]
Do you have more information like version and device type?

**Comment by grishka** [comment]
I believe this is the same as #544, which I recently fixed
