### ISSUE TITLE
Login screen: "Server URL" hitbox too small

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#446]
There's a relatively wide area on the right-hand edge of the "Server URL" text box that's not clickable.

![Screenshot_2022-12-07-17-12-15-022_org joinmastodon android sk debug](https://user-images.githubusercontent.com/6217438/206231681-07e04d92-1816-4df2-80f4-fcdfc1d3fb09.jpg)

**Comment by grishka** [comment]
Yes it is, because I knowingly made it so.
