### ISSUE TITLE
Feature Request - Multiaccount interaction with toots

### ISSUE THREAD

**Issue by jbalint-de** [mastodon/mastodon-android#466]
When using multiple accounts in the app it should be possible interacting  with posts from the timeline currently scrolled with all accounts currently signed in. For example boosting and commenting or simply opening a particular toot with a different account should be possible for all accounts signed in on a device. 

Maybe using long press on the existing buttons should open a context menu offering to use a different account for performing the interaction.

**Comment by realpixelcode** [comment]
Duplicate of #58

**Comment by jbalint-de** [comment]
Closing and extending request in before mentioned duplicate issue.
