### ISSUE TITLE
1.1.4 crashes when searching an Akkoma instance

### ISSUE THREAD

**Issue by ymollard** [mastodon/mastodon-android#468]
Mastodon for Androd 1.1.4 (45) crashes when typing at least 5 characters in the search bar from an account run by Akkoma 3.3.1-0-gba132a7 instance.

It seems to happens systematically, except in these situations:
* if I search on the "message" tab or the "People" tab
* if I type less than 5 characters
* If the search does not run Akkoma

Here are logs from the server, the search runs well up to 5 characters, and then after the second request the app crashed:
```
ip - - [17/Dec/2022:15:20:19 +0000] "GET /api/v2/search?q=barba&resolve=true HTTP/2.0" 200 18380 "-" "MastodonAndroid/1.1.4"
ip - - [17/Dec/2022:15:20:23 +0000] "GET /api/v2/search?q=barbatro&resolve=true HTTP/2.0" 200 1049 "-" "MastodonAndroid/1.1.4"
```

**Comment by sk22** [comment]
in my experiences, crashes seem to happen when the search result contains a hashtag - because, as it seems, akkoma doesn't provide the "history" property, which mastodon for android expects to be not null
