### ISSUE TITLE
Copying username doesn't show toast message (Android 13, MIUI)

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#469]
```
// Android 13+ SystemUI shows its own thing when you put things into the clipboard
if(Build.VERSION.SDK_INT<Build.VERSION_CODES.TIRAMISU){
	Toast.makeText(getActivity(), R.string.text_copied, Toast.LENGTH_SHORT).show();
}
```

Apparently though, MIUI doesn't show its own thing when copying things - I don't get any feedback at all when copying the username on my Xiaomi 12 running MIUI 13 with Android 13.

**Comment by grishka** [comment]
Xiaomi... Xiaomi never changes 😢

**Comment by sk22** [comment]
yep… :/ i plan to flash lineageOS as soon as possible anyway, so that would make one MIUI user less to worry about

**Comment by grishka** [comment]
Can you please build the app with this commit and confirm that my MIUI detection is working? The newest Xiaomi device I own is too old.

**Comment by sk22** [comment]
yup, works. thanks!
