### ISSUE TITLE
[BUG] can't sign up because something is wrong with the password confirms steps

### ISSUE THREAD

**Issue by jixiaoyong** [mastodon/mastodon-android#472]
Hi,

Thank you for this great project.

When I try to create a new account with mastodon app, it keeps warning me "Passwords don't match". I am sure that my code is the same.
After checking out, I find the code below compares the `Editable` objects rather than the code `String`, which will never be the same and cause the wrong result.

https://github.com/mastodon/mastodon-android/blob/6f2e5a63d70945410832cb7e40bad73b9620f878/mastodon/src/main/java/org/joinmastodon/android/fragments/onboarding/SignupFragment.java#L158

Maybe I will create a pull request to fix this.

**Comment by grishka** [comment]
Thanks, makes sense. There's a reason these changes are not released yet :D
