### ISSUE TITLE
Notification setting is reset after every update

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon-android#497]
1. Set notification setting as "noone"
2. Update app
3. Notification setting is reset

Version:
v1.1.5

Additional context

Update from f-droid - affected
Update from app itself - affected

related: https://github.com/sk22/megalodon/issues/252

**Comment by grishka** [comment]
It feels like I'm not passing things correctly when re-registering for push notifications after the app updates. I'll look into it.

**Comment by grishka** [comment]
Actually, it's the server not returning the `policy` field for some reason. So one can set it but not retrieve its current value? [The docs](https://docs.joinmastodon.org/methods/push/) also make no mention of `policy` in responses, only as a request parameter. @Gargron is this a bug on your side?
