### ISSUE TITLE
Draft Lost in Task Switching w/Picture Attachment

### ISSUE THREAD

**Issue by ellestad** [mastodon/mastodon-android#505]
If I task switch from the Mastodon Android App with a message draft open after having added a picture attachment, when you switch back to the Mastodon app, the draft message is lost. Does not happen without a picture attachment.

Pixel 5
Mastodon for Android 1.1.4 (45)
Android Version 13
Build number TP1a.221105.002

**Comment by grishka** [comment]
Already fixed but not yet released
