### ISSUE TITLE
FR: Open links in app

### ISSUE THREAD

**Issue by torgeros** [mastodon/mastodon-android#507]
It would be nice to be able to open any mastodon links in the app (instead of the browser).

This of cause would need to work for all instances.

It is kind of easy to add links for renowned instances like mastodon.social. This is not ideal, because there is obviously no list of all instances.

An alternative could be to have a url-scheme like `masto://<url>` that then opens in the android app. The website could then show a button to "open in app". This, however, would need to be defined on a global mastodon level and is therefore not feasible.

It would be interesting to research, whether apps can allow users to add custom links to an app that this app can then open. After all, the used protocols are the same for all instances, it is just about the url of the host to open...

---

Edit: NewPipe (foss youtube client) has a list of 51 urls of different video and audio hosting platforms that they support. I really hate this but it works, because users can configure whatever platforms they regularly use

**Comment by grishka** [comment]
Already discussed in #380 and #110.

**Comment by torgeros** [comment]
duplicate
