### ISSUE TITLE
Inline local translations are nonfunctional

### ISSUE THREAD

**Issue by deanveloper** [mastodon/mastodon-android#509]
Android semi-recently added a feature where you can translate any text that's in a different language by highlighting it and clicking "Translate", which brings up a modal of your preferred translation app.

Here is the expected behavior in Sync for Reddit:
![Screenshot_20230120-155638](https://user-images.githubusercontent.com/3196327/213813821-3d8d9500-c542-4343-afb0-f689c2d94317.png)

And the unexpected behavior in Mastodon:
![Screenshot_20230120-160016](https://user-images.githubusercontent.com/3196327/213814054-fb2511ac-6162-475c-8fac-bbd0922de7a7.png)

It's not clear in screenshots, but clicking the "translate" button simply does nothing, it doesn't even close the context menu.

**Comment by deanveloper** [comment]
I was originally filing this bug with Megalodon, however it appears in upstream Mastodon. Here is my original bug report for Megalodon which I instead filed here after testing on upstream: https://github.com/sk22/megalodon/issues/337

**Comment by grishka** [comment]
Hm. Where is the setting to choose which app is that? I have an English dictionary app installed, and I do have "define" in that popup for some words.

**Comment by grishka** [comment]
```
01-21 01:22:39.857  3757  4449 I AiAiTextClassifier: [AiaiTextClassifierLibWrapper]: classifyTextInternal: return system response
01-21 01:22:39.880  1901  3835 I AppsFilter: interaction: PackageSetting{f763944 org.joinmastodon.android/10551} -> PackageSetting{debd1ac ru.yandex.translate/10009} BLOCKED
01-21 01:22:39.880  1901  3835 I AppsFilter: interaction: PackageSetting{f763944 org.joinmastodon.android/10551} -> PackageSetting{e52de75 org.wikipedia/10526} BLOCKED
01-21 01:22:39.880  1901  3835 I AppsFilter: interaction: PackageSetting{f763944 org.joinmastodon.android/10551} -> PackageSetting{c8e8e0a org.mariotaku.twidere/10225} BLOCKED
01-21 01:22:39.880  1901  3835 I AppsFilter: interaction: PackageSetting{f763944 org.joinmastodon.android/10551} -> PackageSetting{db5b67b livio.pack.lang.en_US/10304} BLOCKED
01-21 01:22:39.880  1901  3835 I AppsFilter: interaction: PackageSetting{f763944 org.joinmastodon.android/10551} -> PackageSetting{21a5c98 com.google.android.apps.translate/10295} BLOCKED
```
ugh. So this must be related to the new package querying permissions.

**Comment by grishka** [comment]
It does work on a Galaxy S9 running Android 10, so it must be that. One would think that Android wouldn't break itself due to its own security, but ¯\_(ツ)_/¯

**Comment by deanveloper** [comment]
Weird, I'd at least expect it to hide the button entirely instead of failing after pressing it. 🤷

**Comment by sk22** [comment]
https://user-images.githubusercontent.com/6217438/213840175-985ce195-cfb1-4405-a722-bdb00a8bc73c.mp4

doesn't work on MIUI either (not to anyone's surprise), plus it seems i just discovered another bug…

**Comment by grishka** [comment]
> it seems i just discovered another bug…

In MIUI ;)

**Comment by deanveloper** [comment]
Can this be reopened? Looks like this still isn't quite fixed: 
![Screenshot_20230218-030714](https://user-images.githubusercontent.com/3196327/219857083-b16c83db-409d-42c0-8b69-bd28b84b2cfc.png)

However, if you open up the "..." menu, there is a second translate button there, and that one works. Weird
![Screenshot_20230218-031003](https://user-images.githubusercontent.com/3196327/219857112-da1fc750-8cb3-4db3-a243-60933b1a98e7.png)

**Comment by grishka** [comment]
Works for me (Pixel 4a, Android 13)
https://user-images.githubusercontent.com/1478258/219904470-b944d4ff-f046-4552-b16a-c6f4ac88a841.mp4

**Comment by deanveloper** [comment]
Can you try on this post? For me there are two translate buttons for some reason (as shown in my screenshots). The main one doesn't work, but the one in the "..." menu does

Pixel 7 Pro, Android 13

https://urusai.social/@ajissa/109891687590484807
