### ISSUE TITLE
ALT overlay can be too small to display any text

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#514]
Probably an edge case, but in those cases, the ALT button doesn't work as expected. (Also, and this occurs much more often, the expanded box is still very small and makes reading the text pretty painful.) Maybe this can be fixed by allowing it to overflow the current photo? No idea if this would be easy to implement, though

![Screenshot_2023-01-22-20-13-57-028_org joinmastodon android-edit](https://user-images.githubusercontent.com/6217438/213935388-e3d5810e-77a9-43b8-ad2d-a8eb30afd64e.jpg)
![Screenshot_2023-01-22-20-14-07-835_org joinmastodon android-edit](https://user-images.githubusercontent.com/6217438/213935390-93bb44d5-403c-455d-88a2-3531fd72e918.jpg)

**Comment by grishka** [comment]
> Maybe this can be fixed by allowing it to overflow the current photo?

The way display items work, this would be really painful.

**Comment by grishka** [comment]
This was fixed by making the entire media attachments block a single display item so alt text overlays can now span multiple attachments.
![Screenshot_20230601_191221](https://github.com/mastodon/mastodon-android/assets/1478258/b9e5deb8-7c5e-4b91-8e30-0017c3b33fee)
