### ISSUE TITLE
App crashes when you add second image to your post 

### ISSUE THREAD

**Issue by olekstomek** [mastodon/mastodon-android#522]
Steps:
1. Start adding new post
2. Attach first image
3. Attach second image
4. App crash. 

I don't have logs. App is closed automatically. 

Xiaomi Mi 9, Android 11, Mastodon for Android v1.1.4 (45)

The same problem here: https://github.com/mastodon/mastodon/issues/23300

**Comment by grishka** [comment]
Already fixed but not yet released.
