### ISSUE TITLE
ALT not writable under  Android  when editing an already existing troet

### ISSUE THREAD

**Issue by rcpffm** [mastodon/mastodon-android#523]
When I use "bearbeiten" = edit of an already existing troet I can edit the ALT text, but when I click "Save" I get "record not found", the changed ALT text is not saved.

**Comment by Gargron** [comment]
It’s not currently possible to change media descriptions when editing a published post in Mastodon, this is not a problem unique to this app.

**Comment by rcpffm** [comment]
hope it is in work. sometime.
