### ISSUE TITLE
Private reply by original poster publicly visible

### ISSUE THREAD

**Issue by FakePlasticDunk** [mastodon/mastodon-android#532]
Every now and then I notice that I can see what appears to be a private reply (i.e. named only). The common factors appear to be that the reply is by the original poster, replying to a private reply by someone else to one of their posts. Screenshot attached. 
![Screenshot_20230209-190043](https://user-images.githubusercontent.com/123900329/218157806-7950c24c-00b9-4761-8c55-495453bf907a.png)

**Comment by grishka** [comment]
You mean you're seeing something you think you aren't supposed to see?

Either way, this is controlled entirely by the server. The app simply turns the JSON that the server returns into something more fit for human consumption — no privacy-related filtering is done on the client side, obviously.

**Comment by FakePlasticDunk** [comment]
Yes, that is what I mean. So... who should I point this out to? I've noticed it a few times now, but this is the only screenshot I have. Probably best assume that nothing is 'obvious' to me. 

Sent from Yahoo Mail on Android 
 
  On Fri, 10 Feb 2023 at 17:37, Gregory ***@***.***> wrote:   


You mean you're seeing something you think you aren't supposed to see?

Either way, this is controlled entirely by the server. The app simply turns the JSON that the server returns into something more fit for human consumption — no privacy-related filtering is done on the client side, obviously.

**Comment by grishka** [comment]
Which instance are you on? Does it run Mastodon or something else? Is it upstream Mastodon, or a fork?

**Comment by FakePlasticDunk** [comment]
1) I'm on universeodon.com 2) don't know3) don't know

Sent from Yahoo Mail on Android 
 
  On Fri, 10 Feb 2023 at 17:43, Gregory ***@***.***> wrote:   


Which instance are you on? Does it run Mastodon or something else? Is it upstream Mastodon, or a fork?

**Comment by grishka** [comment]
Yes, it runs upstream Mastodon. Although a release candidate. Either way, this issue is not with the app itself. Could you please reproduce it somewhere else just to be extra sure, for example on the web or in a 3rd-party app like Tusky? Then it would make sense to create an issue [in the main Mastodon repo](https://github.com/mastodon/mastodon).

**Comment by FakePlasticDunk** [comment]
Ok I'll have look on the browser, I should have done that first shouldn't I. Yup, ok, assuming that it's visible there too I'll raise it there. Thanks Gregory.Duncan 

Sent from Yahoo Mail on Android 
 
  On Fri, 10 Feb 2023 at 18:29, Gregory ***@***.***> wrote:   


Yes, it runs upstream Mastodon. Although a release candidate. Either way, this issue is not with the app itself. Could you please reproduce it somewhere else just to be extra sure, for example on the web or in a 3rd-party app like Tusky? Then it would make sense to create an issue in the main Mastodon repo.

**Comment by FakePlasticDunk** [comment]
PS yes, it is visible on the browser client on universeodon.con
Sent from Yahoo Mail on Android 
 
  On Fri, 10 Feb 2023 at 18:29, Gregory ***@***.***> wrote:   


Yes, it runs upstream Mastodon. Although a release candidate. Either way, this issue is not with the app itself. Could you please reproduce it somewhere else just to be extra sure, for example on the web or in a 3rd-party app like Tusky? Then it would make sense to create an issue in the main Mastodon repo.

**Comment by FakePlasticDunk** [comment]
Post was set to 'followers only' so all is in order.
