### ISSUE TITLE
Any chance we can override the emojis with tweemoji? 

### ISSUE THREAD

**Issue by ice1000** [mastodon/mastodon-android#546]
This is supported by Discord. How difficult it would be, technically?

**Comment by grishka** [comment]
> How difficult it would be, technically?

Very. In a previous project, I had to use Apple emoji. All those custom spans, sprites, trees, parsers, async loading — I'm very happy this is over and we can finally just let the OS do its job.

There is #470 for new unicode emoji support on Android 11 and earlier, but that relies on the content provider in GSF for the font. My eventual plan is to take the library they offer and de-appcompat-ize it like I did with the rest of the AndroidX libraries I use.

**Comment by ice1000** [comment]
I see, thanks for the reply!
