### ISSUE TITLE
"CW revealed" state inconsistent with what display items show

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#548]
to reproduce:

1. reveal a post's CW in timeline
2. open post
3. hide the post's content using the 👁️ button
4. go back to the timeline
5. (see that the content is still being displayed)
6. click the 👁️ button to hide the content → nothing happens because the status' revealed state was already "false"
7. click the 👁️ button again to actually hide the content

https://user-images.githubusercontent.com/6217438/226313142-c0b6c972-7d4c-4a6d-93b9-4fd512ac839d.mp4

**Comment by grishka** [comment]
The 👁️ button will be removed in the material 3 redesign anyway.

**Comment by sk22** [comment]
https://github.com/mastodon/mastodon-android/assets/6217438/1b4de36d-5157-46d1-96cc-47bcb71447ca

okay, update; currently, it's actually even buggier in the m3 redesign…

**Comment by grishka** [comment]
oof
