### ISSUE TITLE
Notification List Cache Doesn't Update

### ISSUE THREAD

**Issue by Tom-Archer** [mastodon/mastodon-android#553]
App version 1.2.0

When opening the app and navigating to the "Notifications > All" tab, initially I can only see old notifications (from the 28th of January). Refreshing the tab correctly shows my latest notifications. When I force-close and re-open the app, I can again only see old notifications.

I've tried clearing the app cache and storage and re-installing.

**Comment by Tom-Archer** [comment]
I've noticed this is also a problem with the web-version, albeit it presents a little differently. This probably points at it being an issue in the Mastodon source or the instance? I've raised a bug over on https://github.com/mastodon/mastodon/issues/24256

**Comment by grishka** [comment]
It turns out sqlite doesn't compare strings the way I expected it to. IDs that are strings are a pain in the ass to work with.
