### ISSUE TITLE
Filters aren't applied in the app

### ISSUE THREAD

**Issue by pabloscloud** [mastodon/mastodon-android#572]
When scrolling through Moshidon I can show the hidden toots with just a tap. In the mastodon app toots that should be filtered are just displayed as if there were no filters. This is I correct behavior. The website applies the filters as well.

![74be6d6d-c8e5-4e7d-ba34-106126d59ae0](https://user-images.githubusercontent.com/93644977/234040177-bab2affc-f88c-44ec-8967-4e3d9eadbc6d.png)
![a7eb054e-2489-49ad-9157-0cacf0949f07](https://user-images.githubusercontent.com/93644977/234040188-69634403-bd40-4134-94cd-91835d0d29cb.png)

**Comment by grishka** [comment]
Fixed in the upcoming version.
![image](https://github.com/mastodon/mastodon-android/assets/1478258/9e71d2af-51b3-4929-b738-b6ffb1a71b6f)

**Comment by pabloscloud** [comment]
Very nice
