### ISSUE TITLE
m3_redesign account switcher: clicking radio button doesn't switch account

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#587]
when clicking a radio button (instead of the surrounding item) in the new account switcher, the radio button itself gets selected, but the account doesn't switch

**Comment by grishka** [comment]
Yep, this needs to be replaced with my newer approach with `Checkable*Layout` and just a `View` with the background set to the drawable of a checkbox or a radio button. Why use real radio buttons where a fake one would suffice? :P
