### ISSUE TITLE
m3_redesign: logging out of currently logged in account doesn't switch accounts

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#588]
when you long-press-to-log-out of the account you're currently logged into, mastodon doesn't switch accounts - rather, it crashes on the next interaction

**Comment by grishka** [comment]
I already refactored logout as part of the settings redesign

**Comment by grishka** [comment]
It *does* switch accounts:
https://github.com/mastodon/mastodon-android/blob/7c6ec2e3d7dbab400e4e12cd9a6de6d4af86ce85/mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSessionManager.java#L188-L193
It doesn't write the new account into the preferences, and *that* I fixed now.
