### ISSUE TITLE
Main navigation's height is not right

### ISSUE THREAD

**Issue by ivadham** [mastodon/mastodon-android#59]
Main navigation's height (the red one) should not depend on System navigation (the cyan one). On my device, it is 190px tall on Gesture navigation, and 138px tall on 3-button navigation. Also, when on Gesture navigation, the icons are not vertically centered.

![wrongHeight](https://user-images.githubusercontent.com/11696957/164271415-d7cea8e9-9cc0-41fc-b86c-bb569f04692a.png)

**Comment by realpixelcode** [comment]
Can confirm this.

![Screenshot-2022-04-21-14-15-40.png](https://user-images.githubusercontent.com/52963327/164456108-86c97af8-cd9d-4a15-8a6e-1fcc19c70d6f.png)

Though, with gesture navigation, the icons are vertically centered in the search tab when the keyboard is opened:

![Screenshot-2022-04-21-14-16-00.png](https://user-images.githubusercontent.com/52963327/164456244-b15d0124-cd6f-405d-9bfe-5bd15650834c.png)

**Comment by ivadham** [comment]
[v2.0.0](https://github.com/mastodon/mastodon-android/releases/tag/v2.0.0) fixes this. Thanks!
