### ISSUE TITLE
Google Play Upgrade Causes Complete App Reset

### ISSUE THREAD

**Issue by timnolte** [mastodon/mastodon-android#599]
I feel like this is the second time where I've installed the update from the Google Play Store to find that the entire application completely resets and I have to login fresh and set up the app all over again. This is super annoying.

Version: 1.2.3+fork.95-play

Is this some result of the app being available through other means and when it's built for Google Play it can't reuse a previous install data set due to some security restriction?

**Comment by grishka** [comment]
You're using a fork, not an official build. Please report your issue to the developers of the fork you're using.

**Comment by timnolte** [comment]
Oops, somehow I ended up here instead of the fork
 Sorry.
