### ISSUE TITLE
kbin help

### ISSUE THREAD

**Issue by usnbtv** [mastodon/mastodon-android#601]
kbin.social will his support come?![kbin.jpg](https://github.com/mastodon/mastodon-android/assets/26837921/ee34e1f9-2e7e-46f8-8acf-801aac32c05c)

**Comment by grishka** [comment]
This is the Mastodon app. The only server software it officially supports is Mastodon. It may work with servers running other ActivityPub software (Pleroma, Pixelfed, etc) if they offer a compatible client API, but we make no guarantees about such servers. You're on your own if something doesn't work on a non-Mastodon server.
