### ISSUE TITLE
M3: Inconsistent state when refreshing; spoiler deletes footer

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#604]
when refreshing after revealing a spoiler, the spoiler thinks the text is still revealed, so when pressing it, it "eats" the post footer instead of revealing the text

https://github.com/mastodon/mastodon-android/assets/6217438/fa423007-da46-46f7-98c0-a4801c1953d3

**Comment by sk22** [comment]
i assume you meant

```

**Comment by grishka** [comment]
Hm. Actually, I should always set that flag on the top-level status.
