### ISSUE TITLE
m3: admin follow button defunct in instance info

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#606]
![Screenshot_20230621-122808_Mastodon](https://github.com/mastodon/mastodon-android/assets/6217438/72d8a4a4-4c43-42bf-968d-a72549b6e1e3)

should probably display "follow"/"following", but displays and does seemingly nothing

**Comment by grishka** [comment]
Yes I'm still waiting for complete design specs on that component. There isn't supposed to be a button on this screen.
