### ISSUE TITLE
m3: when posting reply and opening it, it has an invalid state in home timeline

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#610]
not 100% sure what might cause this, but i can reproduce it like this:

1. make a post (with CW)
2. open that post
3. post a reply (also with CW)
4. open the CW
5. go back to the home timeline
6. see that the newly added reply is displayed with "Re-hide" even though there's no content being displayed
7. pressing the CW will eat the footer

https://github.com/mastodon/mastodon-android/assets/6217438/47304230-e889-46d6-b6d3-af1e3dbecba6

**Comment by grishka** [comment]
I **am** 100% sure what causes this, it's the fact that the same post object ends up existing on different screens because of the event bus.
