### ISSUE TITLE
m3: user autocomplete disappears when entering instance

### ISSUE THREAD

**Issue by sk22** [mastodon/mastodon-android#611]
https://github.com/mastodon/mastodon-android/assets/6217438/71ef5a53-1eba-4d07-8fa6-783e05b9db94

**Comment by grishka** [comment]
I can't reproduce it 🤔
![screenshot](https://github.com/mastodon/mastodon-android/assets/1478258/decdb605-b2c1-4f23-b943-b09f98639f2f)

**Comment by sk22** [comment]
huh, weird?! if this info helps; autocomplete does appear when i select something from autocomplete and then press backspace.. but once i manually press @, it seems to always terminate the autocomplete span (just an assumption, i haven't tried debugging it.. yet anyway)

**Comment by grishka** [comment]
For me it disappears when I type the @ but then reappears after I start typing the domain. It does make *technical* sense because a mention that ends with a @ is invalid. The mention regex doesn't match it.

**Comment by grishka** [comment]
Huh, I can reproduce it on Android 13. That's... strange. I mean it's regular expressions and spanned strings, these things should work the same they did on Android 1.6 🤔
