### ISSUE TITLE
Unable to add/edit new filter

### ISSUE THREAD

**Issue by bpepple** [mastodon/mastodon-android#620]
When adding a new filter, the following error message is given when attempting to save it.

![Screenshot_20230702-140917.png](https://github.com/mastodon/mastodon-android/assets/8381/0f669188-388f-4968-91f2-d0265e9008b1)

**Comment by Gargron** [comment]
What's the version of the Mastodon server you're connected to?

**Comment by bpepple** [comment]
> What's the version of the Mastodon server you're connected to?

v4.1.2

**Comment by bpepple** [comment]
> What's the version of the Mastodon server you're connected to?

Verified that this doesn't work on v4.1.3 nor v4.1.3+nightly-20230706

**Comment by davidn** [comment]
Also happening on mstdn.social (4.1.5) from Android (2.0.1)
