### ISSUE TITLE
Recents URL sharing support

### ISSUE THREAD

**Issue by Dubzer** [mastodon/mastodon-android#632]
Hi.
It would be nice if the app supported the Recents URL sharing API: https://developer.android.com/guide/components/activities/recents#url-sharing.

**Comment by grishka** [comment]
You mean to share URLs **from** the app, of whatever is currently open?

**Comment by Dubzer** [comment]
@grishka I'm not quite sure I understand your question correctly. But there's a video demo if you follow the link.
This API allows an app to announce its currently opened link to the system. And then system shows it in the recent apps screen.

So, for example if I open some profile in Mastodon, then its URL should be shown in recents, like in demo.

![image](https://github.com/mastodon/mastodon-android/assets/18244287/3a8ead5b-d073-449f-aa61-a14865a69491)
