### ISSUE TITLE
UI glitch on profile page

### ISSUE THREAD

**Issue by HughIngram** [mastodon/mastodon-android#638]
My profile page looks like this, with many views overlapping. Other peoples' profile pages are unaffected.

Pixel 6A, Android 13. App version 2.0.1

![Screenshot_20230709-231354.png](https://github.com/mastodon/mastodon-android/assets/6364856/31e4dc17-1f92-420b-9340-ca63c0f6bbfe)

**Comment by grishka** [comment]
Duplicate of #619
