### ISSUE TITLE
clicking on links shoukd give a warning 

### ISSUE THREAD

**Issue by RustoMCSpit** [mastodon/mastodon-android#645]
you are about to be taken to: poopland.com
continue? go back?

also should warn if it doesnt supoort https or if ublock finds it suspicious

**Comment by grishka** [comment]
It absolutely shouldn't. I hate this "feature" in Discord with a burning passion and I wouldn't wish having to confirm every link click on my worst enemy.

**Comment by RustoMCSpit** [comment]
> It absolutely shouldn't. I hate this "feature" in Discord with a burning passion and I wouldn't wish having to confirm every link click on my worst enemy.

yeah so it should be a toggle on setting for those that do want it

**Comment by RustoMCSpit** [comment]
> It absolutely shouldn't. I hate this "feature" in Discord with a burning passion and I wouldn't wish having to confirm every link click on my worst enemy.

anyways the https thing is totallt valid even if yiu disagree with makinf it a settinf, theres no reason why in 2023 a website shouldnt support that and a warning message is necessary

**Comment by RustoMCSpit** [comment]
but yeah just make it a toggle on off setting right

**Comment by grishka** [comment]
IMO the https part is not the responsibility of the app. Mastodon is far from being the only app that opens links in the browser.

It's browser extension territory. There are extensions that redirect from http:// to https:// and I'm sure mobile Firefox supports them. There still are valid use cases for plaintext HTTP too. Things like LAN/intranet services for example, or TOR websites.

**Comment by RustoMCSpit** [comment]
> IMO the https part is not the responsibility of the app. Mastodon is far from being the only app that opens links in the browser.
> 
> It's browser extension territory. There are extensions that redirect from http:// to https:// and I'm sure mobile Firefox supports them. There still are valid use cases for plaintext HTTP too. Things like LAN/intranet services for example, or TOR websites.

fair enough, can we make the link warnings an opt in setting for those that do like it?
