### ISSUE TITLE
Bottom navigation bar icons should get filled, once active

### ISSUE THREAD

**Issue by pabloscloud** [mastodon/mastodon-android#650]

**Comment by grishka** [comment]
They shouldn't.

**Comment by pabloscloud** [comment]
It's even documented like that in their guidelines. What do you mean they shouldn't?

![Screenshot_20230721-093136_Ecosia.png](https://github.com/mastodon/mastodon-android/assets/93644977/7d6055c4-5bf7-431e-b09e-2ed50364af81)

https://m3.material.io/components/navigation-bar/guidelines
