### ISSUE TITLE
User's own timeline is broken

### ISSUE THREAD

**Issue by opedron** [mastodon/mastodon-android#657]
Hi everyone,

I'm using the latest version of the Mastodon app for Android and my own timeline is broken everytime I scroll through my own content. Not sure what the problem is here, but it has been like this for a few weeks now.

Screenshot a
![Screenshot_20230725_205514_Mastodon](https://github.com/mastodon/mastodon-android/assets/140553940/b8bc546b-5a94-4241-a02b-8239895b0df7)
ttached.

**Comment by grishka** [comment]
Duplicate of #619
