### ISSUE TITLE
Can't save filters on Android on Mastodon.social

### ISSUE THREAD

**Issue by hach-que** [mastodon/mastodon-android#658]
This currently fails with a validation error:

![Screenshot_20230729-185023](https://github.com/mastodon/mastodon-android/assets/504826/650341d1-b355-4d12-8740-aa51af6ce71f)

**Comment by bama35453** [comment]
Same issue here for mastodon.social.
One little difference:
I don't get any error message at all.

**Comment by ClearlyClaire** [comment]
I can reproduce the issue.

This seems to be down to the application sending the filter parameters with incorrect keys, e.g. instead of title, this is `a`, instead of `context` this is `b`, and so on.
