### ISSUE TITLE
Incorrect state restoration in bottom navigation bar

### ISSUE THREAD

**Issue by cachapa** [mastodon/mastodon-android#683]
Sometimes, when returning to the app after it has been in the background for a while the bottom navigation state will be incorrect.

I haven't found a way to reproduce this reliably but once in a while I see it.

Tapping the home button in the bottom navigation bar takes me home, and everything else seems to keep the earlier state, so I assume it's just a visual glitch.

![Screenshot_20230905-204446.png](https://github.com/mastodon/mastodon-android/assets/1006207/4fa17b89-ebcd-42de-bdf5-bcddaeed3fd9)

**Comment by grishka** [comment]
I can't reproduce it at all 🤔
I tried enabling "don't keep activities" under developer options, as that is supposed to surface all the nasty bugs related to state restoration, but it does restore the selected tab correctly.

**Comment by grishka** [comment]
Ok, changing the theme between light and dark does it.
