### ISSUE TITLE
Crash when tapping on post

### ISSUE THREAD

**Issue by Erufailon4** [mastodon/mastodon-android#693]
In any view that lists posts (at least the home feed and an user page), tapping on a post to open it crashes the app. This only happens for posts that are loaded immediately upon entering such a view - scroll far down enough and it no longer happens. 

Mastodon Android v2.0.4 (64) from Google Play 
Android 11

**Comment by grishka** [comment]
Ah, yes, I fixed this. Someone broke placeholders in strings in several languages. Meanwhile, if you're using Android 13 or newer, you can set the app language to English to avoid this crash until the next update.

**Comment by th1nhhdk** [comment]
I have the same problem so i have to stay on 1.2.3, fixed it
thanks a lot!

**Comment by Erufailon4** [comment]
> Ah, yes, I fixed this. Someone broke placeholders in strings in several languages. Meanwhile, if you're using Android 13 or newer, you can set the app language to English to avoid this crash until the next update.

Oh, okay. Thanks for fixing it.
