### ISSUE TITLE
LED notification missing

### ISSUE THREAD

**Issue by zofoklecja** [mastodon/mastodon-android#695]
I'm using Android 11, OnePlus 6, 2.0.4 app version

By default when there is new notification on my phone, notification LED starts flashing. I rely quite a lot on this, especially when in conversation with someone. Unfortunately it doesn't seen to work with Mastodon app.  

![oneplus_notch](https://github.com/mastodon/mastodon-android/assets/8929565/a75f1393-5b93-49c7-b358-72a67b8711c9)

**Comment by grishka** [comment]
You may need to clear the app data after the next update for these changes to take effect. Alternatively, you can enable "blink light" in the system notification settings for the app.
![Screenshot_20230925_230236](https://github.com/mastodon/mastodon-android/assets/1478258/2af18a4f-c9bb-4767-9af1-8957700b2e4d)

**Comment by zofoklecja** [comment]
It did take clearing app data, but it works 🎉
Thank you so much!
