### ISSUE TITLE
Search indexing opt-in is not saved

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#698]
1. Go to `Settings > Privacy and reach`
2. Enable `Include public posts in search results`.
3. Go to home timeline.
4. Go to `Settings > Privacy and reach` again: Search indexing is disabled.

This happened with both https://social.tchncs.de and https://mstdn.social, which both run Mastodon v4.2.0.

https://github.com/mastodon/mastodon-android/assets/52963327/c41236a2-622a-4fbf-822c-400ee8c86cf4

**Comment by grishka** [comment]
Already fixed in fe1cfa1d7bb1a6f9fa861ed6c28180e45ddebf0c
