### ISSUE TITLE
Keep device awake during video playback

### ISSUE THREAD

**Issue by Discostu36** [mastodon/mastodon-android#7]
When watching a video, I have to touch the screen every few seconds to keep it turned on. The app should keep the device awake during playback.

Fairphone 4
Android 11
Mastodon for Android 1.0

**Comment by grishka** [comment]
Ah, right, I forgot about that.

(to be fair, the video player needs an actual UI too)

**Comment by grishka** [comment]
I'm keeping this issue open as a reminder to myself and @samhenrigold that we need a video player UI
