### ISSUE TITLE
`java.lang.IllegalStateException: Duplicate key` when using GoToSocial

### ISSUE THREAD

**Issue by tsmethurst** [mastodon/mastodon-android#703]
Heya! I know the Mastodon official app is for, well, Mastodon, and of course you probably don't worry too much about issues with other server implementations, so please feel free to disregard/close this issue if it's too far beyond your purview.

I was hoping, though, that you might be able to shed some light on an issue someone just opened on the GoToSocial repository, whereby their GtS profile doesn't load properly because of a duplicate key error. The issue and stack trace are here: https://github.com/superseriousbusiness/gotosocial/issues/2226

Do you have any idea about what's going wrong?

**Comment by grishka** [comment]
I had no idea that `Collectors.toMap` would throw an exception if you try to put a key into a map more than once. This is stupid and inexcusable behavior. The exception [is not documented either](https://docs.oracle.com/javase/8/docs/api/java/util/stream/Collectors.html#toMap-java.util.function.Function-java.util.function.Function-) (there's usually a "throws" section even for methods that only throw unchecked exceptions).

> and of course you probably don't worry too much about issues with other server implementations

I have a rule that no matter what the server does, the app should not crash.

**Comment by CDN18** [comment]
I can confirm that the fix worked. Using the latest commit build I no longer experience the crash when accessing my profile due to the `duplicate key` issue. Thank you for making the quick fix!
