### ISSUE TITLE
Lowercase  hashtag suggestions don't show for #CamelCase hashtags

### ISSUE THREAD

**Issue by anibyl** [mastodon/mastodon-android#708]
**Description**

When typing a hashtag, e.g. `#NonProfit`, `#nonprofit` suggestion shows only before the second capital letter is present, or after the hashtag is complete

**To reproduce**

1. Start creating a post
2. Type `#NonP` in, and continue until it becomes `#NonProfit`

https://github.com/mastodon/mastodon-android/assets/790717/98f19aa7-fb38-4884-a4bf-16a554de310f

**Comment by grishka** [comment]
The web app has the same behavior:
https://github.com/mastodon/mastodon-android/assets/1478258/351ce3ad-9776-4c74-9f98-f9a53f6c826b
Please report this [to the main repo](https://github.com/mastodon/mastodon/issues) instead.

**Comment by anibyl** [comment]
Oh I see, didn't think of that. Will do.

Maybe they didn't upload as videos because it's a comment? Not sure.
