### ISSUE TITLE
Android System App crashes at login

### ISSUE THREAD

**Issue by tiptoptom** [mastodon/mastodon-android#711]
When I try to login into the Mastodon app, select a server and press continue, the app crashes and a system message appears with Android system has been terminated.

Mastodon from F-Droid 2.1.6
Android 8.0.0

**Comment by grishka** [comment]
Are you using a custom ROM?

**Comment by tiptoptom** [comment]
No, but I have disabled Google Play services.

**Comment by tiptoptom** [comment]
The Mastodon app crashes and the Android-System app. The System UI keeps running. And yes I have Firefox and Tor.

**Comment by tiptoptom** [comment]
This is the problem:
https://github.com/zacharee/MastodonRedirect/issues/25
