### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by individual8** [mastodon/mastodon-android#720]
I seem [not the only one](https://mastodon.social/@nexuscodez@mstdn.social/111284713095185058) having issues with receiving notifications on Android right now. Using v2.1.6 and having both internally and externally activated all permissions for notifications, I don't receive any at the moment.

![image](https://github.com/mastodon/mastodon-android/assets/363356/92eb16eb-4fc0-4557-a94b-748beb76199e)
![image](https://github.com/mastodon/mastodon-android/assets/363356/e95cefaf-6829-4e3b-9331-d14e2bbc95b2)
![image](https://github.com/mastodon/mastodon-android/assets/363356/4ae6cfde-405e-4991-be40-d79987f810ab)

**Comment by grishka** [comment]
Do you have Google services installed?

**Comment by individual8** [comment]
I use a brand-new Pixel 8 Pro. I guess so. All other apps work as expected.

**Comment by individual8** [comment]
In the meantime I got some notifications again. Without any change on my side.

**Comment by grishka** [comment]
So maybe the problem is on your server.

**Comment by individual8** [comment]
That's why I opened this issue. To address it to maintainers of mastodon.social.

**Comment by Le1b1** [comment]
I'm also not receiving notifications on Mastodon for Android. Notifications are working with the app 'trunks' on the same account on same device.

Anything I can do to help debugging this?

**Comment by individual8** [comment]
Fixed.
