### ISSUE TITLE
Missing German translation in list menu in home screen

### ISSUE THREAD

**Issue by ElFrogster** [mastodon/mastodon-android#724]
App version 2.2.0
![Screenshot_20231029-105154389 (1)](https://github.com/mastodon/mastodon-android/assets/123737003/b113f2a3-91ed-4a92-a2ea-b8735b3b3dd5)

**Comment by grishka** [comment]
That's intended. Translations are done by volunteers on Crowdin and merged shortly before each update. Some translations — especially for new features — thus end up incomplete because no one translated those new strings yet.
