### ISSUE TITLE
[Feature]: passing ntfy notifation integration 

### ISSUE THREAD

**Issue by Today20092** [mastodon/mastodon-android#735]
### Description

I think it would be great for the android version of the app to have ntfy integration, because I don't believe ntfy works with ios, but it says to add feature requests here.

Ntfy is a push notification feature that allows you to recieve push notifications without using Google services.

### Suggested Solution

Add integration with unified push and ntfy as the distributor.

https://unifiedpush.org/users/faq/#what-are-push-notifications

### Additional Context

Matrix protocol client, Element, has the feature integrated in their app. If you have ntfy installed on Android then you can set ntfy as the push notifation server and it works automatically. For android users, this allows for saving battery life because you're only listening on one connection

**Comment by grishka** [comment]
This requires server support, doesn't it?

**Comment by FineFindus** [comment]
Not really, [Unified Push](https://unifiedpush.org/) uses Web Push, which is already partially supported by the Mastodon server. Unfortunately, it still uses an older version of the protocol, so the received notification cannot be decrypted on the client side. This can be partially mitigated by using the API to request the notifications.

See https://github.com/sk22/megalodon/pull/749 for an initial implementation in a fork. I'd be happy to upstream it if you'd like.

**Comment by Today20092** [comment]
> Not really, [Unified Push](https://unifiedpush.org/) uses Web Push, which is already partially supported by the Mastodon server. Unfortunately, it still uses an older version of the protocol, so the received notification cannot be decrypted on the client side. This can be partially mitigated by using the API to request the notifications.
> 
> See [sk22#749](https://github.com/sk22/megalodon/pull/749) for an initial implementation in a fork. I'd be happy to upstream it if you'd like.

Hey that's awesome. I just downloaded megladon and ima try it out. How long did it take you to integrate the unified push in your pull request?
