### ISSUE TITLE
WordPress link not clickable

### ISSUE THREAD

**Issue by realpixelcode** [mastodon/mastodon-android#737]
Today, I came across [this WordPress post](https://laurenshof.online/bluesky-crosses-the-mark-for-2-million-accounts/) and noticed that it included a non-clickable link to itself at the end of the text. The link is not part of the original blog post, but is instead inserted later during federation by WordPress or by the Mastodon app.

![Screenshot-2023-11-14-07-32-59.png.png](https://github.com/mastodon/mastodon-android/assets/52963327/6705e30c-be8e-41b2-a5d2-7f999cd9e167)

**Comment by grishka** [comment]
This is an issue with WordPress. Mastodon, and most other ActivityPub servers, rely on the originating server to format the text correctly. They don't parse any URLs into links, the only processing they do with the text in incoming posts is filtering the HTML against a whitelist of tags and attributes for safety. The app is pretty dumb in this regard too, it just renders the HTML that comes from the server.
