### ISSUE TITLE
Not available on play store?

### ISSUE THREAD

**Issue by AverytheFurry** [mastodon/mastodon-android#74]
Searching for mastodon on the google play store returns nothing on my phone, however, searching on the aurora store does show it, and it works perfectly fine that way.

**Comment by grishka** [comment]
It does show up for me, just not as high up as it should ideally be.

![Вставленное_изображение_26_04_2022__01_27](https://user-images.githubusercontent.com/1478258/165185134-ba60111b-8f33-4903-8c3d-5763bda9c3b8.jpg)

**Comment by AverytheFurry** [comment]
> It does show up for me, just not as high up as it should ideally be.
> 
> ![Вставленное_изображение_26_04_2022__01_27](https://user-images.githubusercontent.com/1478258/165185134-ba60111b-8f33-4903-8c3d-5763bda9c3b8.jpg)

Oh, you're right, I searched for a while but it was *WAY* far down on the mobile app
