### ISSUE TITLE
Crashing when tapping my toots

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#741]
Latest version 2.2.2 crashes if I tap my toots. I've tried it my TL and My Profile and faced the same bug.

**Comment by grishka** [comment]
Can you please provide a crash log?

**Comment by grishka** [comment]
If you have adb: `adb logcat | grep AndroidRuntime`

If you don't: create a bug report in developer options, send it to yourself somewhere, unzip it. Open the huge text file. Search for `AndroidRuntime` or `FATAL EXCEPTION`. Copy the exception stack that mentions `org.joinmastodon.android`.

If you don't have developer options, tap the "build number" in system settings until it says "you're now a developer".
