### ISSUE TITLE
Filters set to hide posts still shows them with CW

### ISSUE THREAD

**Issue by thecrazything** [mastodon/mastodon-android#747]
When setting a filter with the "show with content warning" toggle set to false, the posts still shows up behind a content warning instead of being hidden completely.

![Screenshot_20231123-102239](https://github.com/mastodon/mastodon-android/assets/6420379/7a8aa81b-9377-4494-aadb-98187ede027f)
![Screenshot_20231123-102252](https://github.com/mastodon/mastodon-android/assets/6420379/95fd0da4-6a0e-4d47-ab42-2a88570a3a66)

**Comment by grishka** [comment]
A new or updated filter doesn't apply to any posts that were already loaded. You need to refresh the corresponding timeline.

**Comment by thecrazything** [comment]
This filter is months old.
