### ISSUE TITLE
Timeout too short to load long threads

### ISSUE THREAD

**Issue by box-dev** [mastodon/mastodon-android#751]
Due to the time it takes for long threads to load, it can be impossible to open them because they always timeout. The web front end has the same slow speed but does not time out so is less of a problem, but the app is just too 'impatient'. 

An example long thread: 
https://mastodon.social/@dungeons/111482971553327055

This not only means you can't scroll back to previous posts in the threads - it also means you cannot view replies to the post itself because it all times out.

Steps to reproduce:
1. Open above post using the Android app.
2. Try to view replies or previous posts in the thread.

What should happen: at the very least it would be nice to see replies, as particularly with that Dungeons bot being unable to see replies takes away some of the fun from people posting comments about the game as it progresses through the polls.

What does happen: The only way to properly interact with long threads is to open in browser or I suppose use a different app.

**Comment by grishka** [comment]
Then it makes sense to increase that to 30. I thought the default was 30.
