### ISSUE TITLE
Add Georgian language to the Crowdin project

### ISSUE THREAD

**Issue by DraganRatkovich** [mastodon/mastodon-android#754]
Please add Georgian for Android on Crowdin to start translating.

**Comment by grishka** [comment]
Added

**Comment by DraganRatkovich** [comment]
@grishka Is there a translation approval system for Mastodon? If so. let me know if any person is appointed as Georgian language proofreader/translator and if not, give me that role to approve Android translations.

**Comment by grishka** [comment]
> Is there a translation approval system for Mastodon?

No, there isn't one. I myself sometimes review and fix the Russian translation, because that's my native language, but that's it.
