### ISSUE TITLE
Too bright/dark highlight color on some devices. (Material You related?)

### ISSUE THREAD

**Issue by AmionSky** [mastodon/mastodon-android#767]
The color that's used when you tap a post (or some other UI elements) feels way too strong/high contrast from what it should be. It's been like this since the Material You redesign so I thought it's just an odd design choice, but recently I took out my old phone and noticed that the colors look good on it. I tried changing the material colors in the system in case it was just a wrong color scheme but it didn't fix the issue (it's always too bright/dark).

Too bright/dark colors on Samsung Galaxy S23 (Android 14):
S23 Dark             |  S23 Light
:-------------------------:|:-------------------------:
![S23 Dark](https://github.com/mastodon/mastodon-android/assets/13593262/b6238244-5140-426c-a6aa-6a33da57ffa7) | ![S23 Light](https://github.com/mastodon/mastodon-android/assets/13593262/4b2305dd-e8bb-42f9-9b0e-5269b57cd1fd)

The "correct" colors on Samsung Galaxy A3 2017 (LineageOS 17.1 - Android 10):
A3 Dark             | A3 Light
:-------------------------:|:-------------------------:
![A3 Dark](https://github.com/mastodon/mastodon-android/assets/13593262/416dcd73-51ff-4400-bd89-69dc54ace721) | ![A3 Light](https://github.com/mastodon/mastodon-android/assets/13593262/a5d59157-5575-42c2-bcdf-28bf31ccf5d8)

**Comment by grishka** [comment]
So they did fix RippleDrawable on Android 14, after all?
