### ISSUE TITLE
[Feature Request] Translation

### ISSUE THREAD

**Issue by Offbeatmammal** [mastodon/mastodon-android#768]
One of the great things about Mastodon is it's very international, but that does mean I encounter a lot of toots (especially in replies) that I can't read (unless I copy and paste into a translation service). Would be great to have inline translate options.

I can foresee issues with selecting a scalable and accurate translation service with a low enough cost to be practical

**Comment by grishka** [comment]
It already exists
![Screenshot_20240120-132802](https://github.com/mastodon/mastodon-android/assets/1478258/63d19fd7-cd35-4757-bcb9-8914bbfe2e74)
