### ISSUE TITLE
Crash when switching post language

### ISSUE THREAD

**Issue by AlphaCraft9658** [mastodon/mastodon-android#770]
When I create a new post, change the posts language and then open the menu again, the entire app crashes.
Here is a url to the generated crash log:
https://paste.crdroid.net/tJR5a6

**Comment by AlphaCraft9658** [comment]
Oops.

**Comment by grishka** [comment]
> at androidx.lifecycle.c0.b(SourceFile:30)

Are you sure this is the right crash log? There's no such library in this app.

**Comment by AlphaCraft9658** [comment]
> > at androidx.lifecycle.c0.b(SourceFile:30)
> 
> Are you sure this is the right crash log? There's no such library in this app.
> 
> edit: definitely wrong one
> 
> > Unable to create application com.pairip.application.Application

You're right. That must be the ChatGPT crash log then. My system doesn't even give me a popup telling me that Mastodon crashed. I'll try giving a log from Matlog filtered by the word mastodon. Additionally, this crash only happens when selecting the suggested detected language based on the post content and then trying to open the menu again.

**Comment by AlphaCraft9658** [comment]
> > at androidx.lifecycle.c0.b(SourceFile:30)
> 
> Are you sure this is the right crash log? There's no such library in this app.
> 
> edit: definitely wrong one
> 
> > Unable to create application com.pairip.application.Application

Here is the correct log:
https://gist.github.com/AlphaCraft9658/bf6cc5b03804f7edc4aa594af27f430f

It's a log of a full session until the crash happens.

**Comment by grishka** [comment]
There are many lines missing from the log 🤔
Like there's only 2 lines about the actual crash and only one of them is part of the stack trace.

**Comment by grishka** [comment]
If you were grepping for `org.joinmastodon.android`, don't do that, grep for `AndroidRuntime` instead

**Comment by AlphaCraft9658** [comment]
> If you were grepping for `org.joinmastodon.android`, don't do that, grep for `AndroidRuntime` instead

I have a new log now.
https://gist.github.com/AlphaCraft9658/a4eead79b713dfe10d779f02bf52e69f
