### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [mastodon/mastodon-android#777]
My [recently enhanced scanner](https://gitlab.com/IzzyOnDroid/repo/-/issues/475) just reported on yesterday's update of your app:

```
! repo/org.joinmastodon.android_84.apk declares sensitive permission(s):
  android.permission.REQUEST_INSTALL_PACKAGES android.permission.READ_EXTERNAL_STORAGE*
! repo/org.joinmastodon.android_84.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

`READ_EXTERNAL_STORAGE` is granted implicitly (indicated by the trailing `*`) due to `WRITE_EXTERNAL_STORAGE`. Could you please clarify what this is needed for? Further, and much more problematic is `REQUEST_INSTALL_PACKAGES`; what apps are you installing there?

As for the `DEPENDENCY_INFO_BLOCK`, that's easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Thanks in advance!

**Comment by grishka** [comment]
> READ_EXTERNAL_STORAGE is granted implicitly (indicated by the trailing *) due to WRITE_EXTERNAL_STORAGE. Could you please clarify what this is needed for?

For saving images from the media viewer. The image is already cached so I just copy it to the external storage from my cache to avoid downloading it a second time. I don't ever use or request READ_EXTERNAL_STORAGE.

> Further, and much more problematic is REQUEST_INSTALL_PACKAGES; what apps are you installing there?

App's own updates. Only added for `githubRelease`/`githubDebug` flavors.

> For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

What's the point of it being a thing then? 🤔

**Comment by IzzySoft** [comment]
Thanks @grishka – and apologies for the late reply: it seems GH loses some notifications :cry:

* r/w storage: Thanks, set accordingly here

> App's own updates. Only added for `githubRelease`/`githubDebug` flavors.

Is there an APK available without that self-updater? Like in F-Droid, the inclusion policy in my repo speaks against those.

> What's the point of it being a thing then?

You'll have to ask Google, it's signed with their key. Probably something something proprietary-issue-with-Playstore, idk. Apart from Google, nobody can even read it anyway. So being a proprietary blob, it should rather not be inside a FOSS APK :wink: (there's even more to those blobs, but that goes beyond this issue here).

**Comment by grishka** [comment]
> Is there an APK available without that self-updater? Like in F-Droid, the inclusion policy in my repo speaks against those.

Yes, just build the `release` flavor. The self-updater is the only difference between `release` and `githubRelease`.

**Comment by IzzySoft** [comment]
You forget that i just run a binary repo. No build environment here. So I need to grab the APK from you.

**Comment by grishka** [comment]
Oof. Well, I plan to setup a CI pipeline eventually, so you'll be able to grab apks from there. Probably even eutomatically. In the meantime, here's the latest one:
[mastodon-release.apk.zip](https://github.com/mastodon/mastodon-android/files/14398702/mastodon-release.apk.zip)

**Comment by IzzySoft** [comment]
Thanks @grishka – but my updater cannot grab from pipelines. It can grab from releases, from a directory inside the repo – or from "fixed URLs" (which may redirect to the real one). So maybe your CI/release workflow could include that APK with releases?

**Comment by grishka** [comment]
> So maybe your CI/release workflow could include that APK with releases?

I deliberately don't want to make a `release` apk easily available to users because then, not knowing the difference between flavors, they will install it and get stuck on that version because there's no self-updater.

**Comment by IzzySoft** [comment]
Understood. Then maybe I remove it from my repo and F-Droid users have to rely on F-Droid.org instead (including the delayed updates)? Alternatively you could make the updater opt-in (if it isn't already): have a bool option for that (initially `null`), when `null` ask whether to enable, then store (and allow changing via settings) – including proper explanations? You know, "informed and explicit consent" and all that :wink: Giving you an example from a different app:

[<img src="https://github.com/mastodon/mastodon-android/assets/6781438/7f70fab5-b8bf-4a2e-a9ab-18ffde2c159d" alt="01_enable_update_check" width="250">](https://github.com/mastodon/mastodon-android/assets/6781438/7f70fab5-b8bf-4a2e-a9ab-18ffde2c159d) [<img src="https://github.com/mastodon/mastodon-android/assets/6781438/63982517-233a-4249-bba2-f69ecb8e01ef" alt="02_update_action" width="250">](https://github.com/mastodon/mastodon-android/assets/6781438/63982517-233a-4249-bba2-f69ecb8e01ef)

**Comment by grishka** [comment]
> Then maybe I remove it from my repo and F-Droid users have to rely on F-Droid.org instead (including the delayed updates)?

That would be cumbersome. If you need a fixed URL, I can set up an endpoint on my personal server that would redirect to the apk from the latest CI run (and maybe move it to joinmastodon.org later, I will need to ask the team). Will that work?

> Alternatively you could make the updater opt-in (if it isn't already)

I'm not sure how to properly integrate that into the UI. I **definitely** don't want a modal that pops up by itself like on your screenshots. Forcefully diverting user's attention like that is one of the worst UX sins for me. Besides, there isn't the usual "they may track you" concern, it's just an unauthenticated GitHub API request. If I were to make a setting for that, it would be opt-out.

**Comment by IzzySoft** [comment]
> If you need a fixed URL, I can set up an endpoint on my personal server that would redirect to the apk from the latest CI run (and maybe move it to joinmastodon.org later, I will need to ask the team). Will that work?

Sure, that would work fine – provided the fixed URL also sends a `LAST_MODIFIED` header.

> Besides, there isn't the usual "they may track you" concern, it's just an unauthenticated GitHub API request

It's not so much the tracking part there, though that also plays into it. Those "side-loaded" updates would bypass all scans performed in my repo – which are not done because I mistrust you, but because everybody can miss something.

> If I were to make a setting for that, it would be opt-out.

Which would not be compatible with the inclusion criteria on either F-Droid or my repo. But as said above: a fixed URL providing the last-modified flag would do for me, even long-term if needed. It just needs to be "stable" then: should it disappear, I have no idea where to look – while at releases here I could see at least if the file is gone or just the naming pattern changed :wink: But as I can reach you here in such a case, this would be a good compromise for both of us I'd say?

**Comment by grishka** [comment]
I got CI working: https://github.com/mastodon/mastodon-android/actions/runs/8117973419

But apparently, it isn't possible to download artifacts as-is. They are put into zip archives even if it's just a single file *because reasons*. See actions/upload-artifact#14
The API [doesn't allow it either](https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28#download-an-artifact):
>  The :archive_format must be zip.

Are you okay with having to extract the apk from a zip archive?

**Comment by IzzySoft** [comment]
> Are you okay with having to extract the apk from a zip archive?

My updater does not support that unfortunately. But a quick search on "github workflow release apk" returns some interesting results, maybe you could use one of those? [example 1](https://gist.github.com/alexanderbazo/227476190ef5ab655795e34ec0d314d6), [example 2](https://github.com/marketplace/actions/build-android-release-apk-when-create-new-tag), [step-by-step guide](https://proandroiddev.com/create-android-release-using-github-actions-c052006f6b0b?gi=5fc04f3bc4bc)

**Comment by grishka** [comment]
This puts it into releases, which is something I explicitly don't want. I don't want to make non-self-updating apks easily available to users because they will install them and then get stuck on that version. This is why only `githubRelease` ones go there.

I suppose I can have a cron job on my server that would periodically check for new CI artifacts and download and unzip them if there are any.

**Comment by IzzySoft** [comment]
> This puts it into releases

I saw that. But not being familiar with Github actions/CI I thought maybe that step could be replaced somehow :cry:

> I don't want to make non-self-updating apks easily available to users because they will install them and then get stuck on that version.

That could happen via the F-Droid website (or mine) then as well – though it's less likely there than it might be with the Github releases page, yeah… Thanks for looking into a viable approach, @grishka!

**Comment by grishka** [comment]
> That could happen via the F-Droid website (or mine) then as well

The idea is that because F-Droid manages updates for apps it installed, it's perfectly fine to have a non-self-updating apk *there*.

**Comment by IzzySoft** [comment]
Sure, got that. Same with my repo :wink:

**Comment by IzzySoft** [comment]
Shall I disable automatic update checks in my repo then until the final link becomes available? Else the APK would be replaced from here should you make a new release. Won't happen of course if I put the new one into the repo before it shows up here.

Oof. Cannot download via `wget` as that seems to be some JavaScript circus. Have to click the link in the browser, store locally, then go where it's stored, unzip, then push the file over… OK, have replaced it now, thanks!

**Comment by IzzySoft** [comment]
@grishka ^^ (just in case the notification didn't reach you – looks like several got lost for me and others as well).

**Comment by grishka** [comment]
> Shall I disable automatic update checks in my repo then until the final link becomes available?

Yes, it would make sense

**Comment by IzzySoft** [comment]
To not fall back too far, I've set it to "Static" now (which means "monthly checks" instead of "daily checks" of my updater). So the next check would be in 14 days from now (static run is on the 1st of each month around 2 am UTC).

Does that give you sufficient time? I just want to ensure my repo doesn't "fall too much behind" should this issue be "forgotten" (buried in the heap of work).

**Comment by grishka** [comment]
Yes

**Comment by grishka** [comment]
GitHub's API documentation seems to contradict reality 🤔
![Снимок экрана 2024-03-18 в 21 59 05](https://github.com/mastodon/mastodon-android/assets/1478258/4db52430-dcc1-431f-965e-17522e7a6f2a)
![Снимок экрана 2024-03-18 в 21 59 25](https://github.com/mastodon/mastodon-android/assets/1478258/31fd7d03-7769-430a-a502-8e6a6b31bf5c)

**Comment by grishka** [comment]
So apparently this is a "known issue" that's been ignored for 4 years... yikes.
actions/upload-artifact/51

**Comment by IzzySoft** [comment]
Like several others :cry: There are still notifications lost. Releases disappear (you can see them when you have the URL, but they are not listed at the release page; you can reach them via their tags, though; this happens when you delete a release and re-create it with the same name, in some cases)…

**Comment by IzzySoft** [comment]
@grishka just seeing this issue is still open. May I ask what the status is? There was an update in May (so not sure if "Static" shall still apply), but `REQUEST_INSTALL_PACKAGES` is still there.

**Comment by grishka** [comment]
> but REQUEST_INSTALL_PACKAGES is still there.

Where? It is in the `githubRelease` flavor because it needs to be able to update itself. I can't remove it from there.

**Comment by grishka** [comment]
I submitted a bug report to GitHub about that artifact download endpoint requiring authentication.

**Comment by IzzySoft** [comment]
Thanks! Hope we can get that alternative download working.

**Comment by IzzySoft** [comment]
Yuck, warning popped up again. Any chance we can get this solved, @grishka? I cannot keep it up forever this way as it violates the inclusion criteria. Afraid next time I'll have to disable/remove the app :cry:

**Comment by grishka** [comment]
Here's the last response I got from GitHub support:

> Hi Gregory,
>
>Thanks for confirming.
>
>I agree that this is unexpected behaviour, so I'll escalate this and get the documentation updated accordingly too.
>
>I'll keep you posted with any updates, but if there's anything else you need in the meantime just let me know.
>
>Kind regards, 
Dan | GitHub Support Engineer

Maybe I should research request authentication. Maybe they have some sort of non-personal token that only grants read access to public data.

**Comment by IzzySoft** [comment]
Thanks @grishka – and I'll keep my :crossed_fingers: Nasty situation…

**Comment by grishka** [comment]
Okay, I managed to get it working. I didn't get the token scopes right the first time because the layout of that form is so confusing.

The always-latest apk is at https://grishka.me/uploads/mastodon-release-latest.apk, the update-checking script runs twice a day.

**Comment by IzzySoft** [comment]
Thanks so much, @grishka – that worked out fantastic! I've adjusted the config to pick the APK from there, making sure Fastlane is still checked from here, manually triggered an update – and all went smooth. `REQUEST_INSTALL_PACKAGES` is gone, the blob was already gone before, so all is solved now :star_struck: Closing the issue then.

**Comment by IzzySoft** [comment]
@grishka sorry for jumping on this old thread again. I was just looking if we could not switch to the APK from the releases here as well, which F-Droid uses, too (as we have deprecated "direct-link" downloads; they still work for existing apps, but we're sunsetting this). Then the APK we ship could also be marked "reproducible" (we'd confirm that via [our own builders](https://codeberg.org/IzzyOnDroid/rbtlog), of course, which then would be possible.

Diffing the 2 APKs turns up, as to be expected:

```diff
   <uses-sdk android:minSdkVersion="23" android:targetSdkVersion="37"/>
+  <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>
   <uses-permission android:name="android.permission.INTERNET"/>
   <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
   <uses-permission android:name="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK"/>
@@ -29,6 +30,7 @@
     </intent>
   </queries>
   <application android:theme="@7F110007" android:label="@7F10001B" android:icon="@7F0E0000" android:name="org.joinmastodon.android.MastodonApp" android:allowBackup="true" android:largeHeap="true" android:supportsRtl="true" android:extrac
+    <provider android:name="org.joinmastodon.android.updater.SelfUpdateContentProvider" android:exported="false" android:authorities="org.joinmastodon.android.self_update_provider" android:grantUriPermissions="true"/>
     <meta-data android:name="com.google.mlkit.vision.DEPENDENCIES" android:value="barcode_ui"/>
```

Wouldn't that be [against F-Droid's policy](https://f-droid.org/en/docs/Inclusion_Policy/#:~:text=inclusion%2E-,Applications,it,-%2E) as well, @licaon-kter @linsui ? So maybe you could turn this special build into a build flavor, and attach the `fdroid` release here as well (for both, F-Droid _and_ IzzyOnDroid, to use)?

**Comment by linsui** [comment]
So... if a versioned url to the apk can be provided, we can re-enable reproducible build along with the apks signed by our key.

**Comment by IzzySoft** [comment]
To just have the current one versioned _at the same place_ (replacing the current link), would break it for IzzyOnDroid, though – we only support "versioned" by means of "being attached to the corresponding release". Naming patterns at the release must just be "match-able" by a regular expression (as the version is already clear by the name of the tag/release). So if it were e.g. named `this-would-make-your-device-explode.apk` (to keep folks from downloading it), that would be no issue: we could simply match `/this.*explode\.apk/` and be fine.

**Comment by grishka** [comment]
Yeah, the `githubRelease` flavor includes the self-updating functionality, that's the only reason for it to exist. If you want an apk without that, that's the `release` flavor.

I can't add `release` apks to GitHub releases because then people will inevitably download them and get stuck on that version. It would be nice if you could grab them from CI artifacts.

**Comment by IzzySoft** [comment]
Thanks for your swift response, @grishka! Unfortunately, F-Droid needs the URL to be "matchable" via either `versionCode` or `versionName` (or both) – something artifacts do not support. IzzyOnDroid needs them at the related tag/release (Mastodon is one of the currently 2 remaining apps still using "direct links to a fixed URL", a feature we already deprecated and hope to drop soon™).

I understand your fears regarding "stuck on that version" – which is why I mentioned "discouraging file names". Would maybe a (self-hosted) mirror (e.g. using Forgejo) be an option? Being self-hosted, would mean most people would "never find it" (because it's not on ~Facebook or Google~ Github, for some people it simply does not exist). Having the code mirrored there (e.g. via an "on-tag" and/or "on-push" action), and the APKs attached there, would work for all of us, I guess? And of course no problem with having Issues, PRs, etc disabled in that mirror.

This would give the official Mastodon client the additional plus of being "verified" as Reproducible Build by multiple 3rd parties (here: F-Droid, IzzyOnDroid, plus (hopefully) also IoD's "independent builders" run by people outside of all teams mentioned). I'm pretty sure it is RB; Moshinda (a fork) is as well, and the official client at least was at F-Droid, at one point.

**Comment by grishka** [comment]
I'm unwilling to spend any extra effort on this from my side, but *especially* anything that would require me to perform extra actions every time I release an update, for the rest of eternity.

What is the software that pulls in these updates? Can't it be modified to add support for GitHub artifacts? That would make life easier not just for me, but potentially for anyone who wants their app on F-Droid but doesn't want their users to require the use of something like Obtainium. I'd even volunteer to make a PR if whoever maintains it has no resources for that, just to get this sorted once and for all.
