### ISSUE TITLE
Android Push Notifications not working.

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#779]
Hello. I changed to the new update a few minutes after released, but from the next day on the app is not sending more push notifications at all. 
1. I have checked all permissions,
2. I have uninstalled and installed the app, 
3. I have downgraded and upgraded Google Play Services on purpose, 
4. I have cleaned the whole mobile cache,
5. I have even tried both forks Megalodon/ Moshidon resulting in the same behavior...

with no success.

It has never happened to me before.

My cellphone is a Redmi 9A running Android 11.

**Comment by renchap** [comment]
Can you share what is your Mastodon account?

**Comment by grishka** [comment]
Did you install any system updates or change any battery-related settings recently? Xiaomi phones are [among the worst offenders](https://dontkillmyapp.com/xiaomi) at killing apps so hard they can't even receive FCM notifications.

Or, yes, it might be a server issue.

**Comment by jotaluissoy** [comment]
Issues are the same with the following instances:
mastodon.social (my favorite one)
mastodon.la
tuiter.rocks
mast.lat
cc. @renchap

**Comment by jotaluissoy** [comment]
Hi. Having restored my device to factory value, the issue is done. It seems a malware or an annoying disruption broke Chrome browser and Mastodon website&app push notifications. I think I may close my report as I apologize for taking your time.
Thanks.
