### ISSUE TITLE
Enhancement: Bazel Build Migration

### ISSUE THREAD

**Issue by AbdhilahiRWabwire** [mastodon/mastodon-android#783]
# Bazel Build

- I would like to migrate this project from Gradle to Bazel Build. 

-  How the team would feel about me implementing this enhancement in my fork?

- Examples: https://github.com/bazelbuild/rules_kotlin/tree/master/examples

**Comment by Gargron** [comment]
We are not looking to change our team's workflow at the moment, thank you.

**Comment by AbdhilahiRWabwire** [comment]
Let me know if you ever change your mind in the future.
