### ISSUE TITLE
F-droid has an old version (v. 2.2.4)

### ISSUE THREAD

**Issue by Mr-Bajs** [mastodon/mastodon-android#785]
The F-droid version is a rather old version 2.4.4, why is that? Are F-droid support abandoned?

https://f-droid.org/en/packages/org.joinmastodon.android/

**Comment by grishka** [comment]
We don't manage F-Droid builds. That's a question for @licaon-kter and @linsui

**Comment by licaon-kter** [comment]
@Mr-Bajs have you read https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client yet?

&

https://floss.social/@fdroidorg/112023405602612085

/close this

**Comment by licaon-kter** [comment]
There was no months delay, what do you mean? 2.2.4 is from November 2023... 2.3.0 is from a couple of days ago...

**Comment by linsui** [comment]
Nothing happens... 2.3.0 and 2.4.0 have been built and will be published in few days. F-Droid is just slow and this is a normal delay.
