### ISSUE TITLE
Play store app defect

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#787]
### Steps to reproduce the problem

Download app in app store

Enter server at login

App cannot retrieve server info

### Expected behaviour

App should have opened after I entered server info

### Actual behaviour

App cannot retrieve server info

### Detailed description

The Mastodon app in the play store cannot retrieve server info when trying to login.
I've tried to enter other servers but had same result.
This happened about a week ago which made me download the web app version.

Not sure if Android issue

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by Gargron** [comment]
It may be relevant what server you’re trying to connect to.

**Comment by tenebrios** [comment]
> It may be relevant what server you’re trying to connect to.

I tried a few other servers that I'm not on. It didn't retrieve them either

**Comment by Gargron** [comment]
To investigate the issue we need to be able to reproduce it locally. For that we need as many details as possible. Which server you have tried, which app version, which Android version, which device model.

**Comment by tenebrios** [comment]
> To investigate the issue we need to be able to reproduce it locally. For that we need as many details as possible. Which server you have tried, which app version, which Android version, which device model.

I took a few photos 
As for the phone type, it is a Samsung galaxy a14
I never get further then the 4th photo...


![Screenshot_20240304_132211_Mastodon](https://github.com/mastodon/mastodon-android/assets/161815189/c25285c7-6405-46bc-8866-4795bf8e64c8)
![Screenshot_20240304_132250_Mastodon](https://github.com/mastodon/mastodon-android/assets/161815189/887853e7-c6fb-41e5-a0b8-c771821e80a3)
![Screenshot_20240304_114617_Mastodon](https://github.com/mastodon/mastodon-android/assets/161815189/21a19a32-b074-4c35-b6ef-dbf98fb8be0c)
![Screenshot_20240304_121929_Chrome](https://github.com/mastodon/mastodon-android/assets/161815189/89145292-7cfa-45f5-a269-5654f928117d)

**Comment by grishka** [comment]
So what happens when you tap "authorize"?

**Comment by tenebrios** [comment]
> So what happens when you tap "authorize"?

Nothing at all
It just stays there

**Comment by jotaluissoy** [comment]
If this may help, that has happened to me several times with different app versions and the cause is only one, low connectivity. Asap internet speed gets better, everything works perfectly.

**Comment by tenebrios** [comment]
> If this may help, that has happened to me several times with different app versions and the cause is only one, low connectivity. Asap internet speed gets better, everything works perfectly.

My connection seems to be fine.
All other apps work fine
Why wouldn't that one in particular?
I've been using the "web app" version and that's working fine.
I think it's something else with the app in the store

**Comment by grishka** [comment]
What is your default web browser? Does it have a setting to not open links in apps, and if so, what is it set to? The app relies on a custom URL scheme for authentication.

**Comment by tenebrios** [comment]
> What is your default web browser? Does it have a setting to not open links in apps, and if so, what is it set to? The app relies on a custom URL scheme for authentication.

Browser is Google
I was able to use the app last week.
I open links on other apps so I don't think that's the problem. 

On a side note, I made a suggestion about there being a setting to make it do others can't download  posts.
I made a few suggestions the other day.
What does it take to have these suggestions actually come to fruition?

I was involved with helping another app by giving them suggestions and they banged them out fairly quickly.
Here I see that people requested things 5 years ago like polls being able to have photos as options and it hasn't been implemented. 
Do things actually happen?

**Comment by Gargron** [comment]
You can see the changelog by either viewing the "releases" page, or by browsing the commit history on the main page of the repository. We appreciate all feedback but we cannot guarantee that any particular suggestion will be "banged out" in any specific time frame, or even at all, depending on how it fits with the needs of the other users and overall vision for the product.

**Comment by tenebrios** [comment]
> You can see the changelog by either viewing the "releases" page, or by browsing the commit history on the main page of the repository. We appreciate all feedback but we cannot guarantee that any particular suggestion will be "banged out" in any specific time frame, or even at all, depending on how it fits with the needs of the other users and overall vision for the product.

Something like photos being added to polls is something that the majority seems to want.
That request was 5 years ago.
So what happened there?

**Comment by tenebrios** [comment]
> You can see the changelog by either viewing the "releases" page, or by browsing the commit history on the main page of the repository. We appreciate all feedback but we cannot guarantee that any particular suggestion will be "banged out" in any specific time frame, or even at all, depending on how it fits with the needs of the other users and overall vision for the product.

As far as the other app "banging changes out", they absolutely did do that. I would say it took them a few months to add things to updates.
They want their app to be a success.
Does Mastodon want to be a success?
It could be but there's things about it that don't make it user friendly...and it's basic things that could change all that.
For example:
The stats don't appear under posts when scrolling a page. They absolutely should show so that others can see if a page is busy or not.
A setting to make it so others can't download your posts.
Post comment bumping.
No more 500 character limit
Fixing the featured tags feature so it works correctly and make the list unlimited.

These are all simple things that would drastically improve things here.
