### ISSUE TITLE
Recent GitHub version 2.4.1 crashes at start

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#789]
Having installed the newest recent version from GitHub (2.4.1) it immediately crashes at the start first second .

Redmi 9A
Android 11

**Comment by grishka** [comment]
Thank you very much for noticing this!
![FD9sV40VQAw72Qu](https://github.com/mastodon/mastodon-android/assets/1478258/11b7fd8a-aa13-4cf2-8210-ecc77f60922a)

**Comment by jotaluissoy** [comment]
Thank youuuuu for fixing it‼️
