### ISSUE TITLE
"Always expand posts marked with content warnings" not honored

### ISSUE THREAD

**Issue by uusijani** [mastodon/mastodon-android#797]
I have "Always expand posts marked with content warnings" on in my settings, but CW-marked posts in the Android app still show as unexpanded.

I'm fairly sure this used to work until recently, and #87 being closed as "completed" back in October would imply I wasn't just imagining it.

**Comment by grishka** [comment]
The setting in the app is not synced with the one on the server. You have to enable it in the app separately.

**Comment by uusijani** [comment]
Ah, apparently "Show content warnings" on the app is the opposite of what's "Always expand posts marked with content warnings" in the web UI. I was confused because the former refers to the **warning**, whereas the latter refers to the **content**. There may be minor usability issue there, but I'll leave it out of this one.

Sorry for the noise. To make up for it, #290 looks like a duplicate of this one and thus could possibly also be closed.
