### ISSUE TITLE
Profile pinned post location

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#800]
Are profile pinned posts supposed to appear under the featured hashtag tab or are they supposed to appear as the first post on the profile feed?

As of now "on the app store app version" my pinned post is appearing under the featured hashtag tab whereas on the web app, the pinned post appears as the 1st post on my profile feed.

Could this be causing the app to be glitchy?
Something is off with pinned posts on the app.

Again, I am an android user and the server is mastodon.social 
![Screenshot_20240313_145701_Mastodon](https://github.com/mastodon/mastodon-android/assets/161815189/87219095-c5ae-459d-bc6e-de305640a1f9)

**Comment by tenebrios** [comment]
As side note, the web app does not have the featured hashtag tab and it is very much needed there

**Comment by tenebrios** [comment]
Will the pinned post appear pinned to the top of the timeline?

**Comment by andypiper** [comment]
This issue is now closed.
