### ISSUE TITLE
Mastodon.social app login

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#801]
It takes a VERY long time for the apo to retrieve the Mastodon.social server info when trying to login through the app.

It doesn't appear to be like this with other servers.

After I finally get on the server, I'm only on for a few minutes before the dial starts spinning and I can't do anything.
Trying to log out even takes time. 

Is this an android issue?
What can be causing this?

**Comment by tenebrios** [comment]
The dial spins for a long time before it finally retrieves the server
This doesn't happen with other servers.
What is wrong with this server?


![Screenshot_20240313_162041_Mastodon](https://github.com/mastodon/mastodon-android/assets/161815189/0346402a-5dbd-45ad-a0ad-963eb370ec06)

**Comment by tenebrios** [comment]
It took 20 minutes or so to get to this point.
Now the dial continues to spin 
![Screenshot_20240313_172641_Mastodon](https://github.com/mastodon/mastodon-android/assets/161815189/a4178871-138e-42fa-b522-e30a425d527d)

**Comment by tenebrios** [comment]
I Finally got on the app.
I went to my featured tag list, pressed on one of the tags to open it and the app closed out

**Comment by jotaluissoy** [comment]
It usually happens to me with all servers if I am under low connectivity. If it is good, everything works perfectly.

**Comment by tenebrios** [comment]
> It usually happens to me with all servers if I am under low connectivity. If it is good, everything works perfectly.

Connectivity is fine.
For me it only happens with mastodon.social 
How can this be fixed?
I'd like to be able to use the app over the web app

**Comment by jotaluissoy** [comment]
> > It usually happens to me with all servers if I am under low connectivity. If it is good, everything works perfectly.
> 
> Connectivity is fine. For me it only happens with mastodon.social How can this be fixed? I'd like to be able to use the app over the web app

I wish I could help you, but I'm only a simple user.
