### ISSUE TITLE
Please fix featured hashtags glitch 

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#821]
I already made a post about this.
Please refer to that
Thanks

**Comment by Gargron** [comment]
If you've already opened an issue, you do not have to open a second issue. Thank you for your feedback.

**Comment by tenebrios** [comment]
> If you've already opened an issue, you do not have to open a second issue. Thank you for your feedback.

Ok
Just doing what I can to see that some of these issues get resolved. 
Polls not having photo options is another one very much needing a fix.
That poll issue was brought up a number of years ago and nothing has happened with it.

**Comment by andypiper** [comment]
@tenebrios please do not use the issue tracker like this. If issues have been raised previously then we are already aware of them. If there is *new* information to add to an existing issue then you could do that; if not, then this is not adding useful data to our troubleshooting and diagnosis.


On the other point you make - “polls not having photo options” would be a feature request, not an issue or something that needs to be “fixed”. If and when this is something that is prioritised as something to add to Mastodon, it will be worked on. At the moment, this is not something that is near top of the list. There are a vast range of things that we could work on, and we need to choose the most important things to spend the limited time and resources that we have available at any point in time.

We appreciate your passion for the project and the platform but please help us by only raising an issue if you have useful data. Thank you.

**Comment by tenebrios** [comment]
> @tenebrios please do not use the issue tracker like this. If issues have been raised previously then we are already aware of them. If there is _new_ information to add to an existing issue then you could do that; if not, then this is not adding useful data to our troubleshooting and diagnosis.
> 
> On the other point you make - “polls not having photo options” would be a feature request, not an issue or something that needs to be “fixed”. If and when this is something that is prioritised as something to add to Mastodon, it will be worked on. At the moment, this is not something that is near top of the list. There are a vast range of things that we could work on, and we need to choose the most important things to spend the limited time and resources that we have available at any point in time.
> 
> We appreciate your passion for the project and the platform but please help us by only raising an issue if you have useful data. Thank you.

Sounds good
Regarding the featured tags glitch.
When might that be able to be fixed?
I made a post stating the steps to reproduce the bug.

**Comment by tenebrios** [comment]
> If you've already opened an issue, you do not have to open a second issue. Thank you for your feedback.

It's great to reply to the ceo of Mastodon. 
I am curious why fixing this bug would be something that isn't planned.
It closes out the app.
That's not something you want to have fixed?

**Comment by andypiper** [comment]
This issue is closed. You can use #798 to follow progress and any decision to add featured hashtags to the Android app.

**Comment by tenebrios** [comment]
Seems to be fixed now.
App is no longer closing out after pressing view all and trying to open a tag.
Still limited to only 10 tags though.
Would be nice if it was unlimited and not just 10 tags though

**Comment by andypiper** [comment]
Your interest is noted. There are no plans to change this functionality at this time.

**Comment by tenebrios** [comment]
> Your interest is noted. There are no plans to change this functionality at this time.

Ok
Thanks for listening
