### ISSUE TITLE
Lists feature

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#841]
Is the lists feature coming to the app?
I see it is on the web app 
Photo included here

![Screenshot_20240515_193545_Chrome](https://github.com/mastodon/mastodon-android/assets/161815189/424205e1-0e29-4122-bc6a-b49b2a7124eb)

**Comment by andypiper** [comment]
Please do not use GitHub Issues for Q&A.

There is a roadmap [here](https://joinmastodon.org/roadmap).

That is what we have to share at this time.
