### ISSUE TITLE
App takes 30+ seconds to load posts on personal instance

### ISSUE THREAD

**Issue by Voklen** [mastodon/mastodon-android#849]
I used to use the mastodon app with my account at [mastodon.social](https://mastodon.social/@Voklen) but I've recently set up my own server at [social.voklen.com](https://social.voklen.com). This works great and loads fast when I'm using my browser (both on my computer and on my phone), but when I log in through the app it takes 33 seconds loading before showing any posts (even if there have been no new posts at all, my feed isn't very active).

|Setup                  |Time to load|
|-----------------------|------------|
|web + mastodon.social  |instant     |
|web + social.voklen.com|instant     |
|app + mastodon.social  |instant     |
|app + social.voklen.com|~33 seconds  |

I thought it may be related to mastodon/mastodon-ios#904 (even though that was on iOS) so I logged out and reinstalled the app but the issue still persists. I've not made any changes to the server and set it up using the defaults on NixOS. If you need any information or logs I'll be happy to provide them.

- Android version: 13
- Android ROM: LineageOS 20
- Mastodon app version: 2.5.0
- Mastodon server version: 4.2.9

**Comment by grishka** [comment]
There's definitely something odd about your server configuration — my attempt to just load it in a browser timed out:
![Снимок экрана 2024-06-12 в 15 24 05](https://github.com/mastodon/mastodon-android/assets/1478258/a01bf207-9875-4f8e-99fc-7dd960306d90)
No idea what's happening here, but it's odd that the client sends a FIN packet after a ServerHello:
![image](https://github.com/mastodon/mastodon-android/assets/1478258/5ac42c8c-6ec2-4da5-9faf-dde191605389)

**Comment by Voklen** [comment]
I just found out it was a problem with the ipv6 configuration, I removed the AAAA record and it seems to work well now, still taking a bit to update on all devices though. Thank you for the quick response and sorry for all the noise!

**Comment by grishka** [comment]
(that couldn't explain my connection problems, I don't have IPv6 on my home network 👀)
