### ISSUE TITLE
App crash when reporting on Mastodon for Android 

### ISSUE THREAD

**Issue by lipgi** [mastodon/mastodon-android#854]
App crash when reporting a post on Mastodon for Android after updating to version 2.5.2
It crushes all several times I have tried and still works on the web.

**Comment by grishka** [comment]
Please provide a crash log.

If you have a computer with the SDK or adb installed: just plug your phone in with USB debugging enabled and run `adb logcat | grep AndroidRuntime`

If you don't: 
1. Unlock developer settings by tapping "build number" 10 times, it's somewhere in "about this device" in settings, the exact location varies depending on OEM skin
2. Shortly after the crash, tap "take bug report"
3. The bug report will be generated in the background. You will receive a notification when it's ready
4. Send it somewhere to yourself
5. Unpack the zip archive, open the (huge) text file and search for, for example, `FATAL EXCEPTION`, copy the stack trace

**Comment by grishka** [comment]
Yes, it's okay, I've also seen this crash in Google Play
