### ISSUE TITLE
Mastodon crashes on startup

### ISSUE THREAD

**Issue by Coehill** [mastodon/mastodon-android#860]
Since upgrading to version 2.5.4 from F-Droid, the app has crashed on startup.  I have tried clearing the app cache, force stopping it, and restarting my phone. 

Samsung Galaxy S23
Android 14

**Comment by grishka** [comment]
You should update to 2.5.6. Version 2.5.4 was only briefly made available here on GitHub and it's extremely unfortunate that F-Droid picked it up.

**Comment by Coehill** [comment]
> You should update to 2.5.6. Version 2.5.4 was only briefly made available here on GitHub and it's extremely unfortunate that F-Droid picked it up.

Thaks, I'll wait a few days then update Mastodon in F-Droid.

**Comment by grishka** [comment]
It's still there 🤬
![image](https://github.com/mastodon/mastodon-android/assets/1478258/78ef47d7-4fda-414d-92ba-c18e4e0226ef)

@licaon-kter could you please remove this version **RIGHT NOW** and then take your time to release 2.5.6? I've had this already-fixed crash reported to me 3 times today already.

**Comment by Coehill** [comment]
Fixed. 👍
