### ISSUE TITLE
Latest version 2.6.0 crashes immediately after initializing.

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#862]
Having downloaded and installed v.2.6.0 it crashes immediately after initializing. Tried cache deleting first and all data secondly and the same error occurs.

**Comment by jotaluissoy** [comment]
Running Android 11.

**Comment by grishka** [comment]
Do you have a crash log?

**Comment by jotaluissoy** [comment]
Sorry, I don't.

**Comment by grishka** [comment]
I reproduced it myself. It only affects the github build.

**Comment by jotaluissoy** [comment]
Yes. That was exactly what I returned here right now. Googled version is ok.

**Comment by grishka** [comment]
Fixed. I hope. This whole "it crashes on startup" thing is getting rather annoying...

**Comment by jotaluissoy** [comment]
Annoying, but it is okay. 
Feel free to understand things like that may happen more than once, please. Never mind. At the end you will always find the way out to any issue like that...😉
