### ISSUE TITLE
GoToSocial emoji support

### ISSUE THREAD

**Issue by SadmL** [mastodon/mastodon-android#874]
Mastodon client - emoji list is empty

![Screenshot_20240814-103017_Moshidon1](https://github.com/user-attachments/assets/601223d0-2ee2-44da-bc7b-ac94caf70c90)

Husky

![Screenshot_20240814-103025_Husky1](https://github.com/user-attachments/assets/3dd5a58a-3d91-4b86-a992-61b858f60a90)

**Comment by grishka** [comment]
There's no official support for non-Mastodon servers. They may or may not work.

**Comment by SadmL** [comment]
Well, that was expected 🙃
