### ISSUE TITLE
Wrong character size.

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#876]
The menu to select which type of post to send in the app has too long characters and the recent Spanish translation is wrong in the last choice. 
Two attached images to compare:
The first one, the app view.
Second, the web (which is cute and right).

MastodonSocial instance.
The latest app version.
![IMG_20240816_164239](https://github.com/user-attachments/assets/a57de85f-01b1-49f8-a453-f98fca5e0c16)
![IMG_20240816_163223](https://github.com/user-attachments/assets/9d8aae8f-0321-4f8c-a9fc-8d577bd5d257)

**Comment by grishka** [comment]
Is this a good fix for when `sp` is too huge?
![screenshot](https://github.com/user-attachments/assets/1041657b-c9e3-43f9-b883-99fd78dd5955)

**Comment by jotaluissoy** [comment]
Yes, I know. Thanks.
