### ISSUE TITLE
Want to add in-app agents

### ISSUE THREAD

**Issue by YangSuGuo** [mastodon/mastodon-android#877]
Protocol support 
（socks5://127.0.0.1:7890/）or（http...）

**Comment by grishka** [comment]
You mean you want proxy support? It should work if you set the proxy system-wide in wifi and/or APN settings.

**Comment by YangSuGuo** [comment]
The problem was solved, and until then I had no idea what a good solution was! thank you 
(≧∀≦)ゞ👍
