### ISSUE TITLE
Request: show emoji name in toast when long-tapping over them

### ISSUE THREAD

**Issue by AnalogFeelings** [mastodon/mastodon-android#884]
As the title says, apps like Discord implement this and can be very useful for example when adding emojis to your profile.

**Comment by grishka** [comment]
You mean in the server emoji keyboard when composing a new post?

**Comment by AnalogFeelings** [comment]
As well as in places like usernames or profile bios.

**Comment by grishka** [comment]
I'll only add it for the keyboard for now.
