### ISSUE TITLE
Weird squares in bio

### ISSUE THREAD

**Issue by alexanderadam** [mastodon/mastodon-android#890]
**Describe the bug**

In the Android client I'm seeing squares before and after the URL of the Helvetic Ruby bio.
This doesn't happen on iOS or the web view but on the Android app and its forks (i.e. [Moshidon](https://github.com/LucasGGamerM/moshidon/issues/551)).

**To reproduce**

1. Go to https://ruby.social/@helvetic_ruby
2. Have a look at the characters before and after the URL in the bio

**Screenshots and screen recordings**

![Screenshot_20240927-223527.png](https://github.com/user-attachments/assets/95adcb0f-db4b-428b-9d49-c2c2e7c8a24c)

**Version**

Mastodon version: `v2.6.1 (112)`

This happens on a Pixel 8 Pro in Android 14

**Comment by grishka** [comment]
That's U+2029 PARAGRAPH SEPARATOR. I have no idea why Android sometimes decides to render these kinds of characters as squares.

All apps that use Android's native text rendering (browsers don't) are affected. It happens on Tusky as well, for example.
![Screenshot_20240928-090529](https://github.com/user-attachments/assets/2f146f74-9275-4339-b58c-95635ea71c96)

**Comment by alexanderadam** [comment]
I see. I'm not sure whether this was the right place but I [created an Android issue](https://issuetracker.google.com/issues/370150206) for this.
