### ISSUE TITLE
App missing from the Google playstore

### ISSUE THREAD

**Issue by nicekiwi** [mastodon/mastodon-android#891]
The app seems to have been removed from the play store?

**Comment by grishka** [comment]
What do you mean?
![Screenshot_20240929-084620.png](https://github.com/user-attachments/assets/4f4f6da9-c029-4ed7-9d04-4d9a4448a834)

**Comment by nicekiwi** [comment]
Apologies, I was linked here on my phone trying to find the Megalodon Github. I didn't notice the incorrect repo.

**Comment by firescry** [comment]
Does this direct link to the app in Play Store work for you?
[https://play.google.com/store/apps/details?id=org.joinmastodon.android](https://play.google.com/store/apps/details?id=org.joinmastodon.android)
