### ISSUE TITLE
Notifications not working: automatically refresh FCM token?

### ISSUE THREAD

**Issue by tesfabpel** [mastodon/mastodon-android#892]
I have a problem with push notifications not working on the official Android app.
I confirm that my notifications settings are all ON (either in the app, and in the permission settings: app is allowed to use notifications and they are all ON).

After reading #888, it seems the app should request the token every now and then (they suggest every month) and send it to the server for storage and later use. This is because FCM tokens seems to have a validity of 270 days (reading the docs, linked below).

>FCM will only return an invalid token response if a token expired after 270 days or if a client explicitly unregistered.

https://firebase.google.com/docs/cloud-messaging/manage-tokens#ensuring-registration-token-freshness
and in particular,
https://firebase.google.com/docs/cloud-messaging/manage-tokens#update-tokens-on-a-regular-basis

Asking the user to reinstall the app or to wait for an update isn't really a good UX :sweat_smile: ...

PS: They also suggest to remove the stale tokens from the server.

>Maintain token freshness and remove stale tokens. In addition to removing tokens that FCM no longer considers valid, you may want to monitor other signs that tokens have become stale and remove them proactively. This guide discusses some of your options for achieving this.

**Comment by grishka** [comment]
> This is because FCM tokens seems to have a validity of 270 days (reading the docs, linked below).

Oh, I had no idea. Thanks for pointing this out. I'll fix it in the next update.

**Comment by tesfabpel** [comment]
You're welcome! Hopefully it fixes the issues with push notifications. :+1:

**Comment by tesfabpel** [comment]
After the update (Mastodon v2.7.2 (121)), sadly I still can't receive notifications... 
I've also uninstalled the app and cleared the data (from the Android app's settings page).

Is there a way I can debug the issue on my end?

As you can see, everything should be in order:
![mastodon_bug](https://github.com/user-attachments/assets/c7dc1d0f-bf0d-4cb1-b171-a5f5664a1cae)
