### ISSUE TITLE
Receiving Push Notifications in English Language.

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#895]
MastodonSocial, account and device both in Spanish, I've been receiving today (October 3rd) all push notifications in English Language. I tried other instances and it is okay, Spanish as usual.

App version 2.7.0
Android 11
Google Play Services Updated.

**Comment by buerviper** [comment]
I agree. In the app, the main feed is in the selected language (in my case, German), but all notifications in the notifications tab use English.

**Comment by buerviper** [comment]
The notifications tab seems to be even more broken: the "mentions" tab is in the designated language (e.g. German), but the "all" tab is in English.
There seems to be something broken with this tab altogether (see also #897 ) since the last update.

**Comment by buerviper** [comment]
Now (2.7.1) the notifications are a mix of English and German. I also noticed some changed translations - maybe there was a bigger change in the translation files and not everything was correctly changed/applied?

**Comment by jotaluissoy** [comment]
> This is an issue in the backend code, not the mobile app: [mastodon/mastodon#32294](https://github.com/mastodon/mastodon/issues/32294)
> 
> It has been fixed, and will be deployed in the next version.

When will that new version will be available? On Monday as it's been stated before?
