### ISSUE TITLE
Notifications displays last 20 only/cannot force reload

### ISSUE THREAD

**Issue by buerviper** [mastodon/mastodon-android#897]
After the recent update, my notifications are stuck to the most recent 40. When I keep scrolling, it shows the loading symbol, but it never actually loads older notifications.

App Version: 2.7.0 (119)

**Comment by buerviper** [comment]
There seems to be something wrong with the notifications tab altogether. I get (in the app) the notice that I have 2 new notifications, but the "all" tab is not updating, I.e. it does not show the new notificationa. The "mentions" tab, however, shows any new mentions.

**Comment by buerviper** [comment]
Now (2.7.1) it's stuck at 20 for me, so not sure about the number of notifications, but I still cannot update them. Changed the issue title accordingly.

**Comment by buerviper** [comment]
This is still unresolved in 2.7.2 (121) for me. I'm stuck at the most recent 20 notifications and cannot force load. Only way is restarting the app, but then I'm still stuck at 20 most recent notifications.

**Comment by grishka** [comment]
Does the "mark all as read" button not work?

**Comment by grishka** [comment]
Oh, I misunderstood it then. I thought you had an unread counter stuck at 20/40.

Then I have no idea what could be happening here. Which server are you on?

**Comment by buerviper** [comment]
It's happening on any of these:
Mstdn.games
Physchem.science
Botsin.space
Metalhead.club

So it seems universal (to me at least). I can read the notifications just fine on the browser interface.

**Comment by buerviper** [comment]
So just to update, I am now consistently seeing my 20 most recent notifications. I am still unable to reload the tab, and I still cannot load any notification older than my 20 most recent. I though that maybe upgrading the server to 4.3 might have changed the behavior, but it didn''t.

**Comment by grishka** [comment]
> I though that maybe upgrading the server to 4.3 might have changed the behavior, but it didn''t.

It should, it just takes up to a day for the app to become aware that your server was updated and start using the new API.

**Comment by buerviper** [comment]
Confirmed, after roughly 24 hours on Mastodon 4.3, it is working now.
