### ISSUE TITLE
Does not accept GIF keyboard input

### ISSUE THREAD

**Issue by cassidyjames** [mastodon/mastodon-android#90]
When trying to insert a GIF from my keyboard, I get an error, “Mastodon doesn't support image insertion here.” 

![Screenshot_20220427-212812.png](https://user-images.githubusercontent.com/611168/165670747-733b82ae-55c6-44bc-babe-ec6a9192be46.png)

The alternative is to go use another app to search for a GIF, download it, then attach it as an image. Instead, Mastodon should handle that when I attempt to insert a GIF, like Twitter and messaging apps do.

**Comment by grishka** [comment]
It does work for me, always did.

**Comment by cassidyjames** [comment]
For added context, I am on a Pixel 6 on Android 12 with Gboard, the default keyboard, and have tested this with both new posts and replies; I get the same unsupported message in both contexts. I can test on my Pixel 3 with Lineage OS later, but other apps work fine with the GIF keyboard on this phone so it does seem like something may be misconfigured in the app.

**Comment by vwbusguy** [comment]
Interestingly, it half-works on the progressive web app version, though instead of attaching the gif, it just adds a link to the gif in the message.  That's still at least better than what the native Android app does.
