### ISSUE TITLE
Rename Publish button to "Toot!" like on the web version

### ISSUE THREAD

**Issue by d4f5409d** [mastodon/mastodon-android#91]

**Comment by d4f5409d** [comment]
Then what's this![IMG_20220429_133928.jpg](https://user-images.githubusercontent.com/76624594/165937625-8a9ab13c-a62f-4f46-aaac-d5579c78509a.jpg)

**Comment by mkljczk** [comment]
Wow, I thought the *toot* word was removed from the entire UI, but this button still uses it
