### ISSUE TITLE
Notifications still not working in v2.7.3 (123)

### ISSUE THREAD

**Issue by tesfabpel** [mastodon/mastodon-android#910]
Also with v2.7.3 (123).

> @grishka 
> 
> 
> 
> After the update (Mastodon v2.7.2 (121)), sadly I still can't receive notifications... 
> 
> I've also uninstalled the app and cleared the data (from the Android app's settings page).
> 
> 
> 
> Is there a way I can debug the issue on my end?
> 
> 
> 
> As you can see, everything should be in order:
> 
> ![mastodon_bug](https://github.com/user-attachments/assets/c7dc1d0f-bf0d-4cb1-b171-a5f5664a1cae)
> 
> 
> 
> 
> 
>  

 _Originally posted by @tesfabpel in [#892](https://github.com/mastodon/mastodon-android/issues/892#issuecomment-2403469223)_

**Comment by tesfabpel** [comment]
Ok, today I discovered that Mentions do indeed work (I received a push notifications for a Mention).
So maybe it's an issue of "new posts" notifications. 

I'm trying to abandon Twitter and one use case there is to follow News accounts and to set a notification for new posts (not unlike the YouTube's bell for new videos, for example...). This is supported by Mastodon thanks to the bell icon on someone's profile and the notification is indeed working on the server because it is shown on the Notifications tab (under "All" category). The only thing is that maybe this kind of notifications isn't working via FCM Push (either because Mastodon Android doesn't support it or the server doesn't send it).

I don't know if it's an issue of the Android app or the server that hasn't the option set. In the latter case, this bug can indeed be closed.
I don't think I see a relevant / specific category of notifications in the Android's Notifications' settings page for the Mastodon App.

![Image](https://github.com/user-attachments/assets/bfeb779d-6210-424c-adec-36cb9529ba8f)

**Comment by dot166** [comment]
New post notifications are broken for me as well

**Comment by grishka** [comment]
> 'New post' notifications are broken for me as well

I forgot that I needed to update the push notifications code too 🙈
