### ISSUE TITLE
Condensing of hashtags

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#911]
This pertains to the main app store app.
Not the web app.
You have it right on the web app with condensed tags. We also need this on the main app as well

Pages would be visually easier to look at if the tags were condensed.
Some put many tags on a post. It can get quite lengthy.
When scrolling a page and seeing all of these tags, it's a distraction.

Perhaps if there are more than say 3 tags, let's say there are 15 tags.
Just make the post show the 3 tags with the included "and 12 more". You would then click where it says "and 12 more" to view all of the tags.

Example
#red, #green, #blue (and 12 more)

**Comment by tenebrios** [comment]
Is there a plan to implement this?

**Comment by andypiper** [comment]
This issue is now closed.

**Comment by tenebrios** [comment]
> This issue is now closed.

What does that mean?
Will this be implemented in an update?
