### ISSUE TITLE
Follows you date

### ISSUE THREAD

**Issue by tenebrios** [mastodon/mastodon-android#914]
If someone follows you, it only states "follows you" on the upper right corner when we view that person's page.
It would be a good idea if it stated 
"Follows you since (date they followed)".
"Followed you on (date they followed)".

It would give a sense of how long people are following.

**Comment by grishka** [comment]
Could you please stop just pouring your stream of thoughts out into GitHub issues like this? If you want to have a chat with the team, we have a Discord server for that, available to those who donate to Mastodon.

**Comment by tenebrios** [comment]
> Could you please stop just pouring your stream of thoughts out into GitHub issues like this? If you want to have a chat with the team, we have a Discord server for that, available to those who donate to Mastodon.

Who are you exactly?

**Comment by grishka** [comment]
If it's not apparent from the commit history in this repository, I'm the developer who works on this app.

**Comment by tenebrios** [comment]
> If it's not apparent from the commit history in this repository, I'm the developer who works on this app.

Ok well
1. I don't use discord 
2. Someone from here gave me these links. I have a Droid so I used the second one obviously. 
3. It was a server owner that guided me to guthub in regards to making suggestions to improve upon the app. 
4. I've seen a tab for suggestions here...is that not for sugestions?? This tab is where I was making suggestions until that other person provided that link.

**Comment by andypiper** [comment]
As @grishka stated, you *must* stop using GitHub issues for this kind of feedback. 
This is not an appropriate channel.

For a Mastodon platform suggestion you can (for example) use the [Discussions](https://github.com/mastodon/mastodon/discussions) on the main Mastodon repository, or, you could use the Discord channels.

Please also read the [CONTRIBUTING](https://github.com/mastodon/.github/blob/main/CONTRIBUTING.md) and [CODE OF CONDUCT](https://github.com/mastodon/.github/blob/main/CODE_OF_CONDUCT.md) documents.

**Comment by tenebrios** [comment]
Sounds good
Thanks for the discussions link.
@grishka should have just provided that to me.
I will use it going forward 👌🏻

Is there a general Mastodon page on here where we can discuss topics about the app?

**Comment by andypiper** [comment]
The Discussions page is the location to go. Do not follow up on any of the invalid issues on the Android repository or I remove your commenting permission from our organisation.
