### ISSUE TITLE
HTML escaping in notifications

### ISSUE THREAD

**Issue by jarofgreen** [mastodon/mastodon-android#917]
I just tooted this and someone liked it: https://mastodon.online/@jarofgreen/113442769078224887

The notification I got had all the content of my toot but none of the content between angle brackets < >

Is there a HTML escaping issue in the notification?

**Comment by grishka** [comment]
Duplicate of #235, but also it's a server-side issue so https://github.com/mastodon/mastodon/issues/19718

**Comment by jarofgreen** [comment]
Thank you!
