### ISSUE TITLE
Too many emojis on instance cause crash, hits 1MB android sqlite cursor size limit

### ISSUE THREAD

**Issue by likeazir** [mastodon/mastodon-android#919]
The app crashes during compose/opening notifications with instances that have a large number of emojis.

My Instance has a about 10k local emojis available. The Mastodon app stores info about those in a sqlite database.

Sqlite for Android has a 1MB limit for cursors. As custom emojis are stored in just one row, an instance with many emojis can cause the size of the row to go over the limit.

This causes [readInstanceInfo](https://github.com/mastodon/mastodon-android/blob/20ed47032ece944e5a32bf2afbf2e9f1030d9a37/mastodon/src/main/java/org/joinmastodon/android/api/session/AccountSessionManager.java#L384) to fail. 
Then, `loadedInstances` is then set to true, despite the try block failing. I suspect the state of the class is then inconsistent, causing a crash.

Let me know if you need me to generate some logcat output to further investigate.

I implemented rudimentary paging as a [quick fix](https://github.com/owo-uwu-nyaa/meowstodon/commit/5c75ada63298e879363e8289f52f33dab9e94cc9) for myself and the app no longer crashes during compose/notifcation view, it's not a very performant solution though

**Comment by grishka** [comment]
I mean 10k is kinda far into the territory where it feels like the entire list shouldn't be stored in the memory, and should have its own table in the database that is searched as you type. But then it also presents its own challenge about updating them (you'd have to diff the lists somehow) 🤔

**Comment by grishka** [comment]
Your solution looks good to me, and I don't think the performance would take *that* much of a hit, but it can be optimized a bit by retrieving the first part of the string and its total length in the initial query. This way when the string does fit into 1MB, it would not require extra queries. So the initial query would become
```sql
SELECT domain, instance_obj, last_updated, version, length(emoji) AS emoji_len, substring(emoji, 0, min(80000, length(emoji))) AS emoji FROM instances
```
But then also SQLite docs themselves say that [you don't really need to cram as much as possible into a single query](https://www.sqlite.org/np1queryprob.html) unlike you do have to do for client-server databases like MySQL.

**Comment by likeazir** [comment]
I agree its a bit much, but there are shockingly many instances with huge numbers of emojis. 
Multiple megabytes for the custom_emojis is rare, but even mstdn.social is a whole megabyte. (https://mstdn.social/api/v1/custom_emojis)

It's not ideal to store this in a database but it's fine for now

**Comment by likeazir** [comment]
I also updated the pagination, and also made a separate query for each individual domain to prevent crashes.
I don't think this will be detrimental to performance.
If you want to merge it, I made a pull request, but I also understand this many emojis may not exactly be supported by mastodon.

**Comment by grishka** [comment]
> but I also understand this many emojis may not exactly be supported by mastodon.

If it's supported by stock Mastodon (and at this point I'm sure there's no limit on the number of emojis an instance can have), this means is must be supported by the app, or at least the app should handle this situation gracefully. Which it now does, thanks to your PR.

(the performance of the autocompleter still needs some work, I'll probably move it to a background thread, but at least nothing should crash any more)
