### ISSUE TITLE
Version 2.9.0 (128) crashing

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#927]
Version 2.9.0 (128) works perfectly a few couple of minutes after logging in my account, next it turns impossible either posting, replying, sharing or tapping notifications bell.

I delete all data, log in, and the same issue is repeated.
Uninstalling / Installing does the same.

Google Play Services Updated.

Instances:
mastodon.social and/or mastodon.la
OS: Android 11
Redmi 9A 

(can't send crash logs)

**Comment by grishka** [comment]
Should be fixed in 2.9.1. The PR to fix support for servers with thousands of emojis went horribly wrong because of one misplaced `return` statement that I didn't notice. I'm so tired of these same "instance was null" crashes over and over again. Hopefully this is the last time this happens.

**Comment by grishka** [comment]
Does 2.9.1 work for you?

It's currently on review in Google Play and it's especially in these kinds of situations that their day-long reviews feel agonizingly slow. All while the previous buggy version is happily crashing for hundreds of users.

**Comment by jotaluissoy** [comment]
Sorry, I didn't say that yes, crashings seem to be fixed in this latest release.

**Comment by grishka** [comment]
Yay. Thank you for giving me the confidence I desperately needed!
