### ISSUE TITLE
Scale down pictures and video for upload

### ISSUE THREAD

**Issue by vwbusguy** [mastodon/mastodon-android#93]
The main Mastodon servers appear to have a 10mb limit for pictures and 40mb limit for videos.  Unfortunately, on my Samsung phone, this means almost every picture of video I take is unable to be posted.  A workaround I've found for pictures is to take a screenshot of the picture and post that, which is not a good user experience, and there isn't an obvious workaround for videos. 

If the Android app could simply downscale images and videos that exceed these limits, as many other chat platforms already do, it would make sharing media much more convenient via the app.

**Comment by grishka** [comment]
Pictures are already being downscaled, always were. For videos, it's, let's say, a very non-trivial thing to do. I know *how* to do it, it's just that it requires an ungodly amount of code and extensive testing on different devices. Maybe sometime in the future.

**Comment by vwbusguy** [comment]
They aren't for me.  I just get an error that the picture is over 10mb and then it fails to upload. Version 1.0.3 on Samsung Galaxy S20+.

**Comment by grishka** [comment]
Which format are you trying to upload? If it's png, it gets downscaled to a png, so if it's something poorly compressible, it can still exceed the limit.

**Comment by vwbusguy** [comment]
Here's the data on one of the pictures that failed to upload.  This is with the default settings for my 2 year old Samsung.

![Screenshot_20220428-180531_Gallery](https://user-images.githubusercontent.com/5474941/165870781-bb5bc5d6-a39e-4750-bd3e-81c6b0d9da7a.jpg)

Does the app not have support for downscaling jpegs?

**Comment by grishka** [comment]
It does, and it should fit them into those limits 🤔
