### ISSUE TITLE
"Post" button and "Notifications" crashes the app after yesterday's update

### ISSUE THREAD

**Issue by PimpOfSune** [mastodon/mastodon-android#931]
Was using it just fine two days ago.
App is read-only since yesterday: "Post" button (bottom right of Home and Profile screen) crashes the app now.

"Notifications" crashes the app too. This may or may not be related to me getting "filtered notifications" in notifications yesterday. As seen on  https://mastodon.social/notifications :
![Image](https://github.com/user-attachments/assets/db68a342-f698-46c2-abbf-ae7a5c03b8cc)

Samsung A01, Android 12, everything is up to date including Mastodon app, no root (no fiddling with system at all).

**Comment by grishka** [comment]
Now there's the *today's update* that fixes that. It just went live on Google Play a few minutes ago.

**Comment by PimpOfSune** [comment]
Golly! Now THAT's proper bug handling! Appreciated!
Confirming:
- update present
- update installs
- update indeed fixes both crashes
Closing as "fixed with extreme prejudice".

**Comment by grishka** [comment]
Just a coincidence 😜

This bug affected hundreds of users and Google actually took half a day to review the update.
