### ISSUE TITLE
Crashings seem not be fixed yet.

### ISSUE THREAD

**Issue by jotaluissoy** [mastodon/mastodon-android#934]
Though issues 927 & 931 were closed, I've been noticing that some crashings are still accompanying the app.

A friend in Mastodon says that she has the version 2.9.1 (129) and she could hardly use it because of the continuous crashings (Android 10).

I've been using the same app version for 24 hours or something and I can say that unfortunately crashings have not been fixed yet, though my case is faraway from the previous refered example.

I cannot send any log, but if it helps I've noticed that it happens when I have the app working and go and open one or two more different ones, so when returning it looks like no connected so it crashes when I tap any functional button of the app (post, reply, notifications bell, etc). My cellphone is a Redmi 9A running Android 11.

Please, I'm so sorry to open this issue again for I know how bad this trouble causes to the job and enthusiasm of the devs.

Thanks for reading and take it easy.

**Comment by grishka** [comment]
You mean notifications stop working **AFTER** they have already worked?!

**Comment by grishka** [comment]
What about 2.9.2? There's also another fix in 2.9.3 but that one is specific to the onboarding flow.

**Comment by jotaluissoy** [comment]
Hello. Just perfect.
Good job!
Maybe you can close the issue.
