### ISSUE TITLE
QR code scanning does not work in the current version

### ISSUE THREAD

**Issue by nrgeen** [mastodon/mastodon-android#939]
Scanning profile QR codes is currently not possible. 
I tried it on a Pixel 7a and a Samsung Galaxy A52 5G with the latest software update. The app behaves identically on both devices.

tested version: 2.9.3 (132)

**What should the app do?**
Clicking on the QR code icon under ‘Discover’ opens the QR code scanner. I focus on the QR code and the profile whose URL is stored opens.

**What is currently happening:**
As soon as the app has focussed on the QR code, the app crashes and closes.

We have created a new start page for our instance at [https://start.libori.social](https://start.libori.social) to make it easier for newcomers to find interesting accounts. Adding QR codes seems useful to us and can make it easier to get started. A functioning QR code scanner is helpful for this.

**Comment by mhaseneyer** [comment]
Can confirm with an Android 14 phone (Nokia/HMD Global), app crashes repeatedly. Other QR scanner apps ("Binary Eye" on the same phone, or the iOS Camera app on an iOS phone) do recognize the QR codes well.

The QR codes are just the web pages of the Mastodon profiles, so this part should be okay.

**Comment by grishka** [comment]
Proguard fucked everything up yet again. Sigh. It works in debug builds, but doesn't work in release ones.

**Comment by grishka** [comment]
Whenever the next update will be released. I don't have exact plans for that because there currently aren't any new features that are ready for development, but I might release an update that fixes various minor crashes I'm seeing in Google Play.

**Comment by nrgeen** [comment]
That would be great.
We would also wait until the function works on Android devices before promoting our site.
