### ISSUE TITLE
Explore, timeline and "for you" page not available

### ISSUE THREAD

**Issue by mphojele** [mastodon/mastodon-android#95]
Some of the pages that are supposed to appear after clicking the explore button at the bottom are not there. I'm told im missing the News, Community and "For You" pages. 

## Version

![20220429_122145](https://user-images.githubusercontent.com/44401412/165978159-8f573edf-54fc-4e02-94dd-5c1cd21d036e.jpg)

## Available pages:

![Screenshot_20220429-174251_Mastodon](https://user-images.githubusercontent.com/44401412/165978380-a554d0df-f123-4254-a0d4-6f69358c7b33.jpg)
![Screenshot_20220429-174256_Mastodon](https://user-images.githubusercontent.com/44401412/165978400-c9b9b9ea-d892-4db1-9b8b-7675fae133ca.jpg)

Already tried uninstalling and installing

**Comment by grishka** [comment]
The tab bar is scrollable...

**Comment by mphojele** [comment]
@grishka I'm aware but you can see from the screenshot in landscape that I don't have anymore tabs
![Screenshot_20220429-220809_Mastodon](https://user-images.githubusercontent.com/44401412/166062430-c513f4b4-52c9-4cd1-9006-83cc529e8ef8.jpg)

**Comment by grishka** [comment]
You have search active. You have to exit the search mode to access those tabs.

**Comment by mphojele** [comment]
Has a new screenshot and it's deactivated 

![Screenshot_20220430-093040_Mastodon](https://user-images.githubusercontent.com/44401412/166096413-e6b0a8ea-2e9d-421e-99da-ae3509ca6d84.jpg)

**Comment by realpixelcode** [comment]
> You have search active. You have to exit the search mode to access those tabs.

Maybe make it a bit more obvious when the search bar is focused? (e.g. a blue border)

**Comment by mphojele** [comment]
@grishka I really can't figure out how to disable the search. I tried clicking outside the search bar, clicking the tabs nothing is happening for me.

**Comment by grishka** [comment]
You're saying that as if it activates _by itself_?! It should not ever activate unless you tap the text field. And there's the <- button that should exit from it, as well as the system back button/gesture.

**Comment by mphojele** [comment]
When switching to that (explore)tab the cursor is already blinking on the search bar. Clicking outside does nothing

**Comment by grishka** [comment]
Huh? No, that should definitely, absolutely not happen. I should probably add another focusable view there to make sure Android doesn't try being smart and "helpful" by putting focus where it doesn't belong.

**Comment by mphojele** [comment]
On some of the screenshots(the latest one) I sent you can probably see that the cursor is not on the search bar so the bar isn't focused. Does my android version matter? it's android 8

**Comment by mphojele** [comment]
On some of the screenshots(the latest one) I sent you can probably see that the cursor is not on the search bar so the bar isn't focused. Does my android version matter? it's android 8

**Comment by mphojele** [comment]
Yey! Fixed! (just updated) Thank you for your patience :smile:
