### ISSUE TITLE
Small mistake in German translation (followers/following)

### ISSUE THREAD

**Issue by carbeck** [mastodon/mastodon-android#97]
https://github.com/mastodon/mastodon-android/blob/10a5bf0a823e65b1264aea108e1e0ed587a242bb/mastodon/src/main/res/values-de-rDE/strings.xml#L31-L38

The translation of the Android app doesn't align with the web client:

Web client:
![grafik](https://user-images.githubusercontent.com/2134500/165990972-61a0ab9d-6599-4c54-82fb-60306e8a9d5c.png)

Android App:
![grafik](https://user-images.githubusercontent.com/2134500/165991023-2978605c-9002-4135-afeb-2568f48350b3.png)

I think it would be best to use the same strings as in the web client, since those are grammatically/semantically accurate. The current translations in the Android app are misleading in that:
* Follower = people who are following you
* Folgende = people who are following you
* Folgt = follows (i.e. people you follow)

Essentially, I believe it ought to be this way:
```
<plurals name="followers">
	<item quantity="one">Folgender</item> <!-- or: Folgende*r -->
	<item quantity="other">Folgende</item>
</plurals>
<plurals name="following">
	<item quantity="one">Folgt</item>
	<item quantity="other">Folgt</item>
</plurals>
```

**Comment by grishka** [comment]
You can edit the translations [on Crowdin](https://crowdin.com/project/mastodon-for-android).
